define(function(require,exports,module){
	module.exports={
		
			mid_top:''
				+'<div class="mid_top_sub clearfix">'
					+'<div class="before_bg left"></div>'
					+'<ul class="left">'
						+'{{each data as value}}'
							+'<li class="item left" show-type={{value}} >{{value}}</li>'
						+'{{/each}}'
					+'</ul>'
					+'<div class="after_bg left"></div>'
				+'</div>',
			
			mid_Tab:''
				+'<div class="mid_tab_sub">'	
					+'<ul class="mideTab_content_sub clearfix">'
						+'{{each data as val a}}'
							+'<li class="left" cp_type={{val["cp_type"]}} game_lx={{val["game_lx"]}} latetime={{ val["latetime"] }}>'
								+'<span class="status{{val["status"]}}"></span>{{val["game_name"]}}'
							+'</li>'
						+'{{/each}}'
					+'</ul>'
				+'</div>',
		
			mid_Tag:''
				+'<div class="mid-Tag-sub clearfix">'
					+'{{each menu as value i}}'
						+'<div pan_type={{i}} class="midTag_child">{{value["actName"]}}</div>'
					+'{{/each}}'
				+'</div>',
		
			article_top:''
				+'<div class="left-Head">'
					
					+'<div class="leftHead clearfix">'
						+'<h2> {{ data["gameStatus"]["game_name"] }} </h2>'
						+'<span class="leftHead_tag pankou">E盘</span>'
					+'</div>'
					+'<div class="leftTime">'
						+'最新开奖&nbsp;&nbsp;第<span>{{gameResult["qer2"]}}期({{gameResult["game_time"]}}) </span>'
					+'</div>'
					
					+'<div class="clearfix">'
						+'{{each gameResult["px"] as sx}}'
						+'{{if hasT(sx)}}'
							+'{{if data["gameStatus"]["game_lx"]==22 || data["gameStatus"]["game_lx"]==10}}'
								+'<div class="leftNum_child crossbar">▬</div>'
							+'{{/if}}'
							+'<div class="leftNum_child lanBox">{{ gameResult["number"][sx]["num"] }}</div>'
						+'{{else}}'
							+'<div class="leftNum_child {{gameResult["number"][sx]["coler"]}}Box"> {{ gameResult["number"][sx]["num"] }} </div>'
						+'{{/if}}'
						+'{{/each}}'
					+'</div>'
					
				+'</div>'
				+'<div class="left-Body">'
					+'<div class="leftLast">'
						+'<div>当前第{{ data["gameStatus"]["periods2"] }}期</div>'
						+'<div>'
							+'<span class="leftHead_tag reload_btn">刷新</span>'
							+'<span class="leftHead_tag rule">规则</span>'
							+'{{if data["gameStatus"]["cp_type"]=="bjkl8" || data["gameStatus"]["cp_type"]=="k3" }}<span class="leftHead_tag toggleStyle">切换</span>{{/if}}'
						+'</div>'
					+'</div>'
					+'<div class="leftOpTime_show shi-jian" time="{{data["gameStatus"]["latetime"]}}"> {{ timeFormat( data["gameStatus"]["latetime"] ) }} </div>'
				+'</div>',
			
			article_middle:''
				+'<div class="article_middle_nav">'
					+'<div class="clearfix">'
						+'<span class="nowList active">投注单</span>'
						+'<span class="beenList ">最近十注</span>'
					+'</div>'
				+'</div>'
				+'<div class="article_middle_box default-skin clearfix">'
					
					+'<div class="article_middle_nowList_content">暂无投注信息</div>'
					+'<div class="article_middle_beenList_content">THIS IS 最近十注</div>'
				
				+'</div>',
		
			Frame_10:''
				+'<div class="mid_box {{itemID}}_box frame_10 {{if cp_type=="bjkl8"}} module01 {{/if}}" {{if cp_type=="bjkl8" && k8_module!="module01" }} style="display:none"  {{/if}}  itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'{{if !date["isSpecial"]}}'
							+'<div class="midTWord_tab clearfix">'
								+'<div class="midTWord_tab_sub clearfix">'
									+'{{each date["title"] as value i}}'
										+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
											+'{{value}}'
										+'</div>'
									+'{{/each}}'
								+'</div>'
							+'</div>'
							+'<div class="midTWord_outer clearfix">'
								+'{{each date["content"] as value i}}'
									+'<div class="midTWord_outer_sub midTWord_child clearfix odds_box" name={{ current+date["index"][i] }}>'
										+'<div class="midTWord_child_badges_box"><div class=" {{　midTWord_child_badges(value,itemID) }}  {{ if itemID=="LHZMT" || itemID=="GXZM" }} {{ getBgColor( itemID,value ) }} {{/if}}">{{value}}</div></div>'
										+'<div class="left showNum_text_box clearfix odds_box_sub {{if itemID=="SZHS" || getBgColor(itemID,value)=="lhc_text" || getBgColor(itemID,value)=="gxklsf_text"}} showNum_text_box_SZHS {{/if}}" name={{ current+date["index"][i] }}>'
											+'<div class="midTWord_child_showNum odds_pl" name={{ current+date["index"][i] }}>{{ odds["newOdds"][ current+date["index"][i] ] }}</div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'{{else if date["isSpecial"]}}'
							+'{{if date["sjwx"] || date["zfb"]}}'
								+'{{if date["title"]}}'
									+'<div class="midTWord_tab clearfix">'
										+'<div class="midTWord_tab_sub clearfix">'
											+'{{each date["title"] as value i}}'
												+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
													+'{{value}}'
												+'</div>'
											+'{{/each}}'
										+'</div>'
									+'</div>'
								+'{{/if}}'
								+'<div class="midTWord_outer clearfix">'
									+'{{each date["content"] as value i}}'
										+'<div class="left midTWord_outer_sub midTWord_child_sjwx_zfb clearfix odds_box" name="{{current+i}}">'
											+'<div class="left midTWord_child_badges  sjwx_zfb_name">{{value["name"]}}</div>'
											+'<div class="left sjwx_zfb_number">[{{value["number"]}}]</div>'
											+'<div class="right sjwx_zfb_odds odds_pl" name={{current+i}} title="点击赔率进行下注">{{ odds["newOdds"][current+i] }}</div>'
										+'</div>'
									+'{{/each}}'
								+'</div>'
							+'{{else if itemID=="PKDM"}}'
								+'<table cellpadding=0 cellspacing=0 width=100% id={{itemID}}><tbody>'
									+'<tr>'
										 
										+'{{each date["title"] as value i}}'
											+'<td class="midAWtwo_row_childhead {{if value==""}} table_td_no_right_bottom {{/if}}" i={{i}}>{{value}}</td>'
										+'{{/each}}'
										
										
									+'</tr>'
									+'{{each date["content"] as value i}}'
										+'<tr i={{value}}>'
											
											+'<td class="midAWtwo_row_childhead midAWtwo_row_childhead_{{value}}">{{value}}</td>'
											+'{{each date["title"] as val a}}'
												+'{{if val}}'
													+'<td class="odds_box" name={{ a+value  }}>'
														+'<span class="odds_pl" name={{a+value}}>{{ odds["newOdds"][a+value] }}</span>'
													+'</td>'
												+'{{/if}}'
											+'{{/each}}'
											
										+'</tr>'
									+'{{/each}}'
								+'</tbody></table>'
							+'{{/if}}'
						+'{{/if}}'
					+'</div>'
				+'</div>',
			
			Frame_09:''
				+'<div class="mid_box {{itemID}}_box frame_09" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'<table cellpadding=0 cellspacing=0 width=100% ><tbody>'
							+'{{ each date["tr"] as value i}}'
								+'<tr>'
									+'<td class="midAWtwo_row_childhead"><div>{{ value["lable"] }}</div></td>'
									+'{{each value["play_lx"] as val a}}'
										+'<td class="frame_09_td_odds odds_box" name={{a}}><span class="frame_09_descrite">{{val}}</span><span class="showNum odds_pl">{{odds["newOdds"][a]}}</span></td>'
									+'{{/each}}'
								+'</tr>'
							+'{{/each}}'
						+'</tbody></table>'
					+'</div>'
				+'</div>',
		
			Frame_08:''
				+'<div class="mid_box {{itemID}}_box frame_08" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'<div class="midTWord_tab clearfix">'
							+'<div class="midTWord_tab_sub clearfix">'
								+'{{each date["title"] as value i}}'
									+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
										+'{{value}}'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
						+'<div class="midTWord_outer clearfix">'
							+'{{if itemID=="LHLX"}}'
								+'<div class="frame_08_title clearfix">'
									+'<div class="right">'
										+'<span>快速选择:</span>'
										+'{{each date["quick_choose"] as value i}}'
											+'<span class="quick_choose_btn" data-value="{{value.join(",")}}">{{i}}</span>'
										+'{{/each}}'
									+'</div>'
								+'</div>'
							+'{{/if}}'
							+'{{each date["content"] as value i}}'
								+'<div class="clearfix">'
									+'{{each value["lotteryNo"] as val a}}'
									+'{{if val}}'
										+'<div class="left midTWord_child clearfix">'
											+'<div class="midTWord_child_badges_box"><div class="frame_08_sx_name "> {{val}} </div></div>'
											+'{{if value["lotteryNumber"]}}'
												+'<div class="left clearfix frame_08_number_box">{{ #getFrame08Bg(itemID,value["lotteryNumber"][a])  }}</div>'
											+'{{else}}'
												+'<div class="left clearfix frame_08_number_box">{{#getFrame08Number(itemID,a,odds) }}</div>'
											+'{{/if}}'
											+'<div class="right frame_08_odds_box"><label class="clearfix"><div class="left odds_pl">{{odds["newOdds"][current+a]}}</div><input type="checkbox" data-i={{a}} name={{itemID+"checkbox"}} value={{current+a}} class="left"> </label></div>'
										+'</div>'
									+'{{/if}}'
									+'{{/each}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
						+'<div class="frame_08_odds_box_sub">'
							+'[<span>点击选择框生成组合*以各组合内的最{{if itemID=="LHLW"}}高 {{else}}低 {{/if}}赔率为准*</span>]'
							+'<span class="odds_pl"></span>'
							+'<input type="button" value="确定" class="sure">'
							+'<input type="button" value="重置" class="empty">'
						+'</div>'
					+'</div>'
				+'</div>',
		
			Frame_07:''
				+'<div class="mid_box {{itemID}}_box frame_07" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'<div class="midTWord_tab clearfix">'
							+'<div class="midTWord_tab_sub clearfix">'
								+'{{each date["title"] as value i}}'
									+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
										+'{{value}}'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
						+'<div class="midTWord_outer clearfix">'
							+'{{each date["content"] as value i}}'
								+'<div class="clearfix">'
									+'{{each value["lotteryNo"] as val a}}'
										+'<div class="left midTWord_child clearfix">'
											+'<div class="midTWord_child_badges_box"><div class="left midTWord_child_badges frame_07_text" name={{a}}> {{val}} </div></div>'
											+'<div class="left clearfix frame_07_number_box">{{#getFrame08Number(itemID,a,odds) }}</div>'
										+'</div>'
									+'{{/each}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
						+'<div class="frame_07_odds_box">'
		
							+'[<span>点击以上名称生成赔率</span>]<span class="odds_pl"></span>'
						+'</div>'
					+'</div>'
				+'</div>',
		
			Frame_06:''
				+'<div class="mid_box {{itemID}}_box frame_06" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'<div class="midTWord_outer clearfix">'
							+'{{each date["content"] as value i}}'
								+'<div class="clearfix">'
									+'{{each value["lotteryNo"] as val a}}'
										+'<div class="left midTWord_child odds_box clearfix" name={{current+a}}>'
											+'<div class="midTWord_child_badges_box"><div class="frame_06_sx_name" name={{a}}> {{val}} </div></div>'
											+'<div class="left clearfix frame_06_number_box">{{#getFrame08Number(itemID,a,odds) }}</div>'
											+'<div class="right  odds_pl" name={{current+a}}>{{odds["newOdds"][current+a]}}</div>'
										+'</div>'
									+'{{/each}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
					+'</div>'
				+'</div>',
			
			Frame_05:''
				+'<div class="mid_box {{itemID}}_box frame_05" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'{{if date["title"]}}'
						+'<div class="midTWord_tab clearfix">'
							+'<div class="midTWord_tab_sub clearfix">'
								+'{{each date["title"] as value i}}'
									+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}"  {{if date["max"]}} max={{date["max"][i]}} {{/if}}>'
										+'{{value}}'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
						+'{{/if}}'
						+'<div class="midTWord_outer clearfix">'
							+'{{if itemID!="LHLM" && itemID!="KBBJKLXH"}}'
								+'{{each date["content"] as value i}}'
									+'<div class="clearfix frame_05_box" {{if value["TrIDName"]}} name={{ value["TrIDName"] }} {{/if}}>'
										+'{{if value["lable"]}}'
											+'<div class="left frame_05_box_text" name={{value["TrIDName"]}}>{{value["lable"]}}</div>'
										+'{{/if}}'
										+'<div class="left frame_05_number_box">'
											+'{{each value["td"] as val }}'
												+'{{if val}}'
													+'<div class="left clearfix {{if itemID=="LHZXBZ" }}frame_05_number_box_sub {{/if}}">'
														+'{{if itemID=="LHZXBZ" }} <div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div> {{/if}}'
														+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}  {{if itemID=="PKQE" || itemID=="PKQS" || itemID=="PKQSI"}} bjpks_car_{{val}} {{/if}}">{{val}}</div>'
													+'</div>'
												+'{{/if}}'
											+'{{/each}}'
										+'</div>'
										
										+'{{if itemID=="LHZXBZ" }}'
											+'<div class="left combination {{itemID}}_combination frame_05_combination">'
												+'<div class="combination_header">'
													+'注单号码<div class="combination_number"></div>'
												+'</div>'
												+'<div class="combination_content">'
													+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
													+'<div class="combination_content_sub"></div>'
												+'</div>'
											+'</div>'
										+'{{/if}}'
									+'</div>'
								+'{{/each}}'
							+'{{else if itemID=="LHLM"}}'
								+'<div class="clearfix frame_05_box">'
									+'<div class="frame_05_box_title">'
										+'<label><input type="radio" value="zx" checked name="{{itemID}}_radio">自选</label>'
										+'<label><input type="radio" value="dt" name="{{itemID}}_radio">胆拖</label>'
									+'</div>'
									+'<div class="frame_05_number_box_parent">'
										+'<div class="zx">'
												+'<div class="left frame_05_number_box">'
													+'{{each date["content"]["tr1"]["td"] as val }}'
														
															+'<div class="left clearfix frame_05_number_box_sub">'
																+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
																+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
															+'</div>'
														
													+'{{/each}}'
												+'</div>'
											
												+'<div class="left combination {{itemID}}_combination frame_05_combination">'
													+'<div class="combination_header">'
														+'注单号码<div class="combination_number"></div>'
													+'</div>'
													+'<div class="combination_content">'
														+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
														+'<div class="combination_content_sub"></div>'
													+'</div>'
												+'</div>'
			
										+'</div>'
										+'<div class="dt" style="display:none;">'
											+'<div class="left clearfix" style="width:530px;">'
												+'<div>胆码</div>'
												+'<div class="left dm frame_05_number_box">'
													
													+'{{each date["content"]["tr1"]["td"] as val }}'
														
														+'<div class="left clearfix frame_05_number_box_sub">'
															+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
															+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
														+'</div>'
														
													+'{{/each}}'
												+'</div>'
												+'<div class="left tm frame_05_number_box">'
													+'<div>拖码</div>'
													+'{{each date["content"]["tr1"]["td"] as val }}'
														
															+'<div class="left clearfix frame_05_number_box_sub">'
																+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
																+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
															+'</div>'
														
													+'{{/each}}'
												+'</div>'
											+'</div>'
												+'<div class="left combination {{itemID}}_combination_dt frame_05_combination">'
													+'<div class="combination_header">'
														+'注单号码<div class="combination_number"></div>'
													+'</div>'
													+'<div class="combination_content">'
														+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
														+'<div class="combination_content_sub"></div>'
													+'</div>'
												+'</div>'
										+'</div>'
									+'</div>'
								+'</div>'
							+'{{else if itemID=="KBBJKLXH"}}'		
									+'<div class="clearfix left frame_05_box">'
										+'{{each date["content"] as value i}}'
											+'<div class="left frame_05_number_box">'
												+'{{each value["td"] as val }}'
													+'{{if val}}'
														+'<div class="left clearfix ">'
															
															+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(lhc,itemID,val)}} ">{{val}}</div>'
														+'</div>'
													+'{{/if}}'
												+'{{/each}}'
											+'</div>'
										+'{{/each}}'
									+'</div>'
									+'<div class="left combination {{itemID}}_combination frame_05_combination">'
										+'<div class="combination_header">'
											+'注单号码<div class="combination_number"></div>'
										+'</div>'
										+'<div class="combination_content">'
											+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
											+'<div class="combination_content_sub"></div>'
										+'</div>'
									+'</div>'
							+'{{/if}}'
						+'</div>'
						+'<div class="frame_05_odds_box">'
							
							+'[<span>点击以上数字生成{{if itemID=="LHZXBZ" || itemID=="LHLM" || itemID=="KBBJKLXH"}}组合{{else}} 赔率 {{/if}}</span>]'
							+'<span class="odds_pl">'
								+'{{if itemID=="LHZXBZ"}}'
									+'{{odds["newOdds"][itemID+current]}}'
								+'{{else if itemID=="LHLM"}}'
									+'{{odds["newOdds"][current]}}'
								+'{{else if itemID=="KBBJKLXH"}}'
									+'{{odds["newOdds"][current]}}'
								+'{{/if}}'
							+'</span>' 
							+'<input type="button" value="确定" class="sure"><input type="button" value="取消" class="empty">'
						+'</div>'
					+'</div>'
				+'</div>',
		
			Frame_04:''
				+'<div class="mid_box {{itemID}}_box frame_04" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'<table width=100% cellpadding=0 cellspacing=0 ><tbody>'
							+'<tr>'
								+'<td class="midAWtwo_row_childhead table_td_no_right_bottom">&nbsp;</td>'
								+'{{each date["title"] as value }}'
									+'<td class="midAWtwo_row_childhead">{{value}}</td>'
								+'{{/each}}'
							+'</tr>'
							+'{{each date["content"] as val i}}'
								+'<tr>'
									+'<td class="midAWtwo_row_childhead">{{val["lable"]}}</td>'
									+'{{if !val["colspan"]}}'
										+'{{each val["play_lx"] as valu a}}'
											+'<td><label><input type="radio" value={{valu}} name="{{itemID+a}}">{{odds["newOdds"][valu]}}</label></td>'
										+'{{/each}}'
									+'{{else}}'
										+'<td  colspan={{ val["colspan"] }}>'
											
											+'<span class="frame_04_text">点击按钮生成赔率</span>'
											+'<span class="frame_04_odds_pl odds_pl"></span>'
											
										+'</td>'
										+'<td>'
											+'<input type="button" value="确定" class="sure" ><input type="button" value="重置" class="empty">'
										+'</td>'
									+'{{/if}}'
								+'</tr>'
							+'{{/each}}'
						+'</tbody></table>'
					+'</div>'
				+'</div>',
			
			Frame_03:''
				+'<div class="mid_box {{itemID}}_box frame_03" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'{{if date["title"]}}'
						+'<div class="midTWord_tab clearfix">'
							+'<div class="midTWord_tab_sub clearfix">'
								+'{{each date["title"] as value i}}'
									+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
										+'{{value}}'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
						+'{{/if}}'
						+'<div class="midTWord_outer clearfix">'
							+'{{each date["content"] as value i}}'
								+'<div class="frame_03_box clearfix" {{if value["lable"]}}name={{value["TrIDName"]}} {{/if}}>'
									+'{{if value["lable"]}}'
										+'<div class="left frame_03_text" name={{value["TrIDName"]}}>{{value["lable"]}}</div>'
									+'{{/if}}'
									+'<div class="left frame_03_number_box">'
										+'{{each value["td"] as tdArr a }}'
											+'<div class="left frame_03_number midTWord_child_badges">'
												+'{{tdArr}}'
											+'</div>'
										+'{{/each}}'
									+'</div>'
								+'</div>'
							+'{{/each}}'
						+'</div>'
						+'<div class="frame_03_odds_box">'
							+'{{if itemID=="YWRX" || itemID=="YWQSZUX" || itemID=="YWQEZUX" || itemID=="YWQSZHX" || itemID=="YWQEZHX"}}'
								+'[<span>点击以上数字生成组合</span>]'
								+'<span class="odds_pl">'
									+'{{if itemID=="YWRX"}}'
										+'{{odds["newOdds"][current]}}'
									+'{{else if itemID=="YWQSZUX" || itemID=="YWQEZUX" || itemID=="YWQSZHX" || itemID=="YWQEZHX"}}'
										+'{{odds["newOdds"][itemID]}}'
									+'{{/if}}'
								+'</span>'
								+'<input type="button" value="确定" class="sure"><input type="button" value="取消" class="empty">'
							+'{{else}}'
								+'[<span>点击以上数字生成赔率</span>]'
								+'<span class="odds_pl"></span>'
							+'{{/if}}'
							
						+'</div>'
					+'</div>'
				+'</div>',
		
			Frame_02:''
				+'<div class="mid_box {{itemID}}_box frame_02" itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'{{if date["title"]}}'
						+'<div class="midTWord_tab clearfix">'
							+'<div class="midTWord_tab_sub clearfix">'
								+'{{each date["title"] as value i}}'
									+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
										+'{{value}}'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
						+'{{/if}}'
						+'<div class="midTWord_outer clearfix">'
							+'{{each date["content"] as value i}}'
							+'<div class="clearfix frame_02_box" name={{value["TrIDName"]}}>'
								+'<div class="left frame_02_box_text" name={{value["idName"]}}>'
									+'{{if date["current_text"]}} {{date["current_text"][i]}}  {{else}} {{value["lable"]}}  {{/if}}'
								+'</div>'
								+'<div class="left clearfix frame_02_number_box">'
									+'{{each value["td"] as val a}}'
										+'<div class="left frame_02_number midTWord_child_badges " i={{val}}>{{val}}</div>'
									+'{{/each}}'
								+'</div>'
							+'</div>'
							+'{{/each}}'
						+'</div>'
						+'<div class="frame_02_info">[<span>点击以上数字生成赔率进行投注</span>]</div>'
						+'<div class="frame_02_odds_box clearfix">'
						+'</div>'
					+'</div>'
				+'</div>',
		
			Frame_01:''
				+'<div class="mid_box {{itemID}}_box frame_01 {{if cp_type=="bjkl8"}} module01 {{/if}}"  {{if cp_type=="bjkl8" && k8_module!="module01" }} style="display:none"  {{/if}} itemid={{itemID}}>'
					+'<div class="mid-Title">{{title}}</div>'
					+'<div class="mid-TWord">'
						+'{{if date["isTable"]}}'
							+'{{if date["title"]}}'
								+'<table cellpadding=0 cellspacing=0><tbody>'
									+'<tr>'
										+'<td class="midAWtwo_row_childhead table_td_no_right_bottom">&nbsp;</td>'
										+'{{each date["title"] as tdArr }}'
											+'<td class="midAWtwo_row_childhead">{{tdArr}}</td>'
										+'{{/each}}'
									+'</tr>'
									+'{{each date["content"] as trArr }}'
										+'<tr>'
											+'<td class="midAWtwo_row_childhead" ><div>{{trArr["lable"]}}</div></td>'
											+'{{each date["title"] as tdArr a}}'
												+'<td>'
													+'{{if odds["newOdds"][ trArr["play_lx"]+a ]}}'
													+'<div class="odds_box clearfix" name={{trArr["play_lx"]+a}}>'
														+'<span class="frame_01_table_odds left odds_pl" name={{trArr["play_lx"]+a}}>{{odds["newOdds"][ trArr["play_lx"]+a ] }} </span>'
														+'<input type="text" class="midAWtwo_row_childAsh">'
													+'</div>'
													+'{{/if}}'
												+'</td>'
											+'{{/each}}'
										+'</tr>'
									+'{{/each}}'
								+'</tbody></table>'
							+'{{else}}'
								+'<table cellpadding=0 cellspacing=0><tbody>'
									+'{{each date["content"] as trArr}}'
										+'<tr>'
											+'<td class="midAWtwo_row_childhead {{if !trArr["lable"] }} table_td_no_right_bottom {{/if}}" >{{if trArr["lable"]}}<div class="midAWtwo_row_childhead"> {{trArr["lable"]}} </div>{{/if}}</td>'
											+'{{if trArr["isTitle"]}}'
												+'{{each trArr["td"] as tdArr}}'
													+'<td class="midAWtwo_row_childhead">{{tdArr}}</td>'
												+'{{/each}}'
											+'{{else}}'
												+'{{each trArr["play_lx"] as tdArr}}'
													+'<td>'
														+'<div class="odds_box clearfix" name={{tdArr}}>'
															+'<span class="frame_01_table_odds left odds_pl" >{{ odds["newOdds"][ tdArr ] }}</span>'
															+'<input type="text" class="midAWtwo_row_childAsh">'
														+'</div>'
													+'</td>'
												+'{{/each}}'
											+'{{/if}}'
										+'</tr>'
									+'{{/each}}'
								+'</tbody></table>'
							+'{{/if}}'
						+'{{else}}'
							+'{{if date["title"]}}'
								+'<div class="midTWord_tab clearfix">'
									+'<div class="midTWord_tab_sub clearfix">'
										+'{{each date["title"] as value i}}'
											+'<div class="midTWord_tab_child {{if i==current }} midTWord_tab_childAct {{/if}}" id="{{i}}">'
												+'{{value}}'
											+'</div>'
										+'{{/each}}'
									+'</div>'
								+'</div>'
							+'{{/if}}'
							+'<div class="midTWord_outer clearfix">'
								+'{{each date["content"] as value i}}'
									+'{{each value["td"] as tdArr a}}'
										+'<div name="{{if date["index"]}}{{current+date["index"][a]}}{{else}}{{current+a}}{{/if}}"  class="midTWord_child clearfix odds_box {{if itemID=="GYJH" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB"}} midTWord_child_special {{/if}}">'								
											+'{{if itemID !="GYJH" && itemID!="zspTBH" && itemID!="LHPTZX" && itemID!="LHZXDS" && itemID!="LHZMZHDXDS" && itemID!="LHTBHBBSB" && itemID!="LHTBHBSB" && itemID!="LHTBHSB"  && itemID!="LHQSB" && itemID!="WZHS"}}'
												+'<div class="midTWord_child_badges_box">'
													+'<div class="left {{midTWord_child_badges(tdArr,itemID)}}  {{if hasBg}} {{getBgColor( itemID,tdArr )}} {{/if}} {{if itemID=="FCSZHS"}} midTWord_child_badges_SZHS {{/if}}">'
														+'{{tdArr}}'
													+'</div>'
												+'</div>'
											+'{{else if itemID=="GYJH" || itemID=="zspTBH" || itemID=="LHPTZX" || itemID=="LHZXDS" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB" || itemID=="WZHS"}}'
												+'<div class="left midTWord_child_badges_special {{if itemID=="GYJH" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB"}} midTWord_child_badges_special_long {{/if}}  {{if itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHQSB"}} {{current+date["index"][a]}} {{else if itemID=="LHTBHSB"}} {{itemID+date["index"][a]}} {{/if}}">'
													+'{{if itemID=="GYJH"}}'
														+'<span class="GYJH_span">{{# tdArr.split(",").join("</span><span class=\'GYJH_span\'>")}}</span>'
													+'{{else}}'
														+'{{tdArr}}'
													+'{{/if}}'
												+'</div>'
											+'{{/if}}'
											+'<div class="right showNum_text_box clearfix odds_box_sub" name="{{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}}">'
												+'<div class="left midTWord_child_showNum odds_pl" name="{{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}}"> {{if date["index"] }}  {{ odds["newOdds"][ current+date["index"][a] ] }} {{else}} {{ odds["newOdds"][ current+a ] }} {{/if}}</div>'
												+'<input type="text" class="midTWord_child_black">'
											+'</div>'
										+'</div>'
									+'{{/each}}'
								+'{{/each}}'
							+'</div>'
						+'{{/if}}'
					+'</div>'
				+'</div>',
		
			Frame_01_k8_zsp:''
				+'<div class="mid_box {{itemID}}_box k8_zsp_box frame_01 module02 clearfix" itemid={{itemID}}>'
					+'{{each date["content"] as value i}}'
						+'{{each value["td"] as tdArr a}}'
							+'<div class="left {{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}} ">'
								+'<div class="k8_zsp_box_text">{{tdArr}} </div>'
								+'<span class="k8_midTWord_child_showNum " name="{{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}}"> {{if date["index"] }}  {{ odds["newOdds"][ current+date["index"][a] ] }} {{else}} {{ odds["newOdds"][ current+a ] }} {{/if}}</span>'				
							+'</div>'
						+'{{/each}}'
					+'{{/each}}'
				+'</div>',
		
			Frame_10_k8_zsp:''
				+'<div class="mid_box {{itemID}}_box k8_zsp_box frame_10 module02 clearfix" itemid={{itemID}}>'
					+'{{each date["content"] as value i}}'
						+'<div class="left k8_frame10_box_sub {{itemID}}_box_sub odds_box {{current+i}}" name="{{current+i}}">'
							+'<div class=" k8_frame10_text ">{{value["name"]}}</div>'
							+'<div class=" k8_frame10_number">[{{value["number"]}}]</div>'
							+'<div class=" k8_frame10_odds odds_pl" name={{current+i}} >{{ odds["newOdds"][current+i] }}</div>'
						+'</div>'
					+'{{/each}}'
				+'</div>',
		
		
			
			frame_01_title_click:''
				+'{{each date["content"] as value i}}'
					+'{{each value["td"] as tdArr a}}'
						+'<div name="{{if date["index"]}}{{current+date["index"][a]}}{{else}}{{current+a}}{{/if}}" class="midTWord_child clearfix odds_box {{if itemID=="GYJH" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB"}} midTWord_child_special {{/if}}">'								
							+'{{if itemID !="GYJH" && itemID!="zspTBH" && itemID!="LHPTZX" && itemID!="LHZXDS" && itemID!="LHZMZHDXDS" && itemID!="LHTBHBBSB" && itemID!="LHTBHBSB" && itemID!="LHTBHSB"  && itemID!="LHQSB" && itemID!="WZHS"}}'
								+'<div class="midTWord_child_badges_box">'
									+'<div class="left {{midTWord_child_badges(tdArr,itemID)}}  {{if hasBg}} {{getBgColor( itemID,tdArr )}} {{/if}} {{if itemID=="FCSZHS"}} midTWord_child_badges_SZHS {{/if}}">'
										+'{{tdArr}}'
									+'</div>'
								+'</div>'
							+'{{else if itemID=="GYJH" || itemID=="zspTBH" || itemID=="LHPTZX" || itemID=="LHZXDS" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB" || itemID=="WZHS"}}'
								+'<div class="left midTWord_child_badges_special {{if itemID=="GYJH" || itemID=="LHZMZHDXDS" || itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHTBHSB" || itemID=="LHQSB"}} midTWord_child_badges_special_long {{/if}}  {{if itemID=="LHTBHBBSB" || itemID=="LHTBHBSB" || itemID=="LHQSB"}} {{current+date["index"][a]}} {{else if itemID=="LHTBHSB"}} {{itemID+date["index"][a]}} {{/if}}">'
									+'{{if itemID=="GYJH"}}'
										+'<span class="GYJH_span">{{# tdArr.split(",").join("</span><span class=\'GYJH_span\'>")}}</span>'
									+'{{else}}'
										+'{{tdArr}}'
									+'{{/if}}'
								+'</div>'
							+'{{/if}}'
							+'<div class="right showNum_text_box clearfix odds_box_sub" name="{{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}}">'
								+'<div class="left midTWord_child_showNum odds_pl" name="{{if date["index"]}} {{ current+date["index"][a] }}  {{else}} {{ current+a }} {{/if}}"> {{if date["index"] }}  {{ odds["newOdds"][ current+date["index"][a] ] }} {{else}} {{ odds["newOdds"][ current+a ] }} {{/if}}</div>'
								+'<input type="text" class="midTWord_child_black">'
							+'</div>'
						+'</div>'
					+'{{/each}}'
				+'{{/each}}',
		
			frame_02_title_click:''
				+'{{each date["content"] as value i}}'
				+'<div class="clearfix frame_02_box" name={{value["TrIDName"]}}>'
					+'<div class="left frame_02_box_text" name={{value["idName"]}}>'
						+'{{if date["current_text"]}} {{date["current_text"][i]}}  {{else}} {{value["lable"]}}  {{/if}}'
					+'</div>'
					+'<div class="left clearfix frame_02_number_box">'
						+'{{each value["td"] as val a}}'
							+'<div class="left frame_02_number midTWord_child_badges " i={{val}}>{{val}}</div>'
						+'{{/each}}'
					+'</div>'
				+'</div>'
				+'{{/each}}',
		
			frame_03_title_click:''
				+'{{each date["content"] as value i}}'
					+'<div class="frame_03_box clearfix" {{if value["lable"]}}name={{value["TrIDName"]}} {{/if}}>'
						+'{{if value["lable"]}}'
							+'<div class="left frame_03_text" name={{value["TrIDName"]}}>{{value["lable"]}}</div>'
						+'{{/if}}'
						+'<div class="left frame_03_number_box">'
							+'{{each value["td"] as tdArr a }}'
								+'<div class="left frame_03_number midTWord_child_badges">'
									+'{{tdArr}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
					+'</div>'
				+'{{/each}}',
		
			frame_05_title_click:''
				
				+'{{if itemID!="LHLM" && itemID!="KBBJKLXH"}}'
					+'{{each date["content"] as value i}}'
						+'<div class="clearfix frame_05_box" {{if value["TrIDName"]}} name={{ value["TrIDName"] }} {{/if}}>'
							+'{{if value["lable"]}}'
								+'<div class="left frame_05_box_text" name={{value["TrIDName"]}}>{{value["lable"]}}</div>'
							+'{{/if}}'
							+'<div class="left frame_05_number_box">'
								+'{{each value["td"] as val }}'
									+'{{if val}}'
										+'<div class="left clearfix {{if itemID=="LHZXBZ" }}frame_05_number_box_sub {{/if}}">'
											+'{{if itemID=="LHZXBZ" }} <div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div> {{/if}}'
											+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}  {{if itemID=="PKQE" || itemID=="PKQS" || itemID=="PKQSI"}} bjpks_car_{{val}} {{/if}}">{{val}}</div>'
										+'</div>'
									+'{{/if}}'
								+'{{/each}}'
							+'</div>'
							
							+'{{if itemID=="LHZXBZ" }}'
								+'<div class="left combination {{itemID}}_combination frame_05_combination">'
									+'<div class="combination_header">'
										+'注单号码<div class="combination_number"></div>'
									+'</div>'
									+'<div class="combination_content">'
										+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
										+'<div class="combination_content_sub"></div>'
									+'</div>'
								+'</div>'
							+'{{/if}}'
						+'</div>'
					+'{{/each}}'
				+'{{else if itemID=="LHLM"}}'
					+'<div class="clearfix frame_05_box">'
						+'<div class="frame_05_box_title">'
							+'<label><input type="radio" value="zx" checked name="{{itemID}}_radio">自选</label>'
							+'<label><input type="radio" value="dt" name="{{itemID}}_radio">胆拖</label>'
						+'</div>'
						+'<div class="frame_05_number_box_parent">'
							+'<div class="zx">'
									+'<div class="left frame_05_number_box">'
										+'{{each date["content"]["tr1"]["td"] as val }}'
											
												+'<div class="left clearfix frame_05_number_box_sub">'
													+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
													+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
												+'</div>'
											
										+'{{/each}}'
									+'</div>'
								
									+'<div class="left combination {{itemID}}_combination frame_05_combination">'
										+'<div class="combination_header">'
											+'注单号码<div class="combination_number"></div>'
										+'</div>'
										+'<div class="combination_content">'
											+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
											+'<div class="combination_content_sub"></div>'
										+'</div>'
									+'</div>'

							+'</div>'
							+'<div class="dt" style="display:none;">'
								+'<div class="left clearfix" style="width:530px;">'
									+'<div>胆码</div>'
									+'<div class="left dm frame_05_number_box">'
										
										+'{{each date["content"]["tr1"]["td"] as val }}'
											
												+'<div class="left clearfix frame_05_number_box_sub">'
													+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
													+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
												+'</div>'
											
										+'{{/each}}'
									+'</div>'
									+'<div class="left tm frame_05_number_box">'
										+'<div>拖码</div>'
										+'{{each date["content"]["tr1"]["td"] as val }}'
											
												+'<div class="left clearfix frame_05_number_box_sub">'
													+'<div name="{{itemID}}_checkbox" class="left {{itemID}}_checkbox" value={{val}}></div>'
													+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}}">{{val}}</div>'
												+'</div>'
											
										+'{{/each}}'
									+'</div>'
								+'</div>'
									+'<div class="left combination {{itemID}}_combination_dt frame_05_combination">'
										+'<div class="combination_header">'
											+'注单号码<div class="combination_number"></div>'
										+'</div>'
										+'<div class="combination_content">'
											+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
											+'<div class="combination_content_sub"></div>'
										+'</div>'
									+'</div>'
							+'</div>'
						+'</div>'
					+'</div>'
				+'{{else if itemID=="KBBJKLXH"}}'		
						+'<div class="clearfix left frame_05_box">'
							+'{{each date["content"] as value i}}'
								+'<div class="left frame_05_number_box">'
									+'{{each value["td"] as val }}'
										+'{{if val}}'
											+'<div class="left clearfix ">'
												
												+'<div class="left frame_05_number midTWord_child_badges {{getBgColor(itemID,val)}} ">{{val}}</div>'
											+'</div>'
										+'{{/if}}'
									+'{{/each}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
						+'<div class="left combination {{itemID}}_combination frame_05_combination">'
							+'<div class="combination_header">'
								+'注单号码<div class="combination_number"></div>'
							+'</div>'
							+'<div class="combination_content">'
								+'<div>共有<span class="combination_num">0</span>种组合{{if date["maxNum"]}}(最多{{date["maxNum"][current]}} 种组合){{/if}} <span class="combination_result_btn"></span></div>'
								+'<div class="combination_content_sub"></div>'
							+'</div>'
						+'</div>'
				+'{{/if}}',
		
			frame_07_title_click:''
				+'{{each date["content"] as value i}}'
					+'<div class="clearfix">'
						+'{{each value["lotteryNo"] as val a}}'
							+'<div class="left midTWord_child clearfix">'
								+'<div class="midTWord_child_badges_box"><div class="left midTWord_child_badges frame_07_text" name={{a}}> {{val}} </div></div>'
								+'<div class="left clearfix frame_07_number_box">{{#getFrame08Number(itemID,a,odds) }}</div>'
							+'</div>'
						+'{{/each}}'
					+'</div>'
				+'{{/each}}',
		
			frame_08_title_click:''
				+'{{if itemID=="LHLX"}}'
					+'<div class="frame_08_title clearfix">'
						+'<div class="right">'
							+'<span>快速选择:</span>'
							+'{{each date["quick_choose"] as value i}}'
								+'<span class="quick_choose_btn" data-value="{{value.join(",")}}">{{i}}</span>'
							+'{{/each}}'
						+'</div>'
					+'</div>'
				+'{{/if}}'
				+'{{each date["content"] as value i}}'
					+'<div class="clearfix">'
						+'{{each value["lotteryNo"] as val a}}'
						+'{{if val}}'
							+'<div class="left midTWord_child clearfix">'
								+'<div class="midTWord_child_badges_box"><div class="frame_08_sx_name "> {{val}} </div></div>'
								+'{{if value["lotteryNumber"]}}'
									+'<div class="left clearfix frame_08_number_box">{{ #getFrame08Bg(itemID,value["lotteryNumber"][a])  }}</div>'
								+'{{else}}'
									+'<div class="left clearfix frame_08_number_box">{{#getFrame08Number(itemID,a,odds) }}</div>'
								+'{{/if}}'
								+'<div class="right frame_08_odds_box"><label class="clearfix"><div class="left odds_pl">{{odds["newOdds"][current+a]}}</div><input type="checkbox" data-i={{a}} name={{itemID+"checkbox"}} value={{current+a}} class="left"> </label></div>'
							+'</div>'
						+'{{/if}}'
						+'{{/each}}'
					+'</div>'
				+'{{/each}}',
		
			frame_10_title_click:''
				+'{{if !date["isSpecial"]}}'
					
					+'{{each date["content"] as value i}}'
						+'<div class="midTWord_outer_sub midTWord_child clearfix odds_box" name={{ current+date["index"][i] }}>'
							+'<div class="midTWord_child_badges_box"><div class=" {{　midTWord_child_badges(value,itemID) }}  {{ if itemID=="LHZMT" || itemID=="GXZM" }} {{ getBgColor( itemID,value ) }} {{/if}}">{{value}}</div></div>'
							+'<div class="left showNum_text_box clearfix odds_box_sub {{if itemID=="SZHS" || getBgColor(itemID,value)=="lhc_text" || getBgColor(itemID,value)=="gxklsf_text"}} showNum_text_box_SZHS {{/if}}" name={{ current+date["index"][i] }}>'
								+'<div class="midTWord_child_showNum odds_pl" name={{ current+date["index"][i] }}>{{ odds["newOdds"][ current+date["index"][i] ] }}</div>'
								+'<input type="text" class="midTWord_child_black">'
							+'</div>'
						+'</div>'
					+'{{/each}}'
					
				+'{{else if date["isSpecial"]}}'
					+'{{if date["sjwx"] || date["zfb"]}}'
						
						+'{{each date["content"] as value i}}'
							+'<div class="left midTWord_outer_sub midTWord_child_sjwx_zfb clearfix odds_box" name="{{current+i}}">'
								+'<div class="left midTWord_child_badges  sjwx_zfb_name">{{value["name"]}}</div>'
								+'<div class="left sjwx_zfb_number">[{{value["number"]}}]</div>'
								+'<div class="right sjwx_zfb_odds odds_pl" name={{current+i}} title="点击赔率进行下注">{{ odds["newOdds"][current+i] }}</div>'
							+'</div>'
						+'{{/each}}'
							
					+'{{/if}}'
				+'{{/if}}',
		
			mid_Sure:''
				+'<span class="midSure_show">总额度:'
					+'<strong class="midSure_show_money">0</strong>'
				+'</span>'
				+'<div class="midSure_Btn midSure_sureBtn">确定</div>'
				+'<div class="midSure_Btn midSure_refreshBtn">重置</div>',
			
			EZZX_click:''
				+'{{each data as val i}}'
					+'<div class="left clearfix midTWord_child " playobj={{val["play_lx"]}}{{val[0]}}_{{val[1]}}>'
						+'<div class="left clearfix">'
							+'<div class="left midTWord_child_badges">{{val[0]}}</div>'
							+'<div class="left midTWord_child_badges">{{val[1]}}</div>'
						+'</div>'
						+'<div class="right"><span class="odds_pl frame_02_odds"> {{val["odds"]}} </span></div>'
					+'</div>'
				+'{{/each}}',
			
			frame_02_DW:''
				+'{{each data as val i}}'
					+'<div class="left clearfix midTWord_child " playobj={{val["play_lx"]}}{{val[0]}}_{{val[1]}}{{if val[2]}}_{{val[2]}} {{/if}}>'
						+'<div class="left clearfix">'
							+'<div class="left midTWord_child_badges">{{val[0]}}</div>'
							+'<div class="left midTWord_child_badges">{{val[1]}}</div>'
							+'{{if val["2"]}} <div class="left midTWord_child_badges">{{val[2]}}</div> {{/if}}'
						+'</div>'
						+'<div class="right"><span class="odds_pl frame_02_odds"> {{val["odds"]}} </span></div>'
					+'</div>'
				+'{{/each}}',
			
			frame_02_frame_02_number:''
				+'{{each data as val i}}'
					+'<div class="left clearfix midTWord_child " playobj={{val["play_lx"]}}{{val[0]}}_{{val[1]}}{{if val[2]}}_{{val[2]}} {{/if}}>'
						+'<div class="left clearfix">'
							+'<div class="left midTWord_child_badges">{{val[0]}}</div>'
							+'<div class="left midTWord_child_badges">{{val[1]}}</div>'
							+'{{if val["2"]}} <div class="left midTWord_child_badges">{{val[2]}}</div> {{/if}}'
						+'</div>'
						+'<div class="right"><span class="odds_pl frame_02_odds"> {{val["odds"]}} </span></div>'
					+'</div>'
				+'{{/each}}',
			
			article_middle_nowList_content:''
				
					+'<div class="article_middle_nowList_content_sub01">'
						+'<div class="nowList_content_sub01_item"></div>'
						+'<div class="nowList_content_sub01_quickMoney">'
							+'<div class="quickMoney_btn"><span>25</span><span>50</span><span>100</span><span>200</span><span>250</span><span>300</span><span>500</span><span>1000</span></div>'
							+'<div class="clearfix quickMoney_text"><span class="left">每注</span><div class="quickMoneyInput_box left"><input type="text" class="quickMoneyInput"></div><span class="clearMoney left">清除</span></div>'
						+'</div>'
						+'<div class="nowList_content_sub01_btn">'
							+'<input type="button" value="确定" class="submitOdds">'
							+'<input type="button" value="取消" class="deleteOdds">'
						+'</div>'
						+'<div class="user_choose">'
							+'<span class="user_choose_btn_true"></span>显示确认投注'
						+'</div>'
					+'</div>',

			article_middle_nowList_content_quick_bet:''
				+'<div class="article_middle_nowList_content_sub01 article_middle_nowList_content_quick_bet">'
					+'<div class="nowList_content_sub01_item"></div>'
					+'<div class="nowList_content_sub01_quickMoney">'
						+'<div class="quickMoney_btn"><span>25</span><span>50</span><span>100</span><span>200</span><span>250</span><span>300</span><span>500</span><span>1000</span></div>'
						+'<div class="clearfix quickMoney_text"><span class="left">每注</span><div class="quickMoneyInput_box left"><input type="text" class="quickMoneyInput"></div><span class="clearMoney left">清除</span></div>'
						+'<div style="font-size:14px;color:#b4b4b4;">总共金额为:<span class="tolMoney">0</span></div>'
					+'</div>'
					+'<div class="nowList_content_sub01_btn">'
						+'<input type="button" value="确定" class="quick_bet_submitOdds">'
						+'<input type="button" value="取消" class="quick_bet_deleteOdds">'
					+'</div>'
					+'<div class="user_choose">'
						+'<span class="user_choose_btn_true"></span>显示确认投注'
					+'</div>'
				+'</div>',
		
			article_middle_beenList_content:''
				+'<div class="article_middle_beenList_content_sub">'
					+'{{each result as value}}'
						+'<div class="beenList_item">'
							+'<div class="beenList_item_name">{{value["game_name"]}}-[{{value["periods"]}}]</div>'
							+'<div class="beenList_item_descrite">{{value["play_name"]}}</div>'
							+'<div class="beenList_item_pl">{{#value["obj_name"]}}@{{value["bet_pl"]}}</div>'
							+'<div class="beenList_item_money">[{{value["bet_money"]}}]</div>'
							+'<div class="beenList_item_id">{{value["id"]}}</div>'
							+'<div class="beenList_item_time">{{value["bet_time"]}}</div>'
						+'</div>'
					+'{{/each}}'
				+'</div>',
		
			midResult:''
				+'<div class="midResult_tab clearfix">'
					+'<div class="left midResult_tab_left clearfix">'
						+'{{each luzi["XYobj"]["turnon"] as value i }}'
							+'<div class="midResult_tab_leftChild {{if value["0"]==luzi["luType"] }} active{{/if}}" lutype={{value["0"]}}>{{ value["1"] }}</div>'
						+'{{/each}}'
					+'</div>'
					+'<div class="right midResult_tab_right clearfix">'
						/*
						+'<div class="left midResult_tab_rightAu">'
							+'<label><input type="radio" name="open">关</label>'
							+'<label><input type="radio" checked="true" name="open">开</label>'
						+'</div>' */
						+'<div class="left midResult_tab_rightBtn left">刷新</div>'
						+'<select name="" id="" class="left midResult_tab_rightSelect">'
							+'<option value=30 selected>近30期</option>'
							+'<option value=50>近50期</option>'
							+'<option value=100>近100期</option>'
							+'<option value=0>今日</option>'
						+'</select>'
						+'<select id="showRows" style="display:none">'
							+'<option value=3 >3路珠</option>'
							+'<option value=4 >4路珠</option>'
							+'<option value=5 >5路珠</option>'
							+'<option value=6 selected>6路珠</option>'
							+'<option value=7 >7路珠</option>'
						+'</select>'
					+'</div>'
				+'</div>'
				+'<div class="midResult_tag clearfix">'
					
				+'</div>'
				+'<div class="midResult_content clearfix">'
				
				+'</div>'
				
				+'<div class="midResult_content_scrollX_box">'
					//+'<div class="midResult_content_scrollX_box_sub"><div class="midResult_content_scrollX"></div></div>'
				+'</div>',
			
			midResult_content_right_sub_luType_1:''
				+'{{each luzi["num"] as value}}'
					+'<div class="left lz_line_box">'
						+'{{each value as va i}}'
							+'<div class="color{{va["2"]}} {{if va["1"]}} div_number {{/if}} " title={{va["0"]}} >{{va["1"]}}</div>'
						+'{{/each}}'
					+'</div>'
				+'{{/each}}',
		
			midResult_content_right_sub_luType_4:''
				+'<table cellpadding=0 cellspacing=0 class="table_luType_4"><tbody>'
					+'{{each luzi["num"] as value}}'
						+'<tr>'
							+'<td>{{value["0"]}}</td>'
							+'<td>{{value["1"]}}</td>'
							+'<td>{{value["2"]}}</td>'
						+'</tr>'
					+'{{/each}}'
				+'</tbody></table>',
				
		
			'midResult_tag':''
				+'<div class="right">'
					+'{{each luzi["XYobj"]["X"] as value i }}'
						+'<div class="left midResult_tag_child {{if i==luzi["XYobj"]["currX"] }} active{{/if}}" value={{i}}>{{value}}</div>'
					+'{{/each}}'
				+'</div>',
		
			'midResult_content_luType_1':''
				+'<ul class="left midResult_content_left">'
					+'{{each luzi["XYobj"]["Y"] as value i }}'
						+'<li y={{i}} {{if i==luzi["XYobj"]["luziName"]}} class="midResult_content_leftChildAct" {{/if}}>{{value}}</li>'
					+'{{/each}}'
				+'</ul>'
				+'<div class="left midResult_content_sub default-skin">'
					
						+'<div class="midResult_content_right_sub clearfix">'
							
								+'{{each luzi["num"] as value}}'
									+'<div class="left lz_line_box">'
										+'{{each value as va i}}'
											+'<div class="color{{va["2"]}} {{if va["1"]}} div_number {{/if}}" title={{va["0"]}} >{{va["1"]}}</div>'
										+'{{/each}}'
									+'</div>'
								+'{{/each}}'
							
						+'</div>'
					
				+'</div>',
		
			
			'midResult_content_luType_4':''
				+'<ul class="left midResult_content_left">'
					+'{{each luzi["XYobj"]["Y"] as value i }}'
						+'<li y={{i}} {{if i==luzi["XYobj"]["luziName"]}} class="midResult_content_leftChildAct" {{/if}}>{{value}}</li>'
					+'{{/each}}'
				+'</ul>'
				+'<div class="left midResult_content_sub default-skin">'
						+'<div class="midResult_content_right_sub">'				
							+'<table cellpadding=0 cellspacing=0 class="table_luType_4"><tbody>'
								+'{{each luzi["num"] as value}}'
									+'<tr>'
										+'<td>{{value["0"]}}</td>'
										+'<td>{{value["1"]}}</td>'
										+'<td>{{value["2"]}}</td>'
									+'</tr>'
								+'{{/each}}'
							+'</tbody></table>'
						+'</div>'
					
				+'</div>',
			
			midResult_tag_lutype_3:''
				+'<div class="right">'
					+'{{each luzi["XYobj"]["X"] as value i }}'
						+'<div class="left midResult_tag_child_lutype3 {{if i==luzi["XYobj"]["currX"] }} active{{/if}}" value={{i}}> <label > <input type="checkbox" {{if i==luzi["XYobj"]["currX"]}} checked  {{/if}} > {{value}}  </label> </div>'
					+'{{/each}}'
				+'</div>',
		
			midResult_content_luType_3:''
				+'<ul class="left midResult_content_left midResult_content_left_lutype3">'
					+'{{each luzi["XYobj"]["Y"] as value i }}'
						+'<li y={{i}} {{if i==luzi["XYobj"]["luziName"]}} class="midResult_content_leftChildAct" {{/if}}>{{value}}</li>'
					+'{{/each}}'
				+'</ul>'
				+'<div class="left midResult_content_sub default-skin">'
					
						+'<div class="midResult_content_right_sub">'
			
							+'{{each luzi["num"] as value}}'
								+'<div class="left lz_line_box">'
									+'{{each value as va i}}'
										+'<div class="div_lutype3 {{if va["0"]}} div_number {{/if}} color{{va["2"]}} " title={{va["1"]}} >{{va["0"]}} {{if va["2"]>1 && va["2"]==va["3"] }} <sup>{{va["2"]}}</sup> {{/if}}</div>'
									+'{{/each}}'
								+'</div>'
							+'{{/each}}'
							
						+'</div>'
					
				+'</div>',
		
			midResult_content_luType_5:''
				+'<ul class="left midResult_content_left midResult_content_left_lutype5">'
					
				+'</ul>'
				+'<div class="left default-skin midResult_content_sub ">'
					
						+'<div class="midResult_content_right_sub midResult_content_right_lutype5">'
							
							+'<table  class="resultBox" width=100% cellpadding=0 cellspacing=0>'
								+'<thead>'
									+'<tr>'
										+'{{each result["row"] as cos j}}'
											+'<th>{{cos}}</th>'
										+'{{/each}}'
									+'</tr>'
								+'</thead>'
								+'{{each result["data"] as row i}}'
									+'<tr {{if (i+1)%2==0}} style=" "{{/if}}>'
										+'{{if gameLx!=10 && gameLx!=52 && gameLx!=62 && gameLx!=63 }}'
											+'{{each row as cos j}}'
												+'{{if j!=1}}'
													+'<td width="{{if row[1].length<=5}}{{100/row.length-1}}%{{/if}}">{{cos}}</td>'
												+'{{else}}'
													+'<td width="{{if cos.length<=10&&cos.length>=5}}{{cos.length*45}}px{{else if cos.length<5}}{{100/row.length+row.length*1}}%{{else}}{{cos.length*15}}px{{/if}}" >'
														+'{{each cos as ball k}}'
															+'{{if (gameLx==22&&k==4)||(gameLx==10&&k==6)}}'
																+'&nbsp;<b>+</b>&nbsp;'
															+'{{/if}}'
															+'{{if gameLx==10}}'
																+'<span class="{{ball[1]}}">{{ball[0]}}</span><em >{{ball[2]}}</em>'
															+'{{else}}'
																+'<span class="{{ball[1]}}">{{ball[0]}}</span>'
															+'{{/if}}'
														+'{{/each}}'
													+'</td>'
												+'{{/if}}'
											+'{{/each}}'
										+'{{else}}'
											+'{{each row as cos j}}'
												+'{{if j!=2}}'
													+'<td width="{{if row[1].length<=5}}{{100/row.length-1}}%{{/if}}">{{cos}}</td>'
												+'{{else}}'
													+'<td width="{{if cos.length<=10&&cos.length>=5}}{{cos.length*55}}px{{else if cos.length<5}}{{100/row.length+row.length*1}}%{{else}}{{cos.length*15}}px{{/if}}" >'
														+'{{each cos as ball k}}'
															+'{{if (gameLx==22&&k==4)||(gameLx==10&&k==6)}}'
																+'&nbsp;<b>+</b>&nbsp;'
															+'{{/if}}'
															+'{{if gameLx==10}}'
																+'<span class="{{ball[1]}}">{{ball[0]}}</span><em >{{ball[2]}}</em>'
															+'{{else}}'
																+'<span class="{{ball[1]}}">{{ball[0]}}</span>'
															+'{{/if}}'
														+'{{/each}}'
													+'</td>'
												+'{{/if}}'
											+'{{/each}}'
										+'{{/if}}'
									+'</tr>'
								+'{{/each}}'
							+'</table>'
							
						+'</div>'
					
				+'</div>',
		
			midResult_div_number:''
				+'<div class="midResult_div_number_alertBox">'
					+'<div class="midResult_div_number_bgColor"></div>'
					+'<div class="midResult_div_number">'
						+'<div class="midResult_div_number_title">查看结果<span class="close_midResult_div_number"></span></div>'
						+'<div class="midResult_div_number_content">'
							+'{{each saiguo as sg i}}'
								+'<div class="clearfix">'
								+'{{if i=="开奖结果"}}'
									+'<em class="left">结果：</em>'
									+'<p class="num_box left">'
										+'{{each sg as num j}}'
											+'{{if j==10}}'
												+'<br/>'
											+'{{/if}}'
											+'<span class="{{num[1]}}">{{num[0]}}</span>'
										+'{{/each}}'
									+'</p>'
								+'{{else}}'
									+'<em >{{i}}：</em>'
									+'{{if i=="期号"}}'
										+'<b >{{sg}}</b>'
									+'{{else}}'
										+'<em >{{sg}}</em>'
									+'{{/if}}'
								+'{{/if}}'
								+'</div>'
							+'{{/each}}'
						+'</div>'
					+'</div>'
		        +'</div>',
		
			gameRules:'' //游戏规则弹出框内容
				+'<div class="gameRules">'
					+'<div class="gameRulesTitle">游戏规则<div class="closeGameRules"></div></div>'
					+'<div class="gameRulesContent default-skin">'
						+'<table cellspacing=0 cellpadding=0>'
							+'<tbody>'
								+'<tr>'
									+'<td class="https"><a href="{{refer_url}}" target="_blank">进入官网</a></td>'
									+'<td style="color: #d00; font-weight: bold;">'
										+'{{bet_info}}'
									+'</td>'
								+'</tr>'
								+'{{each panType["ruleName"] as content i}}'
									+'<tr><td colspan="2">'
										+'<strong>{{ content }}</strong>:{{#panType["ruleBox"][i]}}'
									+'</td></tr>'
								+'{{/each }}'
							+'</tbody>'
						+'</table>'
					+'</div>'
				+'</div>',
		
			article_middle_nowList_content_sub02:''
				
					//+'<div class="nowList_confirm_header"> 确认投注<div class="right close_nowList_confirm"></div> </div>'
					+'<div class="" style="padding-top:10px;">'
						+'<div><span>当前投注:</span>{{ game_lx }}</div>'
						+'<div><span>期数:</span>{{ periods }}</div>'
						+'<div><span class="num">{{num}} 注</span>共{{ tolMoney }}元</div>'
						/*
						+'<div class="nowList_confirm_btn">'
							+'<input type="button" value="确定" class="submitOdds_ok">'
						+'</div>'*/
					+'</div>',
				
		
			alertBox:''
				+'<div class="alertBox">'
					+'<div class="alertBox_header">提示信息 <div class="right close_alertBox close_alertBox_bg"></div></div>'
					+'<div class="alertBox_content">{{#str}}</div>'
					+'<div class="alertBox_btn">'
						+'<input type="button" value="确定" class="alertBox_btn_ok  close_alertBox {{clas}}">'
					+'</div>'
				+'</div>',
		
			betingLoader:''
				+'<div class="betingLoader"><img src="images2/loadingBG.gif"><div>投注中...</div></div>',
		
			long_queue:''
				+'<div id="HeadTitle" class="lotteryBox01">'
					+'{{each DYTitle as title1 i}}'
					+'<span id="{{i}}">{{title1}}</span>'
					+'{{/each}}'
				+'</div>'
				+'<div id="lotteryContent">'
					+'<div id="titleContent" class="lotteryBox03">'
						+'{{each DETitle as title2 i}}'
							+'<span id="{{i}}">{{title2}}</span>'
						+'{{/each}}'
						+'<a id="moreCL" class="allCL">更多长龙</a>'
					+'</div>'
					+'<div class="lawContent clearfix">'
						+'<div class="lawContent_sub left">'
							+'{{each result as content i}}'
								+'{{if i!="status"}}'
								+'<div class="clearfix">'
									+'<a class="left" name="{{content["play"]}}" href="javascript: void(0)">{{ content["play_name"] }}[{{ content["wave"] }}]</a>'
									+'<span class="right">{{ content["connecting"] }}期</span>'
								+'</div>'
								+'{{/if}}'
							+'{{/each}}'
						+'</div>'
						
					+'</div>'
				+'</div>',
		
			lotteryContent:''
				+'<div id="titleContent" class="lotteryBox03">'
					+'{{each DETitle as title2 i}}'
						+'<span id="{{i}}">{{title2}}</span>'
					+'{{/each}}'
					+'<a id="moreCL" class="allCL">更多长龙</a>'
				+'</div>'
				+'<div class="lawContent clearfix">'
					+'<div class="lawContent_sub left">'
						+'{{each result as content i}}'
							+'{{if i!="status"}}'
							+'<div class="clearfix">'
								+'<a class="left" name="{{content["play"]}}" href="javascript: void(0)">{{ content["play_name"] }}[{{ content["wave"] }}]</a>'
								+'<span class="right">{{ content["connecting"] }}期</span>'
							+'</div>'
							+'{{/if}}'
						+'{{/each}}'
					+'</div>'
					+'<div class="lawContent_sub_scroll_box right"></div>'
				+'</div>',
		
			lawContent:''
				+'<div class="lawContent_sub left">'
					+'{{each result as content i}}'
						+'{{if i!="status"}}'
						+'<div class="clearfix">'
							+'<a class="left" name="{{content["play"]}}" href="javascript: void(0)">{{ content["play_name"] }}[{{ content["wave"] }}]</a>'
							+'<span class="right">{{ content["connecting"] }}期</span>'
						+'</div>'
						+'{{/if}}'
					+'{{/each}}'
				+'</div>'
				+'<div class="lawContent_sub_scroll_box right"></div>',
		
			allChangLong:''
				+'<div class="contentCL_header">{{titleName}}<div class="closeContentCL"></div></div>'
				+'<div class="titleCL clearfix">'
					+'{{each titleCL as value i}}'
						+'<div data-i={{i}} class="left {{i}} {{if i==active}} active {{/if}}">{{value}}</div>'
					+'{{/each}}'
				+'</div>'
				+'<div class="contentLawCL clearfix"><img src="images2/loading.gif" style="width:50px;display:block;max-width:100%;margin:auto;"></div>',
			
			k3Contentdata:''
				+'<div class="k3_content_module01" {{if model!="k3_content_module01"}} style="display:none"  {{/if}}>'
					+'<div id="k3Content01" class="k3Box01 clearfix">'
						+'<div class="k3Box01_01 left">' 
							+'<div id="KSDSWdan" class="odds_13"><img src="images2/k3/dan.png"/><span class="odds_pl">{{newOdds["KSDSWdan"]}}</span></div>'
							+'<div id="KSDXWd" class="odds_01"><img src="images2/k3/d.png"/><span class="odds_pl">{{newOdds["KSDXWd"]}}</span></div>'                
						+'</div>'
						+'<div class="k3Box01_02 left" id="oddsNo">'
							+'<ul class="yz clearfix">'
								+'<li id="KSYYW1" class="odds_11 left border-right"><img src="images2/k3/01.png"> <span class="odds_pl">{{ newOdds["KSYYW1"] }} </span></li>'
								+'<li id="KSYYW2" class="odds_11 left border-right border-left"><img src="images2/k3/02.png"> <span class="odds_pl">{{ newOdds["KSYYW2"] }} </span></li>'
								+'<li id="KSYYW3" class="odds_11 left border-left"><img src="images2/k3/03.png"> <span class="odds_pl">{{ newOdds["KSYYW3"] }} </span></li>'
								+'<li class="bg_yz left"></li>'
								+'<li id="KSYYW4" class="odds_11 left border-right"><img src="images2/k3/04.png"> {{ newOdds["KSYYW4"] }}</li>'
								+'<li id="KSYYW5" class="odds_11 left border-right border-left"><img src="images2/k3/05.png">{{ newOdds["KSYYW5"] }}</li>'
								+'<li id="KSYYW6" class="odds_11 left border-left"><img src="images2/k3/06.png"> {{ newOdds["KSYYW6"] }}</li>'               
							+'</ul>'
							+'<div class="clearfix">'
								+'<div class="dz left">'						
									+'<ul class="clearfix">'
										+'<li id="KSDZ11" class="odds_10 left border_right border_bottom"><img src="images2/k3/11.png"/><span class="odds_pl">{{newOdds["KSDZ11"]}}</span></li>'
										+'<li id="KSDZ22" class="odds_10 left border_right border_bottom border_left"><img src="images2/k3/22.png"/><span class="odds_pl">{{newOdds["KSDZ22"]}}</span></li>'
										+'<li id="KSDZ33" class="odds_10 left              border_bottom border_left"><img src="images2/k3/33.png"/><span class="odds_pl">{{newOdds["KSDZ33"]}}</span></li>'
										+'<li id="KSDZ44" class="odds_10 left border_right border_top"><img src="images2/k3/44.png"/><span class="odds_pl">{{newOdds["KSDZ44"]}}</span></li>'
										+'<li id="KSDZ55" class="odds_10 left border_right border_left border_top"><img src="images2/k3/55.png"/><span class="odds_pl">{{newOdds["KSDZ55"]}}</span></li>'
										+'<li id="KSDZ66" class="odds_10 left border_left border_top"><img src="images2/k3/66.png"/><span class="odds_pl">{{newOdds["KSDZ66"]}}</span></li>'
									+'</ul>'
									+'<div class="text">短牌[对子]</div>'
								+'</div>'
								+'<div class="left weigu">'
									+'<ul class="clearfix">'
										+'<li id="KSBZ666" class="odds_02 left border_right border_bottom"><img src="images2/k3/111.png"><span class="odds_pl">{{newOdds["KSBZ111"]}}</span></li>'
										+'<li id="KSBZ555" class="odds_02 left border_right border_bottom border_left"><img src="images2/k3/222.png"><span class="odds_pl">{{newOdds["KSBZ222"]}}</span></li>'
										+'<li id="KSBZ444" class="odds_02 left border_bottom border_left"><img src="images2/k3/333.png"><span class="odds_pl">{{newOdds["KSBZ333"]}}</span></li>'
										+'<li id="KSBZ333" class="odds_02 left border_right border_top"><img src="images2/k3/444.png"><span class="odds_pl">{{newOdds["KSBZ444"]}}</span></li>'
										+'<li id="KSBZ222" class="odds_02 left border_right border_left border_top"><img src="images2/k3/555.png"><span class="odds_pl">{{newOdds["KSBZ555"]}}</span></li>'
										+'<li id="KSBZ111" class="odds_02 left border_left border_top"><img src="images2/k3/666.png"><span class="odds_pl">{{newOdds["KSBZ666"]}}</span></li>'
									+'</ul>'
									+'<div class="weigu_text"><div>围骰</div></div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="k3Box01_03 left">'  
							+'<div id="KSDSWs" class="odds_13"><img src="images2/k3/shuang.png"/><span>{{newOdds["KSDSWs"]}}</span></div>'
							+'<div id="KSDXWx" class="odds_01"><img src="images2/k3/x.png"><span>{{newOdds["KSDXWx"]}}</span></div>'
						+'</div>'
					+'</div>'
					
					+'<div id="k3Content02" class="k3Box02 clearfix">'
						+'<div class="test left"><span>和值</span></div>'
						+'<ul class="left clearfix">'
							+'<li id="KSZH17" class="odds_05 left no_border_left"><div>17</div><span>{{newOdds["KSZH17"]}}</span></li>'
							+'<li id="KSZH16" class="odds_04 left"><div>16</div><span>{{newOdds["KSZH16"]}}</span></li>'
							+'<li id="KSZH15" class="odds_04 left"><div>15</div><span>{{newOdds["KSZH15"]}}</span></li>'
							+'<li id="KSZH14" class="odds_04 left"><div>14</div><span>{{newOdds["KSZH14"]}}</span></li>'
							+'<li id="KSZH13" class="odds_04 left"><div>13</div><span>{{newOdds["KSZH13"]}}</span></li>'
							+'<li id="KSZH12" class="odds_04 left"><div>12</div><span>{{newOdds["KSZH12"]}}</span></li>'
							+'<li id="KSZH11" class="odds_04 left"><div>11</div><span>{{newOdds["KSZH11"]}}</span></li>'
							+'<li id="KSZH10" class="odds_04 left"><div>10</div><span>{{newOdds["KSZH10"]}}</span></li>'
							+'<li id="KSZH9" class="odds_04 left"><div>9</div><span>{{newOdds["KSZH9"]}}</span></li>'
							+'<li id="KSZH8" class="odds_04 left"><div>8</div><span>{{newOdds["KSZH8"]}}</span></li>'
							+'<li id="KSZH7" class="odds_04 left"><div>7</div><span>{{newOdds["KSZH7"]}}</span></li>'
							+'<li id="KSZH6" class="odds_04 left"><div>6</div><span>{{newOdds["KSZH6"]}}</span></li>'
							+'<li id="KSZH5" class="odds_04 left"><div>5</div><span>{{newOdds["KSZH5"]}}</span></li>'
							+'<li id="KSZH4" class="odds_06 left no_border_right"><div>4</div><span>{{newOdds["KSZH4"]}}</span></li>'
						+'</ul>'
					+'</div>'
					
					+'<div id="k3Content03" class="k3Box03 clearfix">'
						+'<div class="test left"><span>长牌</span></div>'
						+'<ul class="left clearfix">'
							+'<li id="KSEBT12" class="odds_08 no_border_left"><div></div><span class="odds_pl">{{newOdds["KSEBT12"]}}</span></li>'
							+'<li id="KSEBT13" class="odds_09"><div></div><span class="odds_pl">{{newOdds["KSEBT13"]}}</span></li>'
							+'<li id="KSEBT14" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT14"]}}</span></li>'
							+'<li id="KSEBT15" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT15"]}}</span></li>'
							+'<li id="KSEBT16" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT16"]}}</span></li>'
						   
							+'<li id="KSEBT23" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT23"]}}</span></li>'
							+'<li id="KSEBT24" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT24"]}}</span></li>'         
							+'<li id="KSEBT25" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT25"]}}</span></li>'
							+'<li id="KSEBT26" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT26"]}}</span></li>'
							
		
							+'<li id="KSEBT34" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT34"]}}</span></li>'
							+'<li id="KSEBT35" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT35"]}}</span></li>'
							+'<li id="KSEBT36" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT36"]}}</span></li>'
							
							+'<li id="KSEBT45" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT45"]}}</span></li>'
							+'<li id="KSEBT46" class="odds_07"><div></div><span class="odds_pl">{{newOdds["KSEBT46"]}}</span></li>'
							+'<li id="KSEBT56" class="odds_07 no_border_right"><div></div><span class="odds_pl">{{newOdds["KSEBT56"]}}</span></li>'     
						+'</ul>'
					+'</div>'
					
					+'<div class="k3Box04 clearfix">'
						+'<ul class="clearfix">'
							+'<li class="left odds_03" id="KSBZZbz"> 豹子<span class="odds_pl">{{newOdds["KSBZZbz"]}}</span> </li>'
							+'<li class="left odds_12" id="KSSZsz">顺子<span class="odds_pl"> {{newOdds["KSSZsz"]}} </span></li>'
							+'<li class="left odds_12" id="KSDZZdz">对子<span class="odds_pl"> {{newOdds["KSDZZdz"]}} </span></li>'
							+'<li class="left odds_12" id="KSZLzl">杂六<span class="odds_pl"> {{newOdds["KSZLzl"]}} </span></li>'	
						+'</ul>'
					+'</div>'
				+'</div>'
				+'<div class="k3_content_module02 k3" {{if model!="k3_content_module02"}} style="display:none"  {{/if}} >'
					+'<div class="mid_box">'
						+'<div class="mid-Title">一字</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'<div name="KSYY1" class="midTWord_child clearfix odds_box" id="KSYY1">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">1</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW1" id="KSYYW1"> {{ newOdds["KSYYW1"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSYYW2" name="KSYYW2">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">2</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW2" id="KSYYW2"> {{ newOdds["KSYYW2"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSYYW3" name="KSYYW3">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges ">3</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW3" id="KSYYW3"> {{ newOdds["KSYYW3"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSYYW4" name="KSYYW4">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges ">4</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW4" id="KSYYW4"> {{ newOdds["KSYYW4"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSYYW5" name="KSYYW5">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">5</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW5" id="KSYYW5"> {{ newOdds["KSYYW5"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSYYW6" name="KSYYW6">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">6</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSYYW6" id="KSYYW6"> {{ newOdds["KSYYW6"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
		
							+'</div>'
						+'</div>'
					+'</div>'
		
					+'<div class="mid_box">'
						+'<div class="mid-Title">双面</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'<div class="midTWord_child clearfix odds_box" id="KSDXWd" name="KSDXWd">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">大</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSDXWd" id="KSDXWd"> {{ newOdds["KSDXWd"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSDXWx" name="KSDXWx">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges ">小</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSDXWx" id="KSDXWx"> {{ newOdds["KSDXWx"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
								+'<div class="midTWord_child clearfix odds_box" id="KSDSWdan" name="KSDSWdan">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges">单</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSDSWdan" id="KSDSWdan"> {{ newOdds["KSDSWdan"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'			
								+'<div class="midTWord_child clearfix odds_box" id="KSDSWs" name="KSDSWs">'
									+'<div class="midTWord_child_badges_box">'
										+'<div class=" midTWord_child_badges  ">双</div>'
									+'</div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name="KSDSWs" id="KSDSWs"> {{ newOdds["KSDSWs"] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
		
							+'</div>'
						+'</div>'
					+'</div>'
		
					+'<div class="mid_box">'
						+'<div class="mid-Title">和值</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'{{each ZH as value}}'
									+'<div class="midTWord_child clearfix odds_box" id="KSZH{{value}}" name="KSZH{{value}}">'
										+'<div class="midTWord_child_badges_box">'
											+'<div class=" midTWord_child_badges  ">{{value}}</div>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSZH{{value}}" id="KSZH{{value}}"> {{ newOdds["KSZH"+value] }} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
					+'</div>'
		
					+'<div class="mid_box">'
						+'<div class="mid-Title">长牌</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'{{each EBT as value}}'
									+'<div class="midTWord_child clearfix odds_box  midTWord_child_special" id="KSEBT{{value.split(",").join("") }}" name="KSEBT{{value.split(",").join("") }}" >'
										+'<div class="left midTWord_child_badges_special  midTWord_child_badges_special_long ">'
											+'<span class="GYJH_span"> {{# value.split(",").join("</span><span class=\'GYJH_span\'>") }} </span>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSEBT{{value.split(",").join("") }}" id="KSEBT{{value.split(",").join("") }}"> {{ newOdds["KSEBT"+value.split(",").join("")] }} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
					+'</div>'
					
					+'<div class="mid_box">'
						+'<div class="mid-Title">对子</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'{{each DZ as value}}'
									+'<div class="midTWord_child clearfix odds_box  midTWord_child_special" id="KSDZ{{value.split(",").join("") }}" name="KSDZ{{value.split(",").join("") }}" >'
										+'<div class="left midTWord_child_badges_special  midTWord_child_badges_special_long ">'
											+'<span class="GYJH_span"> {{# value.split(",").join("</span><span class=\'GYJH_span\'>") }} </span>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSDZ{{value.split(",").join("") }}" id="KSDZ{{value.split(",").join("") }}" > {{ newOdds["KSDZ"+value.split(",").join("")] }} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
					+'</div>'
		
					+'<div class="mid_box">'
						+'<div class="mid-Title">围骰</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
								+'{{each BZ as value}}'
									+'<div class="midTWord_child clearfix odds_box  midTWord_child_special" id="KSBZ{{value.split(",").join("") }}" name="KSBZ{{value.split(",").join("") }}">'
										+'<div class="left midTWord_child_badges_special  midTWord_child_badges_special_long ">'
											+'<span class="GYJH_span"> {{# value.split(",").join("</span><span class=\'GYJH_span\'>") }} </span>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSBZ{{value.split(",").join("") }}" id="KSBZ{{value.split(",").join("") }}"> {{ newOdds["KSBZ"+value.split(",").join("")] }} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
								+'{{/each}}'
							+'</div>'
						+'</div>'
					+'</div>'
		
					+'<div class="mid_box">'
						+'<div class="mid-Title">其它</div>'
						+'<div class="mid-TWord">'
							+'<div class="midTWord_outer clearfix">'
		
									+'<div class="midTWord_child clearfix odds_box" id="KSBZZbz" name="KSBZZbz">'
										+'<div class="midTWord_child_badges_box">'
											+'<div class="left midTWord_child_badges_special ">豹子</div>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSBZZbz" id="KSBZZbz"> {{ newOdds["KSBZZbz"]}} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
									+'<div class="midTWord_child clearfix odds_box" id="KSSZsz" name="KSSZsz">'
										+'<div class="midTWord_child_badges_box">'
											+'<div class="left midTWord_child_badges_special   ">顺子</div>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSSZsz" id="KSSZsz"> {{ newOdds["KSSZsz"]}} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
		
									+'<div class="midTWord_child clearfix odds_box" id="KSDZZdz" name="KSDZZdz">'
										+'<div class="midTWord_child_badges_box">'
											+'<div class="left midTWord_child_badges_special  ">对子</div>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSDZZdz" id="KSDZZdz"> {{ newOdds["KSDZZdz"]}} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
									+'<div class="midTWord_child clearfix odds_box" id="KSZLzl" name="KSZLzl">'
										+'<div class="midTWord_child_badges_box">'
											+'<div class="left midTWord_child_badges_special ">杂六</div>'
										+'</div>'
										+'<div class="right showNum_text_box clearfix odds_box_sub">'
											+'<div class="left midTWord_child_showNum odds_pl" name="KSZLzl" id="KSZLzl"> {{ newOdds["KSZLzl"]}} </div>'
											+'<input type="text" class="midTWord_child_black">'
										+'</div>'
									+'</div>'
									
							+'</div>'
						+'</div>'
					+'</div>'
		
				+'</div>',
			
			
			k3Contentdata_rxh:''
				+'<div class="k3 mid_box">'
					+'<div class="mid-Title">单选[二同号]</div>'
					+'<div class="mid-TWord">'
						+'<div class="midTWord_outer clearfix">'
							+'{{each ETD as value }}'
								+'<div class="midTWord_child clearfix odds_box  midTWord_child_special " id=ETD{{value.join("")}}>'
									+'<div class="left midTWord_child_badges_special  midTWord_child_badges_special_long "><span class="GYJH_span">{{#value.join("</span><span class=\'GYJH_span\'>")}}</span></div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name=ETD{{value.join("")}}> {{newOdds["KSETD"+ value[0]+value[1]+value[2] ] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
							+'{{/each}}'
						+'</div>'
					+'</div>'
				+'</div>'
				+'<div class="mid_box k3">'
					+'<div class="mid-Title">单选[三不同号]</div>'
					+'<div class="mid-TWord">'
						+'<div class="midTWord_outer clearfix">'
							+'{{each SBT as value }}'
								+'<div class="midTWord_child clearfix odds_box  midTWord_child_special " id=SBT{{value.join("")}}>'
									+'<div class="left midTWord_child_badges_special  midTWord_child_badges_special_long "><span class="GYJH_span">{{#value.join("</span><span class=\'GYJH_span\'>")}}</span></div>'
									+'<div class="right showNum_text_box clearfix odds_box_sub">'
										+'<div class="left midTWord_child_showNum odds_pl" name=SBT{{value.join("")}}> {{newOdds["KSSBT"+ value[0]+value[1]+value[2] ] }} </div>'
										+'<input type="text" class="midTWord_child_black">'
									+'</div>'
								+'</div>'
							+'{{/each}}'
		
						+'</div>'
					+'</div>'
				+'</div>',
		
		
			mid_Tag_k3:''
				+'<div class="mid-Tag-sub clearfix">'	
					+'<div pan_type="zsp" class="midTag_child">主勢盤</div>'
					+'<div pan_type="rxh" class="midTag_child">任选号</div>'
				+'</div>',
		
			status3:'' //游戏结束时的内容
				+'<div class="game_end">'
					+'<div class="game_end_part1">'
						+'<div class="periods">第:<span>{{periods2}}</span>期</div>'
						+'<div class="gameTime">'
							+'<p>开盘时间:<span>{{xztime}}</span></p>'
							+'<p>开奖时间:<span>{{openPantime}}</span></p>'
						+'</div>'
					+'</div>'
					+'<div class="game_end_part2">'
						+'<div class="loadBox01">游戏结束</div>'
						+'<div class="loadBox02">等待开始中. . .</div>'
						+'<img src="style/images/loading02.gif" class="loadBox04" />'
					+'</div>'
				+'</div>',
		
			status2:''//游戏封盘的内容
				+'<div class="game_stop">'
					+'<div class="game_stop_part1">'
						+'<div class="periods">第:<span>{{periods2}}</span>期</div>'
						+'<div class="periods">开盘时间:<span>{{xztime}}</span></div>'
					+'</div>'
					+'<div class="game_stop_part2">'
						+'<div class="loadBox01">第:{{periods2}}期</div>'
						+'<div class="loadBox02">盘势准备中...</div>'
						+'<img src="style/images/loading02.gif" class="loadBox04" />'
					+'</div>'
				+'</div>',
		
			"alert_box":''
				+'<div class="alert_box_sub">'			
					+'<div class="alert_box_sub_header">{{header}}<div class="close_alert_box {{close_btn["clas"]}}" data-fn={{close_btn["fn"]}} ></div></div>'
					+'<div class="alert_box_sub_content"><div class="alert_box_sub_content_item">{{#content}}</div></div>'
					+'<div class="alert_box_sub_footer">'
						+'{{each btn as value i}}'
							+'<input type="button" class="alert_box_sub_btn {{i}}" value="{{value["text"]}}" data-fn={{value["fn"]}} >'
						+'{{/each}}'
					+'</div>'			
				+'</div>',

			'right_quick_bet':''
				+'<div class="quick_bet_box">'
					+'<div class="right_quick_bet_sub">'
						+'{{each date as value i}}'
							+'<div class="{{i}} quick_bet_sub_item">'
								+'<ul class="clearfix">'
									+'{{each value as val a}}'
										+'<li class="left {{a}}" data-title={{a}} data-quick-bet-obj={{quick_bet_obj}} data-number="{{val["number"].join(",")}}">{{val["name"]}}</li>'
									+'{{/each}}'
								+'</ul>'
							+'</div>'
						+'{{/each}}'
					+'</div>'
					+'<div class="right_quick_bet_bottom">'
						+'<div class="right_quick_bet_bottom_sub">'
							+'<div>共<span style="visibility:hidden">哈</span>计:&nbsp;<span class="right_quick_bet_num">0</span>注</div>'
							+'<div>每<span style="visibility:hidden">注</span>注:&nbsp;<input class="right_quickBet_every_input" type="text" placeholder="金额"/></div>'
							+'<div>总额度:&nbsp;<span class="right_quick_bet_tolMoney">0</span></div>'
							+'<div>'
								+'<input type="button" value="确定" class="right_quick_bet_sure">'
								+'<input type="button" value="取消" class="right_quick_bet_empty">'
							+'</div>'
						+'</div>'
					+'</div>'
					+'<div class="right_quick_bet_content">'
						+'点击上方文字投注'
					+'</div>'
				+'</div>',
			'right_quick_bet_content':''
				+'<div class="right_quick_bet_content_sub clearfix">'
					+'{{each quick_betBrders_date as value i}}'
						+'<div data-playOBJ="{{i}}" class="right_quick_bet_item">'
							+'<div class="clearfix"><span class="orderDelete_right_quick"></span></div>'
							+'<div class="title_money clearfix">'
								+'<span data-play={{value["play_lx"]}} class="left">{{value["titlePlayLx"]}}</span>'
								+'<span class="right">{{minMoney[value["play_lx"]]}}~{{maxMoney[value["play_lx"]]}}</span>'
							+'</div>'
							+'<div class="clearfix">'
								+'<div class="orderObj left">'
									+'<span style="color:#AE0F0E;">{{value["objMing"]}}</span>@'
									+'<span style="color:#AE0F0E;" class="{{i}}Odds">{{value["odds"]}}</span>'
								+'</div>'
								+'<input type="text" class="right_quickBet_moneyInput right" id="quick_betMoney{{i}}" value={{value["betMoney"]}}>'
							+'</div>'
						+'</div>'
					+'{{/each}}'
				+'</div>'

		}
})