// JavaScript Document
UI = {
	
//一个字
'Zhong':'MID',
'He':'DRAW',
'Zhu':'HOST',
'Ke':'Client',
'Da':'Over',
'Xiao':'Under',
'Dan':'Odd',
'Shuang':'Even',
'Shang':'FH',
'Chuan':'cluster',
'Rang':'Handicap',

//两个字
'GunQiu':'Bowls',
'JinRi':'Today',
'ZaoCan':'Beforehand',
'DanShi':'SINGLE',
'GuoGuan':'Clearance',
'GuanJun':'Champion',
'ShiJian':'Time',
'ShangBan':'First half',
'SaiShi':'Events',
'DuYing':'WIN',
'HeJu':'Tie',
'ZhuYing':'Home Win',
'KeYing':'Customer Win',
'RangQiu':'G&T',
'DaXiao':'O/U',
'DanShuang':'O/E',
'BoDan':'Correct Score',
'QiTa':'Other',
'ZhangHu':'Account',
'YuE':'Balance',
'MiMa':'Password',
'ShuaXin':'Refresh',
'PeiLv':'Ratio',
'LianSai':'League Matches',
'DuiMing':'Team',
'TouZhu':'Beting',
'JinE':'Amount',
'LeiJin':'Beat gold',
'YingLi':'Profit',
'ZuiDi':'Minimum',
'ZuiGao':'Maximum',
'FanHui':'Back',
'TiJiao':'Submit',
'QueDing':'Confirm',
'ZhuangTai':'Status',
'PanKou':'panType',
'DanHao':'Bet ID',
'ShouRang':'Transferee',
'GongGao': 'Affiche',
'LeiZhu': 'Challenge Slips',

'ShangBanChang':'HT',
'XiaBanChang':'UT',
'ZhongChang':'H-Time',
'DiYiJie':'Quarter1',
'DiErJie':'Quarter2',
'DiSanJie':'Quarter3',
'DiSiJie':'Quarter4',
'PanShu': 'Number of Discs',
'DiYiJu': 'The first game',
'DiErJu': 'Second game',
'DiSanJu': 'Third game',
'DiSiJu': 'Fourth game',
'DiWuJu': 'Ffifth game',
'JuShu': 'Rounds',
'QianWuJu': '5 Innings',
'BuBaoKuoJiaShiSai':'No Including overtime',
'BaoKuoJiaShiSai':'Including overtime',

'RuQiuShu':'Total Goal',
'BanQuanChang':'HT.FT',
'GengDuoWanFa':'More Played',

'XiangGangPan':'Hongkong',
'MaLaiPan':'Malaysian',
'OuZhouPan':'Europe',
'YanZhengMa':'Veri Code',

'ShiJianPaiXu':'Sort by time',
'LianSaiPaiXu':'Sort by league',
'QuanBuLianSai':'All League',
'GongGaoXinXi':'Notice Information',
'TeBieGongGao': 'Special Announcement',

'XiaZhuChengGong':'Successful bet',
'DengDaiQueRen':'Waiting confirmation',
'ZhuDanBuJieShou':'Do not accept bets',
'QueRenTouZhu':'Sure bet',

//系统
'ID10001': 'System maintenance, please try again later',
'ID10002': 'Connect to the server timed out, please try again later',
'ID10003': 'System message',
'ID10004': 'Login state failure, please re-login',


//通用
'Shi': 'YES',
'Fou': 'NO',
'Nian': 'Year',
'Qi': 'Period', 
'GeXia': 'Excellency',
'CunKuan': 'Deposit',
'TiKuan': 'Withdrawal',
'DuiWu': 'Team',
'ShengChu': 'Winners',
'BiFen': 'Score',
'QuanChang': 'Full Matche',
'LiuShuiHao': 'Serial number',
'SaiShiQuXiao': 'Event canceled',
'WuShuJuXinXi': 'No data',
'FanHuiShangYiBu': 'Go back',
'XiTongTiShiXinXi': 'System message',
'WuSaiCheng':'No Event Data',


//注册
'ZhuCe': 'Registration',
'JianCe': 'Detect',
'NiCheng': 'Nickname',
'DengLuXinXi': 'Login Data',
'QueRenDengLuMiMa': 'Confirm Password',
'QueRenTiKuanMiMa': 'Confirm Password withdrawal',
'TiKuanMiMa': 'Password withdrawal',
'YouXiangDiZhi': 'Email Address',
'SiRenWenTi': 'Personal problems',
'SiRenDaAn': 'Private answer',
'LianXiXinXi': 'Contact Information',
'ZhenShiXingMing': 'Real Name',
'SuoZaiGuoJia': 'Country',
'ShengShiQu': 'Province / city',
'YouZhengBianMa': 'Zip code',
'YanZhengJiXieYi': 'Verification and protocol',
'ShuaXinYanZhengMa': 'Click Refresh verification code',
'ZhuCe01': 'Welcome to join us',
'ZhuCe02': 'Can contain only letters, numbers or underscores, 6 to 20 characters',
'ZhuCe03': 'Password length of 6 to 20',
'ZhuCe04': 'Account security information',
'ZhuCe05': 'Please ensure that the e-mail address is available, otherwise the account will not activate and use',
'ZhuCe06': 'Please fill out the correct name, otherwise it will affect the withdrawal operation',
'ZhuCe07': 'I have 18 years of age and agree to',
'ZhuCe08': 'User Rules Terms',

'ID10101': 'Please enter the account name',
'ID10102': 'Please enter a password',
'ID10103': 'Please enter the password withdrawals',
'ID10104': 'Please enter the verification code',
'ID10105': 'Please enter the password to confirm',
'ID10106': 'Account name is not less than 6 characters',
'ID10107': 'Account name is not greater than 20 characters',
'ID10108': 'Login password not less than 6 characters',
'ID10109': 'Login password is not greater than 20 characters',
'ID10110': 'Password and Confirm password is not the same',
'ID10111': 'ATM password is not less than 6 characters',
'ID10112': 'ATM password is not greater than 20 characters',
'ID10113': 'Password and Confirm Password withdrawal withdrawal is not the same',
'ID10114': 'Please enter a valid email address',
'ID10115': 'Please enter the private security',
'ID10116': 'Please enter the private security answer',
'ID10117': 'Please enter a nickname',
'ID10118': 'Please enter a contact telephone',
'ID10119': 'Please enter a state',
'ID10120': 'Please enter a city',
'ID10121': 'Please enter the mailing address',
'ID10122': 'Please enter a zip code',
'ID10123': 'Must be at least 18 years old, and this site agree to the terms of the user agreement can be registered',
'ID10124': 'Congratulations! You can use this account name',
'ID10125': 'Sorry, you enter the account name used by other people',
'ID10126': 'Sorry, you have entered the e-mail use by others',
'ID10127': 'Sorry, you enter the verification code error',
'ID10128': 'Congratulations! Your account has been registered, please login to your e-mail activation',
'ID10129': 'User name can not contain Chinese characters',
'ID10130': 'Please enter the password to confirm withdrawal',
'ID10131': 'Please enter a real name',
'ID10132': 'Please enter the verification code',

'ID10133': 'Please enter the ID number',
'ID10134': 'Please enter the name of the bank',
'ID10135': 'Please enter the account branch',
'ID10136': 'Please enter a bank account',
'ID10138': 'Please enter the MSN or QQ',
'ID10139': 'Congratulations! Your account has been registered agent successfully! The system will automatically log you jump and automatically',

//登录
'ID10151': 'Account name or password is incorrect',
'ID10152': 'Verification code error',
'ID10153': 'Account is not active, please log filled out registration e-mail, to activate',
'ID10154': 'Accounts have been discontinued',
'ID10155': 'Congratulations, you successfully activate the account! Can be used normally after landing',

//找回密码
'ZhaoHuiMiMa': 'Retrieve Password',
'XianShiSiRenWenTi': 'Display personal problems',
'ID10201': 'Account name does not exist',
'ID10202': 'Private security Wrong Answer',
'ID10203': 'Successfully recover the password, new password has been sent to your e-mail',
'ID10204': 'Please click the "Show private problems" for security issues',
'ID10205': 'Please enter the security question',
'ZhaoHuiMiMa01': 'Please answer the question of private security, authentication is correct, the system will send the new password to your e-mail',
'ZhaoHuiMiMa02': 'E-mail to receive a new password',

//账户信息
'DiZhi': 'Address',
'ChengShiSheng': 'City / Province',
'YongHuXinXi': 'User Information',
'ZhangHuMingCheng': 'Account Name',  
'ZhangHuXingMing': 'Real Name',
'ZhangHuYuE': 'Account Balance',
'DongJieJinE': 'Freeze Money',
'DianYouDiZhi': 'Email Address',
'DengLuMiMa': 'Login Password',
'GuoJiaDiQu': 'Country / Region',
'YouZhengBianHao': 'Postal Code',
'HuoBiZhongLei': 'Currency',
'LianXiDianHua': 'TEL',
'XiuGaiDengLuMiMa': 'Change My Password',
'XiuGaiTiKuanMiMa': 'ATM password change',
'YinHangZhangHuXinXi': 'Bank account information',
'ShangCiDengLuIP': 'Current Login IP',
'ShangCiDengLuShiJian': 'Current login time',
'LeiTaiZhengBaJiLu': 'Ring record of hegemony',
'ZhouXuHao': 'Week number',
'QiShiRiQi': 'Start Date',
'JieShuRiQi': 'End date',
'YingLiJinE': 'Win amount',
'PaiMing': 'Ranking',

//银行账户信息
'YinHangMingCheng': 'Name of Bank',
'KaiHuZhiHang': 'Opening Branch',
'YinHangZhangHao': 'Bank account',
'BangDingZhangHu': 'Binding account',
'BangDingSheZhi': 'Binding set',
'ZhangHuLeiBie': 'Account Type',

//交易账单
'ShenQingShiJian': 'Application time',
'JiaoYiZhongZhi': 'Terminate the transaction',
'CunKuanChengGong': 'Deposit has been successful',
'DengDaiDaoZhang': 'Wait Daozhang',
'TiKuanChengGong': 'Successful withdrawal',
'DengDaiZhuanZhang': 'Waiting for transfer',

//在线支付
//第一步
'ZaiXianZhiFu': 'Online Payment',
'ZaiXianZhiFu01': 'Chinese debit cards, credit cards',
'ZaiXianZhiFu02': 'Through online banking or credit card online payment',
'ZaiXianZhiFu03': 'After the payment system in the 1 ~ 10 minutes automatically credited into your account',
'ZaiXianZhiFu04': 'Fee-free way to use the single limit of 2,000 yuan, the user one-day limit of 10,000 yuan deposit',

//第二步
'ZaiXianZhiFu05': 'Single minimum deposit amount of 100 yuan',
'ZaiXianZhiFu06': 'The maximum single deposit amount of 10,000 yuan',
'ZaiXianZhiFu07': 'Page will jump to your choice of online banking, please re-open the page in the transfer operation',
'ZaiXianZhiFu08': 'Application deposit promotion',

//银行转账
//第一步
'YinHangZhuanZhang': 'Bank Transfer',
'YinHangZhuanZhang01': "China's major banks quickly deposits",
'YinHangZhuanZhang02': '10 minutes to 24 hours of arrival, deposit the rebate immediately 5 per thousand, up 50 yuan',
'YinHangZhuanZhang03': 'Members through online banking or ATM transfer to the system designated account, the financial audit to the money credited into account immediately after you',
'YinHangZhuanZhang04': 'Recommended way to use the larger amount of deposits, long-term use of the storage means users can enhance the user level',

//第二步
'YinHangZhuanZhang05': 'Select the bank and enter the amount',
'YinHangZhuanZhang06': 'Select or enter new bank details',
'CunKuanJinE': 'Deposit Amount',
'HuoQuCunKuanXinXi': 'Access to deposit information',
'YinHangZhuanZhang07': 'Note and Deposit Information',
'YinHangZhuanZhang08': 'Please strictly follow the following bank information and the amount of the transfer',
'YinHangZhuanZhang09': 'The system will automatically bind you to the first successful bank deposit withdrawals as your bank',
'YinHangZhuanZhang10': 'Access to bank information and deposit amount, wrote the complete "deposit information" section and submit',
'YinHangZhuanZhang11': 'You can click on "Internet Banking" or to the bank counter or ATM to transfer operations',
'YinHangZhuanZhang16': 'Please fill in your bank account information for transfer',
'ZhiDingCunKuanJinE': 'Specify the amount of the deposit',
'WangShangYinHangWangZhi': 'Online banking website',
'JinRu': 'Enter',
'WangShangYinHang': 'Internet banking',
'TiJiaoCunKuanXinXi': 'Deposit information presented',
'XuanZeYinHangZhangHu': 'Select the bank account',
'ShouCunYouHui': 'First deposit bonus',
'YinHangZhuanZhang17': 'Attended the first deposit promotions, see <a href="./index2.php?tabID=5" target="_blank"> first deposit promotions </ a> Details',

//第三步
'YinHangZhuanZhang12': 'Deposit information has been submitted successfully, financial Once we receive your payment, you will be credited into account the first time',
'YinHangZhuanZhang13': 'For details, please see "History Bill"',
'YinHangZhuanZhang14': 'Delay due to network connection, it is possible to submit the deposit application is not successful',
'YinHangZhuanZhang15': 'Please enter the "trading bill," see the details, any questions please contact customer service',


'ID10251': 'Please enter the deposit amount',
'ID10252': 'Minimum deposit amount of 100 yuan',
'ID10253': 'The maximum amount of 100,000 yuan deposit',
'ID10254': 'Enter the amount of your deposit',
'ID10255': 'System specifies the amount of deposits',
'ID10256': 'After the success of the actual deposit amount credited into',
'ID10257': 'Be sure to specify the amount of the deposit, the Company does not accept the integer sum',
'ID10258': 'Thank you',
'ID10259': 'Please enter the deposit amount and click "Get Deposit Information" button!',
'ID10260': 'Please fill in banking information; or select an existing bank account!',
'ID10261': 'Please fill in banking information',
'ID10262': 'Binding instructions has been sent to your e-mail',
'ID10263': 'Failure to obtain instructions',

//	提款
//提款
//第一步
'WoYaoTiKuan': 'I want withdrawal',
'TiKuan01': 'Domestic bank transfer',
'TiKuan02': 'Recorded within 24 hours',
'TiKuan03': 'Membership applications daily withdrawal limit is: 200,000 yuan',
//'TiKuan04': 'After the second week (including second) generated by withdrawal fee (1% of withdrawal amount, each a minimum 2 yuan, up 50) borne by the Member',
//第二步
'TiKuanJinE': 'Withdrawal Amount',
'TiJiaoTiKuanShenQing': 'Withdrawal application submitted',
'TiKuan05': 'Since your account is not bound yet drawing account, bank account withdrawals before the binding',
'BangDingZhiLing': 'Binding instructions',
'TiKuan06': 'Send commands to the e-mail',
'TiJiaoBangDing': 'Submitted to binding',
'TiKuan07': 'Domestic bank transfer 【withdrawal】',
'TiKuan08': 'Such as: XX XX provincial cities (counties) XX district (town) XX Branch',
'TiKuan09': 'Drawing account name account name must be consistent with this site',
//绑定
'ID10301': 'Lock command has been sent to your e-mail',
'ID10302': 'Please go check',
'ID10303': 'Failure to obtain instructions',
'ID10304': 'Please enter the lock command',
'ID10305': 'Successful bank account lockout',
'ID10306': 'Command error, failed to bind',
'ID10307': 'Please enter the withdrawal amount',
'ID10308': 'Withdrawal amount not less than ',
'ID10309': 'ATM password is incorrect',
'ID10310': 'Insufficient account balance',
'ID10311': 'ATM withdrawal amount exceeds the maximum limit',
'ID10312': '24 hours operation only for a withdrawal',
'ID10313': 'Your bank accounts, account withdrawals not binding, not the withdrawal operation',
'ID10314': 'You deposit the money in circulation has not all been betting, withdrawals can not operate',
//第三步
'TiKuan10': 'Withdrawal application has been submitted, within 24 hours of financial will be credited into account your',

//修改密码
'XiuGaiDengLuMiMa':  'Change My Password',
'XiuGaiTiKuanMiMa':  'ATM password change',
'YuanDengLuMiMa':  'The original password',
'XinDengLuMiMa':  'New password',
'QueRenXinMiMa':  'Confirm new password',
'YuanTiKuanMiMa':  'The original ATM password',
'XinTiKuanMiMa':  'New ATM password',
'ID10351': 'The original password can not be empty',
'ID10352': 'New password can not be empty',
'ID10353': 'Confirm the password can not be empty',
'ID10354': 'Confirm the password and new password is not the same, please re-enter',
'ID10355': 'Change the password fails, the original password is wrong',
'ID10356': 'Password changed successfully',

//下注
'ID10401': 'Please enter a bet',
'ID10402': 'Not less than the amount bet',
'ID10403': 'Insufficient account balance',
'ID10404': 'Bet not more than',
'ID10405': 'The bet amount for the',
'ID10406': 'Sure bet',
'ID10407': 'Pause event bets',
'ID10408': 'Amount is incorrect',
'ID10409': 'Odds change',
'ID10410': 'Single string can not be less than 3 or greater than 10',
'ID10411': 'Against the same can not string a single',
'ID10412': 'The user has been suspended betting',
'ID10413': 'The user is not active, please log in to your mailbox used when registering, the activation',
'ID10414': 'Bet has been submitted',
'ID10415': 'See Note a single state information and betting',
'ID10416': 'The amount can be won',

//参加擂主争霸
'ID10501': 'For more details about Lei Zhu Championship, please refer to "promotions" in the Leizhu Competition Details! \ n \ n participate Leizhu Championship, you will need from your account to pay 100 yuan to buy 1000 gold coins. \ n \ n really want to continue operating cycles?',
'ID10502': 'Gold buying success! \ n \ n Now you can Leizhu hegemony Challenge! \ n \ n Note that in bets select the "Challenge Note" Select button, Lei Zhu hegemony are considered a single note!',
'ID10503': 'Sorry! You have participated in this week`s Leizhu Championship, please Come back next week!',
'ID10504': 'Sorry! Your account balance can not be less than 100 yuan to buy 1000 gold coins, please try again after the deposit!',
'ID10505': 'I want to beat coin redemption',
'ID10506': 'This week for hegemony ranking  TOP10',
'ID10507': 'This month for hegemony ranking  TOP10',
//其他提示性文字

1001: 'Championship - Specials',
1002: 'Sport Account',
1003: 'freeze',
1004: 'Casino Account',
1005: 'Lottery Account',
1006: 'Offers Record',
1007: 'Get Name',
1008: 'discount amount',
1009: 'date of application',
1010: 'Approval Status',
1011: 'preferential Remarks',
1012: 'stadium Account',
1013: 'account balance',
1014: 'No settlement amount',
1015: 'unfinished water',
1016: 'Casino Account',
1017: 'Lottery Account',
1018: 'Withdrawal Amount',
1019: 'Since your account has not been completed stadium and the water balance of accounts exist or settlement amount. \ N \ n hence the deposit will be generated by the operation of the water to accumulate. \ N \ n whether to continue to perform the deposit? ',
1020: 'deposit accounts',
1021: 'Sorry, the deposit amount is not less than',
1022: 'Sorry, the deposit amount can not exceed',
1023: 'online payment interface maintenance; please use other deposit method! ',
1024: 'Company recorded name of the bank',
1025: 'company bank account information',
1026: 'deposit accounts stadium',
1027: 'deposit casino account',
1028: 'lottery games into account',
1029: 'The minimum deposit amount',
1030: 'Maximum deposit amount',
1031: 'minimum',
1032: 'High',
1033: 'select an existing bank account',
1034: 'new bank account',
1035: 'money has been successfully transferred, the author confirmed arrival',
1036: 'Sorry, the deposit amount is not less than',
1037: 'Sorry, the deposit amount can not exceed',
1038: 'Please select the provinces',
1039: 'Please select the city',
1040: 'Please confirm your payment (',
1041: 'has been successfully transferred',
1042: 'select an existing bank account',
1043: 'new bank account',
1044: 'minimum withdrawal amount',
1045: 'maximum withdrawal amount',
1046: 'Special warnings',
1047: 'deposits and obtain preferential Daozhang required after completion of the corresponding bets only after the water requirements for fee-free withdrawals, or received bonus payments will be deducted',
1048: 'and',
1049: 'administrative costs',
1050: 'minimum withdrawal amount',
1051: 'maximum withdrawal amount',
1052: 'Make sure that your bank account for withdrawals name and account name Ben consistent, otherwise you will not be able to arrival',
1053: 'The 24 hours to enjoy once only fee-free withdrawals, the withdrawal will be charged 100 yuan fee, whether to continue the withdrawal operation ',
1054: 'Sorry! Withdrawal amount not less than',
1055: 'Sorry! Withdrawal amount can not exceed',
1056: 'Please select the provinces',
1057: 'Please select the city',
1058: 'Please complete the account opening branch name',
1059: 'Please fill bank account',
1060: 'Sorry, stadium account balance is insufficient!',
1061: 'Sorry, your sports account is currently enjoying preferential dividend',
1062: 'The withdrawal amount must be greater than',
1063: 'As the stadium unfinished bet the water',
1064: 'The withdrawal of the preferential dividend deduction accounts',
1065: 'and administration fee',
1066: 'specific amounts as follows',
1067: 'After discount bonus',
1068: 'administration fee',
1069: 'actual arrival Amount',
1070: 'really this account withdrawals',
1071: 'Application Failed'
}
