define(function(require,exports,module){
module.exports={
	
	'leftMenu':''
		+'{{each result as game }}'
			+'<div class="sport_tree_item  {{if game["game_lx"]==game_lx}}item_sub_active {{/if}}" >'
				+'<div class="item_sub clearfix" game_lx={{game["game_lx"]}}>'
					+'<div  class="img left gamelx{{game["game_lx"]}}" ></div>'
					+'<span class="left item_sub_name">{{game["game_name"]}}</span>'
					+'<span class="right item_sub_num">{{game["event_num"]}}</span>'
				+'</div>'
				+'<ul class="itemUl">'
					+'{{if game_lx==game["game_lx"] }}'
						+'{{each date["playMenu"] as list i}}'
							+'<li class="clearfix playitem {{if list["playItem"]==playitem }} itemUl_li_active {{/if}}" playItem={{list["playItem"]}} fn={{list["fn"]}}>'
								+'<span class="left">{{list["txt"]}}</span>'
								+'<span class="right item_sub_num">{{list["num"]}}</span>'
							+'</li>'
						+'{{/each}}'
					+'{{/if}}'
				+'</ul>'
			+'</div>'
		+'{{/each}}',

	'leftMenu_gq':''
		+'<ul class="itemUl">'
			+'{{each result as game}}'
				+'<li class="page_left_si {{if game["game_lx"]==game_lx }} itemUl_li_active {{/if}}" game_lx={{game["game_lx"]}}   fn="getDanShiOdds" >'				
					+'<span class="page_left_descrite">{{game["game_name"]}}</span>'
					+'<span class="num right">{{game["event_num"]}}</span>'
				+'</li>'
			+'{{/each}}'
		+'</ul>',

	'itemUl':''
		+'{{each date["playMenu"] as list i}}'
			+'<li class="clearfix playitem {{if list["playItem"]==playitem }} itemUl_li_active {{/if}}" playItem={{list["playItem"]}} fn={{list["fn"]}}>'
				+'<span class="left">{{list["txt"]}}</span>'
				+'<span class="right item_sub_num">{{list["num"]}}</span>'
			+'</li>'
		+'{{/each}}',

	'change_menu':''
		+'<div class="change_menu_box">'
			+'<div class="change_menu clearfix">'
				 +'<div class="left">'
					+'<span class="all {{ if isAll }} top_nav_left_active {{/if}}">全部</span>'
					+'<span class="top_nav_sc {{if !isAll }} top_nav_left_active {{/if}}">(<span class="sc_num">{{scNum}}</span>)</span>'
				 +'</div>'
				 +'<div class="right clearfix">'
					+'<button class="refresh left" title="点击刷新"><span class="refreshTime">{{refreshTime}}</span>&nbsp;S&nbsp;后自动刷新</button>'
					+'<div class="pan left">'
						+'<div class="panType" value={{panType}}><span class="left"> {{if panType==1}}香港盘{{else if panType==2}}马来盘{{else if panType==3}} 欧洲盘  {{/if}} </span><span class="top_nav_sjx_bottom"></span></div>'
						+'<div class="panType_box choose_box_sub">'
							+'<div class="panType_text" value=1>香港盘</div>'
							+'<div class="panType_text" value=2>马来盘</div>'
							+'<div class="panType_text" value=3>欧洲盘</div>'
						+'</div>'
					+'</div>'
					+'<div class="px left">'
						+'<div class="pxType" value={{order_by}}> <span class="left">{{if order_by==1}}联赛排序{{else if order_by==2}} 时间排序 {{/if}} </span><span class="top_nav_sjx_bottom"></span></div>'
						+'<div class="pxType_box choose_box_sub">'
							+'<div class="pxType_text" value=1>联赛排序</div>'
							+'<div class="pxType_text" value=2>时间排序</div>'
						+'</div>'
					+'</div>'
					
					+'<div class="ls left">'
						+'<div class="lsType"><span class="left">选择联赛&nbsp;&nbsp;<span class="choose_ls_num" style="color:#fff">{{choose_ls_num}}</span></span> <span class="top_nav_sjx_bottom"></span></div>'
						
					+'</div>'
					+'{{if pages}}'
					+'<div class="page_num left">'
						+'<div class="pageType" value={{currPage}}><span class="left">{{currPage}}'+'/{{pages}}页</span> <span class="top_nav_sjx_bottom"></span></div>'
						+'<div class="pageType_box choose_box_sub">'
							+'{{each pagesArr as item i}}'
								+'<div class="pageType_text" value={{i+1}}>{{item}}/{{pages}}页</div>'
							+'{{/each}}'
						+'</div>'						
					+'</div>'
					+'{{/if}}'
				 +'</div>'
			+'</div>'
		+'</div>'
		+'{{if one_week}}'
		+'<div class="change_date one_week">'
			+'<ul class="clearfix date_content">'
				+'<li class="left {{if !game_time}} date_active {{/if}}" value="" game_time="">所有日期</li>'
				+'{{each one_week as value i}}'
					+'<li class="left {{if value["game_time"]==game_time}} date_active  {{/if}}" game_time="{{value["game_time"]}}">{{value["txt"]}}</li>'
				+'{{/each}}'
			+'</ul>'
		+'</div>'
		+'{{/if}}',

	"lsType_box":''	
		+'<div class="lsType_boxs">'
			+'<div class="all_ls clearfix"><label class="left"><input type="checkbox" {{if lnum.length==0}}checked {{/if}}>全部联赛</label><div class="right close_lsType_box"></div></div>'
			+'<div class="ls_name_box_item">'
				+'<div class="ls_name_box clearfix left">'
					+'{{each ls as value i}}'
					+'<div class="ls_name">'
						+'<label>'
							+'<input type="checkbox" name="ls_input"  {{if value["isChecked"] }} checked {{/if}} value={{value["lnum"]}}>'
							+'<span>{{value["lx"]}}</span>'
						+'</label>'
					+'</div>' 
					+'{{/each}}'
				+'</div>'
				+'<div class="ls_name_scroll_box right"></div>'
			+'</div>'
			+'<div class="lsBtn">'
				+'<input type="button" value="确定" class="lsBtn_choose_ok">'
			+'</div>'
		+'</div>',



	
	"1_0_header_title":''//game_lx:1(足球)     playitem:0(1x2/让球/大小)
		  +'<table cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=235 ></col>'
				+'<col width=50></col>'
				+'<col width=100></col>'
				+'<col width=100></col>'
				+'<col width=50></col>'
				+'<col width=100></col>'
				+'<col width=100></col>'
				+'<col width=40></col>'
			+'</colgroup>'
			+'<thead>'
				+'<tr>'
					+'<th rowspan=2 style="text-align:left;border-left:none;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
					+'<th colspan=3 >全场</th>'
					+'<th colspan=3 >上半场</th>'
					+'<th>&nbsp;&nbsp;</th>'
				+'</tr>'
				+'<tr>'
					+'<th>独赢盘</th>'
					+'<th>让球</th>'
					+'<th>大小</th>'
					+'<th>独赢盘</th>'
					+'<th>让球</th>'
					+'<th>大小</th>'
					+'<th>&nbsp;&nbsp;</th>'
				+'</tr>'
		  +'</thead>'
		+'</table>',

	'1_0_content':''
		 +'{{each result as item}}'
			+'<div>'
				+'<div class="lx">{{item["lx"]}}<span class="lx_sc right {{if item["scClass"] }} lx_scClass {{/if}} "> </span></div>'
				+'<div class="pl_box">'
				+'{{each item["date"] as value i}}'															
						+'<table class={{tableBg(i)}} game_unique={{value["game_unique"]}} cellpadding=0 cellspacing=0>'
							+'<colgroup>'
								+'<col width=70 ></col>'
								+'<col width=165></col>'
								+'<col width=50></col>'
								+'<col width=100></col>'
								+'<col width=100></col>'
								+'<col width=50></col>'
								+'<col width=100></col>'
								+'<col width=100></col>'
								+'<col width=40></col>'
							+'</colgroup>'
							+'<tbody>'							
							+'<tr>'
								+'<td rowspan=3 valign=middle align="center">{{if value["hasSC"]>0 }}<div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div>{{/if}}</td>'//时间 队名
								+'<td align=center><span class="{{if value["pk_num_rq_0"]!=null && value["pk_num_rq_0"]>=0}}gname{{/if}}">{{value["gname1"]}}</span></td>' //队名1
								+'<td align=center>{{if value["dy1_0"] && value["dy1_0"]>0}}<span class="odds" data-action={{action( value["game_unique"], 1, 1,0,"",value["dy1_0"] )}}>{{value["dy1_0"]}}</span>{{/if}}</td>' //独赢盘
								+'<td>{{if value["rqpl1_0"]}} <span class="pk_num ">{{if value["pk_num_rq_0"]>=0}} {{abs(value["pk_num_rq_0"])}}{{/if}}</span> <span class="odds " data-action={{ action( value["game_unique"], 2,1,0,value["pk_num_rq_0"],value["rqpl1_0"] ) }}>{{value["rqpl1_0"]}}</span>{{/if}}</td>' //让球
								+'<td>{{if value["dxpl1_0"]}} <span class="pk_num ">{{if value["pk_num_dx_0"]>=0}} {{abs(value["pk_num_dx_0"])}} {{/if}}</span> <span class="odds " data-action={{action( value["game_unique"], 3,1,0,value["pk_num_dx_0"],value["dxpl1_0"] ) }}>{{value["dxpl1_0"]}}</span>{{/if}}</td>' //大小
								+'<td align=center>{{if value["dy1_1"] && value["dy1_1"]>0 }}<span class="odds" data-action={{action( value["game_unique"],1,1,1,"",value["dy1_1"] )}}>{{value["dy1_1"]}}</span>{{/if}}</td>'  //独赢 半场
								+'<td>{{if value["rqpl1_1"]}} <span class="pk_num ">{{if value["pk_num_rq_1"]>=0}} {{abs(value["pk_num_rq_1"])}} {{/if}}</span> <span class="odds " data-action={{  action( value["game_unique"], 2,1,1,value["pk_num_rq_1"],value["rqpl1_1"] )  }}>{{value["rqpl1_1"]}}</span>{{/if}}</td>' //让球 半场
								+'<td>{{if value["dxpl1_1"]}} <span class="pk_num ">{{if value["pk_num_dx_1"]>=0}} {{abs(value["pk_num_dx_1"])}} {{/if}}</span> <span class="odds " data-action={{ action( value["game_unique"], 3,1,1,value["pk_num_dx_1"],value["dxpl1_1"]  ) }}>{{value["dxpl1_1"]}}</span>{{/if}}</td>' //大小 半场
								+'<td rowspan={{if value["hasSC"] }}3{{else}}2{{/if}}>{{if value["hasSC"]}}<span class="td_sc {{if value["scClass"]}} scClass {{/if}}" game_unique={{value["game_unique"]}}> </span>{{/if}}</td>'
							+'</tr>'
							+'<tr>'
								+'<td  align=center><span class="{{if value["pk_num_rq_0"]!=null && value["pk_num_rq_0"]<0}}gname{{/if}}">{{value["gname2"]}}</span></td>'//队名2
								+'<td  align=center>{{if value["dy2_0"] && value["dy2_0"]>0 }}<span class="odds" data-action={{action( value["game_unique"], 1,2,0,"",value["dy2_0"] )}}>{{value["dy2_0"]}}</span>{{/if}}</td>' //独赢盘
								+'<td> {{if value["rqpl2_0"]}}<span class="pk_num ">{{if value["pk_num_rq_0"]<0}} {{abs(value["pk_num_rq_0"])}} {{/if}}</span> <span class="odds " data-action={{  action( value["game_unique"], 2,2,0,value["pk_num_rq_0"],value["rqpl2_0"] )  }}>{{value["rqpl2_0"]}}</span>{{/if}}</td>' //让球
								+'<td>{{if value["dxpl2_0"]}} <span class="pk_num ">{{if value["pk_num_dx_0"]<0}} {{abs(value["pk_num_rq_0"])}} {{/if}}</span> <span class="odds " data-action={{  action( value["game_unique"], 3,2,0,value["pk_num_dx_0"],value["dxpl2_0"] ) }}>{{value["dxpl2_0"]}}</span>{{/if}}</td>' //大小
								+'<td align=center>{{if value["dy2_1"] && value["dy2_1"]>0 }}<span class="odds" data-action={{ action( value["game_unique"],1,2,1,"",value["dy2_1"] ) }}>{{value["dy2_1"]}}</span>{{/if}}</td>'  //独赢 半场
								+'<td> {{if value["rqpl2_1"]}} <span class="pk_num ">{{if value["pk_num_rq_1"]<0}} {{abs(value["pk_num_rq_1"])}} {{/if}}</span> <span class="odds " data-action={{ action( value["game_unique"], 2,2,1,value["pk_num_rq_1"],value["rqpl2_1"] ) }}>{{value["rqpl2_1"]}}</span>{{/if}}</td>' //让球 半场
								+'<td>{{if value["dxpl2_1"]}} <span class="pk_num ">{{if value["pk_num_dx_1"]<0}} {{abs(value["pk_num_dx_1"])}} {{/if}}</span> <span class="odds " data-action={{ action( value["game_unique"], 3,2,1,value["pk_num_dx_1"],value["dxpl2_1"]) }}>{{value["dxpl2_1"]}}</span>{{/if}}</td>' //大小 半场										
							+'</tr>'
							+'{{if value["hasSC"]}}'
							+'<tr>'
								+'<td  align=center class="hj">和局</td>'
								+'<td  align=center>{{if value["dy3_0"]>0}}<span class="odds" data-action={{action( value["game_unique"],1,3,0,"",value["dy3_0"] ) }}>{{value["dy3_0"]}}</span>{{/if}} <div class="more_play_num {{if value["more_play_num"]>0}}more_play {{/if}}" {{if value["more_play_num"]}} title="更多玩法" {{/if}} {{if value["more_play_num"]}} game_unique={{value["game_unique"]}} {{/if}}>  {{if value["more_play_num"]>0}} +{{value["more_play_num"]}}&gt;&gt; {{/if}}</div>  </td>'
								+'<td ></td>'
								+'<td ></td>'
								+'<td align=center>{{if value["dy3_1"]>0}}<span class="odds" data-action={{action( value["game_unique"],1,3,1,"",value["dy3_1"] ) }}>{{value["dy3_1"]}}</span>{{/if}}</td>'
								+'<td ></td>'
								+'<td ></td>'
							+'</tr>'
							+'{{/if}}'
						+'</tbody></table>'								
					 
				+'{{/each}}'
				+'</div>'
			+'</div>'
		 +'{{/each}}',


	"2_0_header_title":''
		  +'<table class="lq_header_title" cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=231></col>'
				+'<col width=126></col>'
				+'<col width=126></col>'
				+'<col width=126></col>'
				+'<col width=126></col>'
				+'<col width=40></col>'
			+'</colgroup>'
			+'<tbody>'
			+'<tr>'
				+'<th style="text-align:left;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th>独赢</th>'
				+'<th>让球</th>'
				+'<th>大小</th>'
				+'<th>单双</th>'
				+'<th></th>'
			+'</tr>'
		  +'</tbody></table>',

	"2_0_content":''
			+'{{each result as item}}'
				+'<div>'
					+'<div class="lx">{{item["lx"]}}<span class="lx_sc right {{if item["scClass"]}} lx_scClass {{/if}}"> </span></div>'
					+'<div class="pl_box">'
						+'{{each item["date"] as value i}}'
							
								+'<table class={{tableBg(i)}} class="lq_table" game_unique={{value["game_unique"]}} cellpadding=0 cellspacing=0>'
									+'<colgroup>'
										+'<col width=70></col>'
										+'<col width=161></col>'
										+'<col width=126></col>'
										+'<col width=126></col>'
										+'<col width=126></col>'
										+'<col width=126></col>'
										+'<col width=40></col>'
									+'</colgroup>'

									+'<tbody>'
									+'<tr>'
										+'<td  rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div><div>[{{value["half_name"]}}]</div></div></td>' //比赛时间
										+'<td >{{value["gname1"]}}</td>' // 比赛队名 1
										+'<td >{{if value["dy1"]>0}}<span class="odds" data-action={{action( value["game_unique"],1,1,0,"",value["dy1"] )}}>{{value["dy1"]}}</span>{{/if}}</td>'//独赢
										+'<td >{{if value["rqpl1"]>0}}<span class="pk_num">{{if value["pk_num_rq"]>0}} {{abs(value["pk_num_rq"])}} {{/if}}</span>  <span class="odds" data-action={{action( value["game_unique"],2,1,0,value["pk_num_rq"],value["rqpl1"] )}}>{{value["rqpl1"]}}</span>{{/if}}</td>'//让球
										+'<td >{{if value["dxpl1"]>0}}<span class="pk_num">{{if value["pk_num_dx"]>0}} {{abs(value["pk_num_dx"])}} {{/if}}</span>  <span class="odds" data-action={{ action(value["game_unique"],3,1,0,value["pk_num_dx"],value["dxpl1"]) }}>{{value["dxpl1"]}}</span> {{/if}}</td>'// 大小
										+'<td >{{if value["dspl1"]>0}} <span class="odds" data-action={{ action( value["game_unique"],4,1,0,"",value["dspl1"] ) }}>{{value["dspl1"]}}</span> {{/if}}</td>'// 单双
										+'<td  rowspan=2>{{if value["hasSC"]}}<span class="td_sc {{if value["scClass"]}} scClass {{/if}}" game_unique={{value["game_unique"]}} > </span>{{/if}}</td>'
									+'</tr>'
									+'<tr>'
										+'<td>{{value["gname2"]}}</td>' // 比赛队名 2
										+'<td>{{if value["dy2"]>0}}<span class="odds" data-action={{action( value["game_unique"],1,2,0,"",value["dy1"] )}}>{{value["dy2"]}}</span>{{/if}}</td>' //独赢
										+'<td>{{if value["rqpl2"]>0}}  <span class="pk_num">{{if value["pk_num_rq"]<0}} {{abs(value["pk_num_rq"])}}{{/if}}</span>  <span class="odds" data-action={{ action( value["game_unique"],2,2,0,value["pk_num_rq"],value["rqpl2"] ) }}>{{value["rqpl2"]}}</span>{{/if}}</td>'//让球
										+'<td>{{if value["dxpl2"]>0}} <span class="pk_num">{{if value["pk_num_dx"]<0}} {{abs(value["pk_num_dx"])}}{{/if}}</span>   <span class="odds" data-action={{ action(value["game_unique"],3,2,0,value["pk_num_dx"],value["dxpl2"]) }}>{{value["dxpl2"]}}</span> {{/if}}</td>'// 大小
										+'<td>{{if value["dspl2"]>0}} <span class="odds" data-action={{ action( value["game_unique"],4,2,0,"",value["dspl2"] ) }}>{{value["dspl2"]}}</span> {{/if}}</td>' // 单双
									+'</tr>'
								+'</tbody></table>'
							
						+'{{/each}}'
					+'</div>'
				+'</div>'
			+'{{/each}}',

	"ds_header_title":''
		 +'<table class="ds_header_title" cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=235></col>'
				+'<col width=135></col>'
				+'<col width=135></col>'
				+'<col width=135></col>'
				+'<col width=135></col>'
			+'</colgroup>'
			+'<thead>'
			+'<tr>'
				+'<th rowspan=2 style="text-align:left;border-left:none;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th colspan=2 >全场</th><th colspan=2 style="border-right:none;">半场</th>'
			+'</tr>'
			+'<tr>'
				+'<th>单</th>'
				+'<th>双</th>'
				+'<th>单</th>'
				+'<th style="border-right:none;">双</th>'
			+'</tr>'
		 +'</thead></table>',

	"ds_content":''
		+'{{each result as item}}'
			+'<div>'
				+'<div class="lx">{{item[0]}}</div>'
				+'<div class="pl_box">'
					+'{{each item as value i}}'
					+'{{if i>0}}'
						+'<table class={{tableBg(i)}} cellpadding=0 cellspacing=0>'
							+'<colgroup>'
								+'<col width=60></col>'
								+'<col width=175></col>'
								+'<col width=135></col>'
								+'<col width=135></col>'
								+'<col width=135></col>'
								+'<col width=135></col>'
							+'</colgroup>'
							+'<tbody>'
							+'<tr>'
								+'<td rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div></td>'//时间
								+'<td >{{value["gname1"]}}</td>'//队名1
								+'<td rowspan=2>{{if value["dspl1_0"]}}<span class="odds" data-action={{action( value["game_unique"],4,1,0,"",value["dspl1_0"])}}>{{value["dspl1_0"]}}</span>{{/if}}</td>'//全场 单
								+'<td rowspan=2>{{if value["dspl2_0"]}}<span class="odds" data-action={{action( value["game_unique"],4,2,0,"",value["dspl2_0"] )}}>{{value["dspl2_0"]}}</span>{{/if}}</td>'//全场 双
								+'<td rowspan=2>{{if value["dspl1_1"]}}<span class="odds" data-action={{action( value["game_unique"],4,1,1,"",value["dspl1_1"] )}}>{{value["dspl1_1"]}}</span>{{/if}}</td>'//上半场 单
								+'<td rowspan=2>{{if value["dspl2_1"]}}<span class="odds" data-action={{action( value["game_unique"],4,2,1,"",value["dspl2_1"] )}}>{{value["dspl2_1"]}}</span>{{/if}}</td>'//上半场 双
							+'</tr>'
							+'<tr><td >{{value["gname2"]}}</td></tr>'
						+'</tbody></table>'
					+'{{/if}}'
					+'{{/each}}'
				+'</div>'
			+'</div>'
		+'{{/each}}',

	"rqs_header_title":''
		  +'<table cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=215></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
				+'<col width=70></col>'
			+'</colgroup>'

			+'<thead>'
			+'<tr>'
				+'<th rowspan=2  style="text-align:left;border-left:none;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th colspan=4 >全场</th>'
				+'<th colspan=4 >上半场</th>'
			+'</tr>'
			+'<tr>'
				+'<th>0-1</th>'
				+'<th>2-3</th>'
				+'<th>4-6</th>'
				+'<th>7或以上</th>'
				+'<th>0-1</th>'
				+'<th>2-3</th>'
				+'<th>4-6</th>'
				+'<th>7或以上</th>'
			+'</tr>'
		  +'</thead></table>',
	
	"rqs_content":''
		 +'{{each result as item}}'
			+'<div>'
				+'<div class="lx">{{item[0]}}</div>'
				+'<div class="pl_box">'
					+'{{each item as value i}}'
						+'{{if i>0}}'
							+'<table class={{tableBg(i)}} cellpadding=0 cellspacing=0 >'
								+'<colgroup>'
									+'<col width=70></col>'
									+'<col width=145></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
									+'<col width=70></col>'
								+'</colgroup>'
								+'<tbody>'
								+'<tr>'
									+'<td rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div></td>'//时间
									+'<td >{{value["gname1"]}}</td>' //队名1
									+'<td rowspan=2 >{{if value["pl_0_1_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_0_1",0,"",value["pl_0_1_0"] ) }}>{{value["pl_0_1_0"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_2_3_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_2_3",0,"",value["pl_2_3_0"] ) }}>{{value["pl_2_3_0"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_4_6_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_4_6",0,"",value["pl_4_6_0"] ) }}>{{value["pl_4_6_0"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_7up_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_7up",0,"",value["pl_7up_0"] ) }}>{{value["pl_7up_0"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_0_1_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_0_1",1,"",value["pl_0_1_1"] ) }}>{{value["pl_0_1_1"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_2_3_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_2_3",1,"",value["pl_2_3_1"] ) }}>{{value["pl_2_3_1"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_4_6_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_4_6",1,"",value["pl_4_6_1"] ) }}>{{value["pl_4_6_1"]}}</span>{{/if}}</td>'
									+'<td rowspan=2 >{{if value["pl_7up_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_7up",1,"",value["pl_7up_1"] ) }}>{{value["pl_7up_1"]}}</span>{{/if}}</td>'
								+'</tr>'
								+'<tr>'
									+'<td >{{value["gname2"]}}</td>' //队名2
								+'</tr>'
							+'</tbody></table>'
						+'{{/if}}'
					+'{{/each}}'
				+'</div>'
			+'</div>'
		 +'{{/each}}',

	
	"bd_header_title":''
		 +'<table class="bd_header_title" cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=135></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
				+'<col width=40></col>'
			+'</colgroup>'
			+'<thead>'
			+'<tr>'
				+'<th style="text-align:left;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th>1-0</th>'
				+'<th>2-0</th>'
				+'<th>2-1</th>'
				+'<th>3-0</th>'
				+'<th>3-1</th>'
				+'<th>3-2</th>'
				+'<th>4-0</th>'
				+'<th>4-1</th>'
				+'<th>4-2</th>'
				+'<th>4-3</th>'
				+'<th>0-0</th>'
				+'<th>1-1</th>'
				+'<th>2-2</th>'
				+'<th>3-3</th>'
				+'<th>4-4</th>'
				+'<th>其他</th>'
			+'</tr>'
		 +'</thead></table>',

	
	"bd_content":''
		+'{{each result as item}}'
			+'<div>'
				+'<div class="lx">{{item[0]}}</div>'
				+'<div class="pl_box">'
					+'{{each item as value i}}'
						+'{{if i>0}}'
							+'<table class="{{tableBg(i)}} bodan_table" cellpadding=0 cellspacing=0>'
								+'<colgroup>'
									+'<col width=55></col>'
									+'<col width=80></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
									+'<col width=40></col>'
								+'</colgroup>'
								+'<tbody>'
								+'<tr>'
									+'<td rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div></td>' //生成时间
									+'<td >{{value["gname1"]}}</td>' //生成队名1
									+'<td >{{if value["pl_1_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_0",0,"",value["pl_1_0"] ) }}>{{value["pl_1_0"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_2_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_0",0,"",value["pl_2_0"] ) }}>{{value["pl_2_0"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_2_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_1",0,"",value["pl_2_1"] ) }}>{{value["pl_2_1"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_3_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_0",0,"",value["pl_3_0"] ) }}>{{value["pl_3_0"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_3_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_1",0,"",value["pl_3_1"] ) }}>{{value["pl_3_1"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_3_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_2",0,"",value["pl_3_2"] ) }}>{{value["pl_3_2"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_4_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_0",0,"",value["pl_4_0"] ) }}>{{value["pl_4_0"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_4_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_1",0,"",value["pl_4_1"] ) }}>{{value["pl_4_1"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_4_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_2",0,"",value["pl_4_2"] ) }}>{{value["pl_4_2"]}}</span>{{/if}}</td>'
									+'<td >{{if value["pl_4_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_3",0,"",value["pl_4_3"] ) }}>{{value["pl_4_3"]}}</span>{{/if}}</td>'
									
									+'<td  rowspan=2>{{if value["pl_0_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_0",0,"",value["pl_0_0"] ) }}>{{value["pl_0_0"]}}</span>{{/if}}</td>'
									+'<td rowspan=2>{{if value["pl_1_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_1",0,"",value["pl_1_1"] ) }}>{{value["pl_1_1"]}}</span>{{/if}}</td>'
									+'<td rowspan=2>{{if value["pl_2_2"]}}<span class="odds"  data-action={{ action( value["game_unique"],6,"pl_2_2",0,"",value["pl_2_2"] ) }}>{{value["pl_2_2"]}}</span>{{/if}}</td>'
									+'<td  rowspan=2>{{if value["pl_3_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_3",0,"",value["pl_3_3"] ) }}>{{value["pl_3_3"]}}</span>{{/if}}</td>'
									+'<td  rowspan=2>{{if value["pl_4_4"]}}<span class="odds"  data-action={{ action( value["game_unique"],6,"pl_4_4",0,"",value["pl_4_4"] ) }}>{{value["pl_4_4"]}}</span>{{/if}}</td>'
									+'<td  rowspan=2>{{if value["pl_5up"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_5up",0,"",value["pl_5up"] ) }}>{{value["pl_5up"]}}</span>{{/if}}</td>'
									
								+'</tr>'
								+'<tr>'
									+'<td>{{value["gname2"]}}</td>' //生成队名1
									+'<td>{{if value["pl_0_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_1",0,"",value["pl_0_1"] ) }}>{{value["pl_0_1"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_0_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_2",0,"",value["pl_0_2"] ) }}>{{value["pl_0_2"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_1_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_2",0,"",value["pl_1_2"] ) }}>{{value["pl_1_2"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_0_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_3",0,"",value["pl_0_3"] ) }}>{{value["pl_0_3"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_1_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_3",0,"",value["pl_1_3"] ) }}>{{value["pl_1_3"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_2_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_3",0,"",value["pl_2_3"] ) }}>{{value["pl_2_3"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_0_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_4",0,"",value["pl_0_4"] ) }}>{{value["pl_0_4"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_1_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_4",0,"",value["pl_1_4"] ) }}>{{value["pl_1_4"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_2_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_4",0,"",value["pl_2_4"] ) }}>{{value["pl_2_4"]}}</span>{{/if}}</td>'
									+'<td>{{if value["pl_3_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_4",0,"",value["pl_3_4"] ) }}>{{value["pl_3_4"]}}</span>{{/if}}</td>'
								+'</tr>'
							+'</tbody></table>'
						+'{{/if}}'
					+'{{/each}}'
				+'</div>'
			+'</div>'
		+'{{/each}}',

	"bqc_header_title":''
		  +'<table cellpadding=0 cellspacing=0>'
			+'<colgroup>'
				+'<col width=235></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
				+'<col width=60></col>'
			+'<colgroup>'

			+'<thead>'
			+'<tr>'
				+'<th style="text-align:left;border-left:none;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th width=60>主主</th>'
				+'<th width=60>主和</th>'
				+'<th width=60>主客</th>'
				+'<th width=60>和主</th>'
				+'<th width=60>和和</th>'
				+'<th width=60>和客</th>'
				+'<th width=60>客主</th>'
				+'<th width=60>客和</th>'
				+'<th width=60>客客</th>'
			+'</tr>'
		  +'</thead></table>',

	"bqc_content":'{{each result as item}}'
		 +'<div>'
			+'<div class="lx">{{item[0]}}</div>'
			+'<div class="pl_box">'
				+'{{each item as value i}}'
				+'{{if i>0}}'
					+'<table class={{tableBg(i)}} cellpadding=0 cellspacing=0>'
						+'<colgroup>'
							+'<col width=70></col>'
							+'<col width=165></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
							+'<col width=60></col>'
						+'</colgroup>'
						+'<tbody>'
						+'<tr>'
							+'<td rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div></td>' //时间
							+'<td >{{value["gname1"]}}</td>' //队名1
							+'<td rowspan=2>{{if value["pl_H_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_H",0,"",value["pl_H_H"] ) }}>{{value["pl_H_H"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_H_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_N",0,"",value["pl_H_N"] ) }}>{{value["pl_H_N"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_H_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_C",0,"",value["pl_H_C"] ) }}>{{value["pl_H_C"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_N_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_H",0,"",value["pl_N_H"] ) }}>{{value["pl_N_H"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_N_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_N",0,"",value["pl_N_N"] ) }}>{{value["pl_N_N"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_N_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_C",0,"",value["pl_N_C"] ) }}>{{value["pl_N_C"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_C_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_H",0,"",value["pl_C_H"] ) }}>{{value["pl_C_H"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_C_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_N",0,"",value["pl_C_N"] ) }}>{{value["pl_C_N"]}}</span>{{/if}}</td>'
							+'<td rowspan=2>{{if value["pl_C_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_C",0,"",value["pl_C_C"] ) }}>{{value["pl_C_C"]}}</span>{{/if}}</td>'
						+'</tr>'
						+'<tr>'
							+'<td>{{value["gname2"]}}</td>' //队名2
						+'</tr>'
					+'</tbody></table>'
				+'{{/if}}'
				+'{{/each}}'
			+'</div>'
		 +'</div>'
		 +'{{/each}}',


	"xhrq_header_title":'' //先后入球
		 +'<table width=100%  cellpadding=0 cellspacing=0 class="xhrq_header_title">'
			+'<colgroup>'
				+'<col width=310></col>'
				+'<col width=155></col>'
				+'<col width=155></col>'
				+'<col width=155></col>'

			+'</colgroup>'
			+'<thead>'
			+'<tr>'
				+'<th style="text-align:left;border-right:0;"><span class="game_lx_html">{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th>'
				+'<th>最先进球</th>'
				+'<th>最后进球</th>'
				
				+'<th>没有进球</th>'
				
			+'</tr>'
		 +'</thead></table>',


	"xhrq_content":''
		+'{{each result as item}}'
			+'<div>'
				+'<div class="lx">{{item[0]}}</div>'
				+'<div class="pl_box">'
					+'{{each item as value i}}'
						+'{{if i>0}}'
							+'<table class="{{tableBg(i)}}" width=100% cellpadding=0 cellspacing=0 >'
								+'<colgroup>'
									+'<col width=70></col>'
									+'<col width=240></col>'
									+'<col width=155></col>'
									+'<col width=155></col>'
									+'<col width=155></col>'
								+'</colgroup>'

								+'<tbody>'
								+'<tr>'
									+'<td  rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div class="time_color">{{value["time"]}}</div></div></td>' //生成时间
									+'<td>{{value["gname1"]}}</td>' //生成队名1
									
									+'<td >{{if value["pl_x_h"]}}<span class="odds" data-action={{ action( value["game_unique"],8,"pl_x_h",0,"",value["pl_x_h"] ) }}>{{value["pl_x_h"]}}</span> {{/if}}</td>'
									+'<td >{{if value["pl_h_h"]}}<span class="odds" data-action={{ action( value["game_unique"],8,"pl_h_h",0,"",value["pl_h_h"] ) }}>{{value["pl_h_h"]}}</span> {{/if}}</td>'
									+'<td rowspan=2>{{if value["pl_n"]}}<span class="odds" data-action={{ action( value["game_unique"],8,"pl_n",0,"",value["pl_n"] ) }}>{{value["pl_n"]}}</span> {{/if}}</td>'
									
								+'</tr>'
								+'<tr>'
									+'<td>{{value["gname2"]}}</td>' //生成队名1
									
									+'<td >{{if value["pl_x_c"]}}<span class="odds" data-action={{ action( value["game_unique"],8,"pl_x_c",0,"",value["pl_x_c"] ) }}>{{value["pl_x_c"]}}</span> {{/if}}</td>'
									+'<td >{{if value["pl_h_c"]}}<span class="odds" data-action={{ action( value["game_unique"],8,"pl_h_c",0,"",value["pl_h_c"] ) }}>{{value["pl_h_c"]}}</span> {{/if}}</td>'
										
								+'</tr>'
							+'</tbody></table>'
						+'{{/if}}'
					+'{{/each}}'
				+'</div>'
			+'</div>'
		+'{{/each}}',

	'gj_header_title':''
		 +'<table width=100% cellpadding=0 cellspacing=0><thead>'
			+'<tr><th style="text-align:left;"><span class="game_lx_html">冠军&nbsp;{{game_lx_html}}</span><span class="time_lx_html">{{time_lx_html}}</span></th></tr>'
		 +'</thead></table>',

	"gj_content":''
		 +'{{each data as item}}'
			+'<div>'
				+'<div class="lx clearfix"><span class="left gj_lx_text">{{item["lx"]}}</span> <div class="right"><span class="gj_time">{{ item["game_time"] }}</span> <span class="time_color">{{item["time"]}}</span></div></div>'
				+'<div class="pl_box">'
					+'{{each item["lx_sub"] as value i}}'
						+'<div class="lx_sub">'
							+'<div class="lx_sub_text">'
								+'{{i}}'
							+'</div>'
							+'<table width=100% class="gj_table" cellpadding=0 cellspacing=0 ><tbody>'
							+'{{each value as name i}}'
								+'<tr class="lx_sub_tr {{tableBg(i)}}">'
									+'{{each name as td}}'
										+'<td width=50% valign="middle" class="lx_sub_name  {{td["gj_left_div"]}}">'
											+'<span class="gj_lx_sub_gname left "> {{ td["gname"] }} </span>'
											+'<div class="right gj_lx_sub_odds_box">{{if td["pl"]}}<span class="odds"  data-action={{ action( td["game_unique"],10,td["gid"],0,"",td["pl"] ) }} > {{ td["pl"] }} </span>{{/if}}</div>'
										+'</td>'
									+'{{/each}}'
								+'</tr>'
							+'{{/each}}'
							+'</tbody></table>'
						+'</div>'
					+'{{/each}}'
				+'</div>'
			+'</div>'
		 +'{{/each}}',

	'more_play':''
		+'<div class="more_play_box">'
			+'<div class="more_play_zhezhao"></div>'
			+'<div class="more_play_content">'
				+'<div class="more_play_content_header">'
					+'<div class="more_play_content_header_text">'
						+'<span class="game_lx_text">{{game_lx_html}}</span>'
						+'<span class="time_lx_text">{{time_lx_html}}</span>'
						+'<span class="lx_name">{{lx_name}}</span>'
						+'<span class="gname">{{gname1}}&nbsp;<em>v</em>&nbsp;{{gname2}}</span>'
					+'</div>'
					+'<div class="close_more_play_box"></div>'
				+'</div>'
				+'<div class="more_play_content_box clearfix">'
					+'<div class="more_play_content_sub left"><div class="more_play_sub_item">'
						+'{{each result as arr i}}'
						+'{{if i=="ds" && arr.length>0}}'
							+'<div class="ds_box">'
								+'<div class="ds_box_header  more_play_sub_name">'
									+'<div>单双</div>'
								+'</div>'
								+'<div class="ds_box_table">'
									+'<table cellpadding=0 cellspacing=0>'
										+'<thead>'
											+'<tr>'
												+'<th rowspan=2 width=158></th>'
												+'<th colspan=2 width=230>全场</th><th colspan=2 width=230 style="border-right:none;">半场</th>'
											+'</tr>'
											+'<tr>'
												+'<th>单</th>'
												+'<th>双</th>'
												+'<th>单</th>'
												+'<th style="border-right:none;">双</th>'
											+'</tr>'
										+'</thead>'
										+'<tbody>'
											+'{{each arr as value a}}'
											+'<tr>'
												+'<td rowspan=2 ><div class="time"><div>{{value["game_time"]}}</div><div>{{value["time"]}}</div></div></td>'//时间
												
												+'<td rowspan=2>{{if value["dspl1_0"]}}<span class="odds" data-action={{action( value["game_unique"],4,1,0,"",value["dspl1_0"])}}>{{value["dspl1_0"]}}</span>{{/if}}</td>'//全场 单
												+'<td rowspan=2>{{if value["dspl2_0"]}}<span class="odds" data-action={{action( value["game_unique"],4,2,0,"",value["dspl2_0"] )}}>{{value["dspl2_0"]}}</span>{{/if}}</td>'//全场 双
												+'<td rowspan=2>{{if value["dspl1_1"]}}<span class="odds" data-action={{action( value["game_unique"],4,1,1,"",value["dspl1_1"] )}}>{{value["dspl1_1"]}}</span>{{/if}}</td>'//上半场 单
												+'<td rowspan=2>{{if value["dspl2_1"]}}<span class="odds" data-action={{action( value["game_unique"],4,2,1,"",value["dspl2_1"] )}}>{{value["dspl2_1"]}}</span>{{/if}}</td>'//上半场 双
											+'</tr>'
											+'<tr></tr>'
											+'{{/each}}'
										+'</tbody>'
									+'</table>'
								+'</div>'
							+'</div>'
						+'{{else if i=="bd" && arr.length>0}}'
							+'<div class="bd_box">'
								+'<div class="bd_box_header more_play_sub_name">'
									+'<div>波胆</div>'
								+'</div>'
								+'<div class="bd_box_table">'
									+'<table cellpadding=0 cellspacing=0>'
										+'<thead>'
											+'<tr>'
												+'<th style="width:35px;"></th>'
												+'<th width=40>1-0</th>'
												+'<th width=40>2-0</th>'
												+'<th width=40>2-1</th>'
												+'<th width=40>3-0</th>'
												+'<th width=40>3-1</th>'
												+'<th width=40>3-2</th>'
												+'<th width=40>4-0</th>'
												+'<th width=40>4-1</th>'
												+'<th width=40>4-2</th>'
												+'<th width=40>4-3</th>'
												+'<th width=40>0-0</th>'
												+'<th width=40>1-1</th>'
												+'<th width=40>2-2</th>'
												+'<th width=40>3-3</th>'
												+'<th width=40>4-4</th>'
												+'<th width=40 style="border-right:0;">其他</th>'
											+'</tr>'
										+'</thead>'
										+'<tbody>'
											+'{{each arr as value a}}'
											+'<tr>'
												+'<td style="width:50px" rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div>{{value["time"]}}</div></div></td>' //生成时间
												
												+'<td width=40>{{if value["pl_1_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_0",0,"",value["pl_1_0"] ) }}>{{value["pl_1_0"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_2_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_0",0,"",value["pl_2_0"] ) }}>{{value["pl_2_0"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_2_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_1",0,"",value["pl_2_1"] ) }}>{{value["pl_2_1"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_3_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_0",0,"",value["pl_3_0"] ) }}>{{value["pl_3_0"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_3_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_1",0,"",value["pl_3_1"] ) }}>{{value["pl_3_1"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_3_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_2",0,"",value["pl_3_2"] ) }}>{{value["pl_3_2"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_4_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_0",0,"",value["pl_4_0"] ) }}>{{value["pl_4_0"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_4_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_1",0,"",value["pl_4_1"] ) }}>{{value["pl_4_1"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_4_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_2",0,"",value["pl_4_2"] ) }}>{{value["pl_4_2"]}}</span>{{/if}}</td>'
												+'<td width=40>{{if value["pl_4_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_4_3",0,"",value["pl_4_3"] ) }}>{{value["pl_4_3"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_0_0"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_0",0,"",value["pl_0_0"] ) }}>{{value["pl_0_0"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_1_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_1",0,"",value["pl_1_1"] ) }}>{{value["pl_1_1"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_2_2"]}}<span class="odds"  data-action={{ action( value["game_unique"],6,"pl_2_2",0,"",value["pl_2_2"] ) }}>{{value["pl_2_2"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_3_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_3",0,"",value["pl_3_3"] ) }}>{{value["pl_3_3"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_4_4"]}}<span class="odds"  data-action={{ action( value["game_unique"],6,"pl_4_4",0,"",value["pl_4_4"] ) }}>{{value["pl_4_4"]}}</span>{{/if}}</td>'
												+'<td width=40 rowspan=2>{{if value["pl_5up"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_5up",0,"",value["pl_5up"] ) }}>{{value["pl_5up"]}}</span>{{/if}}</td>'
											+'</tr>'
											+'<tr>'
												
												+'<td>{{if value["pl_0_1"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_1",0,"",value["pl_0_1"] ) }}>{{value["pl_0_1"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_0_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_2",0,"",value["pl_0_2"] ) }}>{{value["pl_0_2"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_1_2"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_2",0,"",value["pl_1_2"] ) }}>{{value["pl_1_2"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_0_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_3",0,"",value["pl_0_3"] ) }}>{{value["pl_0_3"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_1_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_3",0,"",value["pl_1_3"] ) }}>{{value["pl_1_3"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_2_3"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_3",0,"",value["pl_2_3"] ) }}>{{value["pl_2_3"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_0_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_0_4",0,"",value["pl_0_4"] ) }}>{{value["pl_0_4"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_1_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_1_4",0,"",value["pl_1_4"] ) }}>{{value["pl_1_4"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_2_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_2_4",0,"",value["pl_2_4"] ) }}>{{value["pl_2_4"]}}</span>{{/if}}</td>'
												+'<td>{{if value["pl_3_4"]}}<span class="odds" data-action={{ action( value["game_unique"],6,"pl_3_4",0,"",value["pl_3_4"] ) }}>{{value["pl_3_4"]}}</span>{{/if}}</td>'
											+'</tr>'
											+'{{/each}}'
										+'</tbody>'
									+'</table>'
								+'</div>'
							+'</div>'
						+'{{else if i=="rqs" && arr.length>0}}'
							+'<div class="rqs_box">'
								+'<div class="rqs_box_header  more_play_sub_name">'
									+'<div>入球数</div>'
								+'</div>'
								+'<div class="rqs_box_table">'
									+'<table cellpadding=0 cellspacing=0>'
										+'<thead>'
											+'<tr>'
												+'<th rowspan=2 width=80></th>'							
												+'<th colspan=4>全场</th>'
												+'<th colspan=4>上半场</th>'
											+'</tr>'
											+'<tr>'
												+'<th width=70>0-1</th>'
												+'<th width=70>2-3</th>'
												+'<th width=70>4-6</th>'
												+'<th width=70>7或以上</th>'
												+'<th width=70>0</th>'
												+'<th width=70>1</th>'
												+'<th width=70>2</th>'
												+'<th width=70>3或以上</th>'
											+'</tr>'
										+'</thead>'
										+'<tbody>'
											+'{{each arr as value a}}'
												+'<tr>'
													+'<td rowspan=2><div class="time"><div>{{value["game_time"]}}</div><div>{{value["time"]}}</div></div></td>'//时间
													
													+'<td rowspan=2 width=70>{{if value["pl_0_1_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_0_1",0,"",value["pl_0_1_0"] ) }}>{{value["pl_0_1_0"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_2_3_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_2_3",0,"",value["pl_2_3_0"] ) }}>{{value["pl_2_3_0"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_4_6_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_4_6",0,"",value["pl_4_6_0"] ) }}>{{value["pl_4_6_0"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_7up_0"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_7up",0,"",value["pl_7up_0"] ) }}>{{value["pl_7up_0"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_0_1_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_0_1",1,"",value["pl_0_1_1"] ) }}>{{value["pl_0_1_1"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_2_3_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_2_3",1,"",value["pl_2_3_1"] ) }}>{{value["pl_2_3_1"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_4_6_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_4_6",1,"",value["pl_4_6_1"] ) }}>{{value["pl_4_6_1"]}}</span>{{/if}}</td>'
													+'<td rowspan=2 width=70>{{if value["pl_7up_1"]}}<span class="odds" data-action={{ action( value["game_unique"],5,"pl_7up",1,"",value["pl_7up_1"] ) }}>{{value["pl_7up_1"]}}</span>{{/if}}</td>'
												+'</tr>'
												+'<tr>'
													
												+'</tr>'
											+'{{/each}}'
										+'</tbody>'
									+'</table>'
								+'</div>'
							+'</div>'
						+'{{else if i="bqc" && arr.length>0}}'
							+'<div class="bqc_box">'
								+'<div class="bqc_box_header  more_play_sub_name">'
									+'<div>半全场</div>'
								+'</div>'
								+'<div class="bqc_box_table">'
									+'<table cellpadding=0 cellspacing=0>'
										+'<thead>'
											+'<tr>'
												+'<th width=80></th>'
												+'<th width=60>主主</th>'
												+'<th width=60>主和</th>'
												+'<th width=60>主客</th>'
												+'<th width=60>和主</th>'
												+'<th width=60>和和</th>'
												+'<th width=60>和客</th>'
												+'<th width=60>客主</th>'
												+'<th width=60>客和</th>'
												+'<th width=60>客客</th>'
											+'</tr>'
										+'</thead>'
										+'<tbody>'
											+'{{each arr as value a}}'
													+'<tr>'
														+'<td rowspan=2 width=80><div class="time"><div>{{value["game_time"]}}</div><div>{{value["time"]}}</div></div></td>' //时间
														
														+'<td width=60 rowspan=2>{{if value["pl_H_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_H",0,"",value["pl_H_H"] ) }}>{{value["pl_H_H"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_H_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_N",0,"",value["pl_H_N"] ) }}>{{value["pl_H_N"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_H_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_H_C",0,"",value["pl_H_C"] ) }}>{{value["pl_H_C"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_N_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_H",0,"",value["pl_N_H"] ) }}>{{value["pl_N_H"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_N_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_N",0,"",value["pl_N_N"] ) }}>{{value["pl_N_N"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_N_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_N_C",0,"",value["pl_N_C"] ) }}>{{value["pl_N_C"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_C_H"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_H",0,"",value["pl_C_H"] ) }}>{{value["pl_C_H"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_C_N"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_N",0,"",value["pl_C_N"] ) }}>{{value["pl_C_N"]}}</span>{{/if}}</td>'
														+'<td width=60 rowspan=2>{{if value["pl_C_C"]}}<span class="odds" data-action={{ action( value["game_unique"],7,"pl_C_C",0,"",value["pl_C_C"] ) }}>{{value["pl_C_C"]}}</span>{{/if}}</td>'
													+'</tr>'
													+'<tr>'
														
													+'</tr>'
											+'{{/each}}'
										+'</tbody>'
									+'</table>'
								+'</div>'
							+'</div>'
						+'{{/if}}'
						+'{{/each}}'
					+'</div></div>'
					+'<div class="more_play_scroll_box right"></div>'
				+'</div>'
			+'</div>'
		+'</div>',

	"alert_box":''
		+'<div class="alert_box_sub">'
			+'<div class="alert_box_sub_header">{{header}}<div class="close_alert_box {{close_btn["clas"]}}" data-fn={{close_btn["fn"]}} ></div></div>'
			+'<div class="alert_box_sub_content"><div class="alert_box_sub_content_item">{{#content}}</div></div>'
			+'<div class="alert_box_sub_footer">'
				+'{{each btn as value i}}'
					+'<input type="button" class="alert_box_sub_btn {{i}}" value="{{value["text"]}}" data-fn={{value["fn"]}} >'
				+'{{/each}}'
			+'</div>'
		+'</div>',

	page_left_nowList_content_box:''
		+'<div class="page_left_nowList_content_box">'
			+'<div class="showSportMenu">返回体育菜单</div>'
			+'<div class="page_left_nowList_title">投注菜单</div>'
			+'<div class="page_left_nowList_content">'
				+'<div class="page_left_nowList_content_sub" nowlist-gameunique={{gameUnique}}>'
					+'<div class="nowList_title clearfix"><div class="nowList_title_text left">{{title}}</div><div class="close_nowList_nogg right"></div></div>'
					+'<div class="nowList_name">'
						+'{{ getName( playLx, playLx==10?"Gj":playObj , gName1, gName2 ) }}'
						+'{{if playLx == 2}}'
							+'{{# pkName( playLx==10?"Gj":playObj, pkNum ) }}'
						+'{{else if playLx == 3}}'
							+'{{ pkNum }}'
						+'{{/if}}'
						+'@<span class="betPl">{{betPl}}</span>'
					+'</div>'
					+'{{if playLx!=10}}'
						+'<div class="nowList_gname clearfix">'
							+'<span class="nowList_gname1 left">{{gName1}}</span>'
							+'<span class="active left">vs</span>'
							+'<span class="nowList_gname2 left">{{gName2}}</span>'
						+'</div>'
					+'{{/if}}'
				+'</div>'
			+'</div>'
			+'<div class="user_scalable_box">'
				+'<div class="nowList_input_box clearfix">'
					+'<div class="betMoney_box left">'
						+'<input type="text" class="betMoney" placeholder="输入金额"/>'
					+'</div>'
					+'<div class="yingli_box right right"><input class="yingli" type="text" readonly="readonly" placeholder="可盈利"></div>'
				+'</div>'
				+'<div class="nowList_bottom_moneyRange">'
					+'{{if minBetNum}}<div class="nowList_minmoney_box clearfix"><span class="nowList_minmoney_text left">最少:</span>     <span class="right minmoney">{{minBetNum}}&nbsp;注</span></div>{{/if}}'
					+'{{if maxBetNum}}<div class="nowList_minmoney_box clearfix"><span class="nowList_minmoney_text left">最多:</span>     <span class="right minmoney">{{maxBetNum}}&nbsp;注</span></div>{{/if}}'
					+'<div class="nowList_minmoney_box clearfix"><span class="nowList_minmoney_text left">最低金额:</span> <span class="right minmoney">{{minMoney}}&nbsp;RMB</span></div>'
					+'<div class="nowList_maxmoney_box clearfix"><span class="nowList_minmoney_text left">最高金额:</span> <span class="right maxmoney">{{maxMoney}}&nbsp;RMB</span></div>'
				+'</div>'
				+'<div class="bet_quick_btn">'
					+'<div class="bet_quick_btn_box">'
						+'<button>25</button>'
						+'<button>50</button>'
						+'<button>100</button>'
						+'<button>250</button>'
						+'<button>500</button>'
						+'<button>1000</button>'
					+'</div>'
					+'<div><span class="clear_money">清除</span></div>'
				+'</div>'
				+'<div class="nogg_nowList_alert_info"></div>'
				+'<div class="nowList_btn">'
					+'<div><input type="button" class="nowList_btn_ok" value="投注"></div><div><input type="button" class="nowList_btn_no" value="取消"></div>'
					+'<div class="user_choose_beting_rule">'
						/*
						+'<div onclick="$(this).find(\'.accept_better_odds_btn\').toggleClass(\'true\')">'
							+'<span class="accept_better_odds_btn true"></span><span>是否接受更好赔率</span>'
						+'</div>'
						*/
						+'<div onclick="$(this).find(\'.isShow_confirm_beting_btn\').toggleClass(\'true\')">'
							+'<span class="isShow_confirm_beting_btn true"></span><span>是否显示确认投注框</span>'
						+'</div>'
					+'</div>'
				+'</div>'
			+'</div>'
		+'</div>',

	page_left_nowList_content:''
			+'<div class="page_left_nowList_content_sub" nowlist-gameunique={{gameUnique}}>'
				+'<div class="nowList_title clearfix"><div class="nowList_title_text left">{{title}}</div><div class="close_nowList_nogg right"></div></div>'
				+'<div class="nowList_name">'
					+'{{ getName( playLx, playLx==10?"Gj":playObj , gName1, gName2 ) }}'
					+'{{if playLx == 2}}'
						+'{{# pkName( playLx==10?"Gj":playObj, pkNum ) }}'
					+'{{else if playLx == 3}}'
						+'{{ pkNum }}'
					+'{{/if}}'
					+'@<span class="betPl">{{betPl}}</span>'
				+'</div>'
				+'{{if playLx!=10 }}'
					+'<div class="nowList_gname clearfix">'
						+'<span class="nowList_gname1 left">{{gName1}}</span>'
						+'<span class="active left">vs</span>'
						+'<span class="nowList_gname2 left">{{gName2}}</span>'
					+'</div>'
				+'{{/if}}'
			+'</div>',

	'beenList':''
		+'<div>'
			+'{{each result as value i}}'
				+'<div class="beenList_sub_item">'
					+'{{if value["gg_info"]}}'
						+'<div style="margin-bottom:3px;">'
							+'{{each value["gg_info"] as val }}'
								+'<div class="gg_item_info" style="margin-bottom:2px;">'
									+'<div>{{#val["event_info"]}}</div>'
									+'<div><span class="beenList_sub_item_select_info">{{val["select_info"]}}</span> @  <span class="beenList_sub_item_bet_pl">{{val["bet_pl"]}}</span> &nbsp; {{val["pan_type"]}}  </div>'
								+'</div>'
							+'{{/each}}'
						+'</div>'
					+'{{else}}'
						+'<div class="beenList_sub_item_title">{{value["title"]}}</div>'
						+'<div class="beenList_sub_item_event_info">{{#value["event_info"]}}</div>'
						+'<div><span class="beenList_sub_item_select_info">{{value["select_info"]}}</span> @ <span class="beenList_sub_item_bet_pl">{{value["bet_pl"]}}</span></div>'
				
					+'{{/if}}'
					+'<div>[<span class="beenList_sub_item_bet_money">{{value["bet_money"]}}</span>]&nbsp;<span class="beenList_sub_item_status">{{value["status"]}}</span> &nbsp;&nbsp;{{value["pan_type"]}}</div>'
					+'<div data-id={{value["id"]}}>{{value["bet_time"]}}</div>'
				+'</div>'
			+'{{/each}}'
		+'</div>',

	"betStatus":''
		+'<div class="betStatus">'
			+'<div class="bet_status_{{status}} bet_status">{{statusText}}</div>'
			+'<div class="bet_money"><span class="bet_money_sub">下注金额</span>:{{betMoney}}</div>'
			+'<div class="bet_panType"><span class="bet_panType_sub">盘口类型</span>:{{panType}}</div>'
			+'<div class="bet_id"><span class="bet_id_sub">投注单号</span>:{{betId}}</div>'
			+'<div class="bet_time"><span class="bet_time_sub">投注时间</span>:{{betTime}}</div>'			
			+'<div class="bet_btn_box">'
				+'<input type="button" value="关闭" class="bet_status_btn_close">'
			+'</div>'
		+'</div>'

}

})