define(function(reqiure,exports,module){
    module.exports = {

        'menuBox':''
            +'<div class="menu">'
                +'<ul class="parent">'
                    +'<li class="quick outroom"></li>'
                    /*
					+'<li class="quick more">'
                        +'<ul>'
                            +'<li class="exit" data-url="/" >退出</li>'
                            +'<li class="account {{if is_test==1}}disabled{{/if}} " >账户</li>'
                            +'<li class="service {{if is_test==1}}disabled{{/if}} " >客服</li>'
                            +'<li class="promotion {{if is_test==1}}disabled{{/if}} " >推广</li>'
                        +'</ul>'
                    +'</li>'
					*/
                    +'<li class="quick selections">菜单'
                        +'<ul>'
                            +'<li class="rule">规则</li>'
                            +'<li class="notice">公告</li>'
                            +'<li class="report">报表</li>'
                            +'<li class="result">结果</li>'
                        +'</ul>'
                    +'</li>'
                    +'<li class="btn open" style="display:none"></li>'
                    +'<li class="btn next" style="display:none"></li>'
                +'</ul>'
                +'<div class="special-tips"></div>'
            +'</div>',


        'roomsBox':''
            +'<div class="room-wrap">'
                +'<div class="rooms-list" style="">'
                +'</div>'
                +'<div class="rooms-item">'
                    +'<ul class="rooms">'
                        +'{{each rooms as room i}}'
                        +'<li class="{{if roomId == room["id"]}}active{{/if}} {{if room["use_flag"]!=1}}disabled{{/if}}" id={{room["id"]}} fp_flag={{room["fp_flag"]}} use_flag={{room["use_flag"]}} use_type={{room["use_type"]}} max={{room["bet_max"]}} min={{room["bet_min"]}} ><img src="./css/kc/images/an{{room["id"]}}.png" alt=""></li>'
                        +'{{/each}}'
                    +'</ul>'
                +'</div>'
            +'</div>'
            +'<div class="mask"></div>'
            +'<div class="loading"></div>',

        'desksBox':''
            +'{{if fp_flag==1}}'
            +'<ul class="list">'
            +'{{each desks as desk i}}'
                +'<li id={{desk["id"]}} net_no={{net_no}} showId={{desk["show_id"]}} class="{{if desk["sign"]==1}}cover{{/if}}" >'
                    +'<span class="number">{{desk["show_id"]}}</span>'
                    +'<span class="name">{{if desk["room_id"] == 1}}经典{{else if desk["room_id"]==2}}贵宾{{else if desk["room_id"]==3}}至尊{{else if desk["room_id"]==4}}私密{{else if desk["room_id"]==5}}试玩{{/if}}房</span>'
                    +'<span class="round"> 第{{desk["cur_per"]}}局 </span>'
                    +'<span class="people">{{desk["cur_user_num"]}}人</span>'
                    +'<span id={{desk["id"]}} class="insert"></span>'
                +'</li>'
            +'{{/each}}'
            +'</ul>'
            +'{{else}}'
            +'<div class="list fpmask">'
                +'<div class="title">非游戏时间，开盘时间08:45~24:00</div>'
                +'<div class="btns">'
                    +'<a href="index.php">首页</a>'
                    +'{{if dq==1}}<a href="sport.php">体育</a>{{/if}}'
                    +'{{if cp==1}}<a href="lottery.php">彩票</a>{{/if}}'
                +'</div>'
                +'<div class="btn report"><span>查看报表</span></div>'
            +'</div>'
            +'{{/if}}',

            
        'sitesBox':''
            +'<span class="show-cards"></span>'
            +'<div class="tablet"  oncontextmenu="return false"  onselectstart="return false">'
                +'<span class="nick" title="点我修改昵称">昵称: {{user["u_name_nick"]}} </span>'
                +'{{if cur_user}}<span class="crowd">人数: {{cur_user.length}} 人</span>{{/if}}'
                +'<span class="balance">金币: {{user["u_money"]}} </span>'
            +'</div>'
            +'<img oncontextmenu="return false"  onselectstart="return false" src="./css/kc/images/desk-land.png" alt="" class="desk-img landscape">'
            +'<img oncontextmenu="return false"  onselectstart="return false" src="./css/kc/images/desk-port.png" alt="" class="desk-img portrait">'
            +'<img oncontextmenu="return false"  onselectstart="return false" src="./css/kc/images/waiter.png" alt="" class="waiter">'
            +'<div class="container"  oncontextmenu="return false"  onselectstart="return false">'
                +'<div class="sum"><span>{{desk_info["total_money"]}}</span></div>'
                +'<div class="tips">'
                    +'<span class="periods" periods={{desk_info["periods"]}} lastest_periods={{desk_info["lastest_periods"]}} >{{desk_info["desk_id"]}}号台/{{desk_info["current_js"]}}期</span>'
                    +'<span class="timer" time={{desk_info["dj_time"]}} fp_time={{desk_info["fp_time_index"]}} >{{time}}</span>'
                    +'<span class="text">{{if desk_status==1}}下注中{{else if desk_status==2}}等开船{{else}}{{if result}}最新为{{desk_info["lastest_periods_inner"]}}期{{else}}等结果{{/if}}{{/if}}...</span>'
                +'</div>'
                +'<div class="content">'
                    +'<ul class="desk">'
                        +'{{each desk_bet_list as list i}}'
                        +'<li id={{i}} class="{{if desk_info["kc_pos"]==i}}marker{{/if}}">'
                            +'<div class="wrap">'
                                +'<div class="sites" site={{i}} >'
                                    +'<span class="head">{{pos_user_num[i]}}注{{if pos_money[i]["self_pos_order"]}}({{pos_money[i]["self_pos_order"].join(",")}}){{/if}}</span>'
                                    +'<div class="item {{if list.length>0}}{{if pos_money[i]["self_money"]>0}}ship{{/if}}{{else if pos_money[i]["other_money"]>0}}{{else}}{{if desk_status==1}}new{{/if}}{{/if}}">{{if pos_money[i]["self_money"]>0}}{{pos_money[i]["self_money"]}}{{else if pos_money[i]["other_money"]>0}}{{pos_money[i]["other_money"]}}{{else}}{{if desk_status!=1}}0{{/if}}{{/if}}</div>'
                                    +'<span class="foot">{{if list.length==0}}{{if desk_status==1}}下注{{/if}}{{/if}}{{if pos_money[i]["self_money"]>0}}{{pos_money[i]["other_money"]}}{{/if}}</span>'
                                    +'{{if result&&result["pos_money"]}}<span class="last">{{result["pos_money"][i]}}{{/if}}</span>'
                                +'</div>'
                                +'<div class="cards">'
                                +'{{if result && result["pos_card"][i].length>0}}'
                                    +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][0]}}.png" alt="">'
                                    +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][1]}}.png" alt="">'
                                    +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][2]}}.png" alt="">'
                                    +'<div class="point">{{if result["pos_card"][i][3]=="三公"}}{{result["pos_card"][i][3]}}{{else}}{{result["pos_card"][i][3]}}点{{/if}}</div>'
                                +'{{/if}}'
                                +'</div>'
                            +'</div>'
                        +'</li>'
                        +'{{/each}}'
                    +'</ul>'
                +'</div>'
            +'</div>'
            +'<div class="mask"></div>'
            +'<div class="loading"></div>',

        'partialBox':''
            +'{{each desk_bet_list as list i}}'
            +'<li id={{i}} class="{{if desk_info["kc_pos"]==i}}marker{{/if}}">'
                +'<div class="wrap">'
                    +'<div class="sites" site={{i}} >'
                        +'<span class="head">{{pos_user_num[i]}}注{{if pos_money[i]["self_pos_order"]}}({{pos_money[i]["self_pos_order"].join(",")}}){{/if}}</span>'
                        +'<div class="item {{if list.length>0}}{{if pos_money[i]["self_money"]>0}}ship{{/if}}{{else if pos_money[i]["other_money"]>0}}{{else}}{{if desk_status==1}}new{{/if}}{{/if}}">{{if pos_money[i]["self_money"]>0}}{{pos_money[i]["self_money"]}}{{else if pos_money[i]["other_money"]>0}}{{pos_money[i]["other_money"]}}{{else}}{{if desk_status!=1}}0{{/if}}{{/if}}</div>'
                        +'<span class="foot">{{if list.length==0}}{{if desk_status==1}}下注{{/if}}{{/if}}{{if pos_money[i]["self_money"]>0}}{{pos_money[i]["other_money"]}}{{/if}}</span>'
                        +'{{if result&&result["pos_money"]}}<span class="last">{{result["pos_money"][i]}}{{/if}}</span>'
                    +'</div>'
                    +'<div class="cards">'
                    +'{{if result && result["pos_card"][i].length>0}}'
                        +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][0]}}.png" alt="">'
                        +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][1]}}.png" alt="">'
                        +'<img src="./css/kc/images/cards/b-{{result["pos_card"][i][2]}}.png" alt="">'
                        +'<div class="point">{{if result["pos_card"][i][3]=="三公"}}{{result["pos_card"][i][3]}}{{else}}{{result["pos_card"][i][3]}}点{{/if}}</div>'
                    +'{{/if}}'
                    +'</div>'
                +'</div>'
            +'</li>'
            +'{{/each}}',

        'betBox':''
            +'<div class="layout">'
                +'<div class="alert bet">'
                    +'<div class="header">'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<ul class="bet-list">'
                            +'{{each pos_detail as pos i}}'
                            +'<li>'
                                +'<div class="wrap">'
                                    +'<div class="sites">'
                                        +'<div class="item{{if pos["u_name"]==u_name && pos["net_no"]==net_no}} ship{{/if}}">{{pos["bet_money"]}}</div>'
                                        +'<span class="foot">'
                                            +'<span class="nick">{{pos["u_name_nick"]}}</span>'
                                            +'{{if pos["js_money"]}}<span class="money">{{pos["js_money"]}}</span>{{/if}}'
                                        +'</span>'
                                    +'</div>'
                                +'</div>'
                            +'</li>'
                            +'{{/each}}'
                            // +'<li>'
                            // +'</li>'
                            +'{{if desk_status==1}}'
                            +'<li class="new" oncontextmenu="return false"  onselectstart="return false" >'
                                +'<div class="wrap">'
                                    +'<div class="sites">'
                                        +'<div class="item"></div>'
                                        +'<span class="foot">下注到此</span>'
                                    +'</div>'
                                +'</div>'
                            +'</li>'
                            +'{{/if}}'
                        +'</ul>'
                        +'{{if desk_status==1}}'
                            +'<ul class="ship-list">'
                                +'<li data-limit=10 oncontextmenu="return false"  onselectstart="return false"></li>'
                                +'<li data-limit=100 oncontextmenu="return false"  onselectstart="return false"></li>'
                                +'<li data-limit=500 oncontextmenu="return false"  onselectstart="return false"></li>'
                                +'<li data-limit=1000 oncontextmenu="return false"  onselectstart="return false"></li>'
                                +'<li data-limit=10000 oncontextmenu="return false"  onselectstart="return false"></li>'
                                +'<li data-limit=max oncontextmenu="return false"  onselectstart="return false"></li>'
                            +'</ul>'
                        +'{{/if}}'
                    +'</div>'
                +'</div>'
            +'</div>',

        'newBetBox':''
            +'<div class="wrap get">'
                +'<div class="sites">'
                    +'<div class="item ship" oncontextmenu="return false" onselectstart="return false">{{ship}}</div>'
                    +'<span class="foot">'
                        +'<input type="button" class="btn sure" value="确定">'
                        +'<input type="button" class="btn cancel" value="取消">'
                    +'</span>'
                +'</div>'
            +'</div>',

        'cardsBox':''
            +'<div class="cards-list">'
                +'<ul class="cards">'
                    +'{{each desk_info["card_detail"] as cards i}}'
                        +'{{if i<=25}}'
                        +'<li {{if cards["use_flag"]==1}}class="opt5"{{/if}}>'
                            +'<em>{{i+1}}</em>'
                            +'<i>{{i+53}}</i>'
                            +'<img src="./css/kc/images/cards/{{cards["card_num"]}}.jpg" alt="">'
                        +'</li>'
                        +'{{/if}}'
                    +'{{/each}}'
                +'</ul>'
                +'<ul class="cards">'
                    +'{{each desk_info["card_detail"] as cards i}}'
                        +'{{if i>25}}'
                        +'<li {{if cards["use_flag"]==1}}class="opt5"{{/if}}>'
                            +'{{if i<28}}<em>{{i+53}}</em>{{else}}<em class="no"></em>{{/if}}'
                            +'<i>{{i+1}}</i>'
                            +'<img src="./css/kc/images/cards/{{cards["card_num"]}}.jpg" alt="">'
                        +'</li>'
                        +'{{/if}}'
                    +'{{/each}}'
                +'</ul>'
                +'{{if result}}'
                    +'<div class="balls">'
                        +'{{each result["cp_result"] as ball i}}'
                            +'<span class="ball {{ball["color"]}}">{{ball["cp_num"]}}</span>'
                        +'{{/each}}'
                    +'</div>'
                    +'<div class="result_tips">'
                        +'<span>总输: {{result["all_lose"]}}</span>'
                        +'<span>总赢: {{result["all_win"]}}</span>'
                        +'<span>水钱: {{result["wave"]}}</span>'
                    +'</div>'
                +'{{/if}}'
                +'<div class="footer"></div>'
            +'</div>',

        'resultBox':''
            +'<div class="layout">'
                +'<div class="alert">'
                    +'<div class="header">'
                        +'{{if target==1}}'
                            +'<ul class="tab">'
                                +'{{if back}}<li class="back" back="{{back}}" > ‹ 返回</li>{{/if}}'
                                +'<li class="control prev">上期</li>'
                                +'<li class="control next">下期</li>'
                                +'<li class="control">'
                                    +'<select class="sel-periods">'
                                        +'<option>1</option>'
                                    +'</select>'
                                +'</li>'
                            +'</ul>'
                        +'{{/if}}'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<table >'
                            +'{{if target==0}}'
                            +'<thead>'
                                +'<th>期数</th>'
                                +'<th>结果</th>'
                            +'</thead>'
                            +'<tbody>'
                                +'{{each history["periods_list"] as list i}}'
                                +'<tr periods={{i}} >'
                                    +'<td>{{i}}期</td>'
                                    +'<td>'
                                        +'{{if list.length==0}}<span>本局无人下注</span>{{else}}'
                                        +'{{each list as ball j}}'
                                            +'{{if ball["pos"] && ball["color"]}}'
                                                +'<span class="sball num_{{ball["pos"]}}_{{ball["color"]}}">{{ball}}</span>'
                                            +'{{else}}'
                                                +'<span>{{ball}}</span>'
                                            +'{{/if}}'
                                        +'{{/each}}'
                                        +'{{/if}}'
                                    +'</td>'
                                +'</tr>'
                                +'{{/each}}'
                            +'</tbody>'
                            +'{{else}}'
                                +'<tbody>'
                                    +'<tr >'
                                        +'<td>'
                                            +'<ul class="cards">'
                                                +'{{each history["card_detail"] as cards i}}'
                                                    +'{{if i<=25}}'
                                                    +'<li {{if cards["use_flag"]==1}}class="opt5"{{/if}}>'
                                                        +'<em>{{i+1}}</em>'
                                                        +'<i>{{i+53}}</i>'
                                                        +'<img src="./css/kc/images/cards/{{cards["card_num"]}}.jpg" alt="">'
                                                    +'</li>'
                                                    +'{{/if}}'
                                                +'{{/each}}'
                                            +'</ul>'
                                            +'<ul class="cards">'
                                                +'{{each history["card_detail"] as cards i}}'
                                                    +'{{if i>25}}'
                                                    +'<li {{if cards["use_flag"]==1}}class="opt5"{{/if}}>'
                                                        +'{{if i<28}}<em>{{i+53}}</em>{{else}}<em class="no"></em>{{/if}}'
                                                        +'<i>{{i+1}}</i>'
                                                        +'<img src="./css/kc/images/cards/{{cards["card_num"]}}.jpg" alt="">'
                                                    +'</li>'
                                                    +'{{/if}}'
                                                +'{{/each}}'
                                            +'</ul>'
                                            +'{{if history["cp_result"]}}'
                                                +'<div class="balls">'
                                                    +'{{each history["cp_result"] as ball i}}'
                                                        +'<span class="ball {{ball["color"]}}">{{ball["cp_num"]}}</span>'
                                                    +'{{/each}}'
                                                +'</div>'
                                            +'{{/if}}'
                                        +'</td>'
                                    +'</tr>'
                                    +'{{if history["pos_all_money"]}}'
                                    +'<tr>'
                                        +'<td>'
                                            +'<div>本期信息:&nbsp;&nbsp;&nbsp;&nbsp;'
                                                +'<span>总输：{{history["all_lose"]}} </span>'
                                                +'<span>总赢：{{history["all_win"]}} </span>'
                                                +'<span>水位：{{history["wave"]}} </span>'
                                            +'</div>'
                                        +'</td>'
                                    +'</tr>'
                                    +'<tr>'
                                        +'<td>'
                                        +'<div class="result-sites">'
                                            +'{{each history["order_result"] as result i}}'
                                                +'<div class="items">'
                                                    +'<div class="wrap {{if kc_pos==i}}marker{{/if}}">'
                                                        +'<div class="sites" site={{i}} >'
                                                            +'<span class="head">{{history["pos_all_money"][i]["bet_num"]}}注{{if history["pos_all_money"][i]["order_pos"]}}({{history["pos_all_money"][i]["order_pos"].join(",")}}){{/if}}</span>'
                                                            +'<div class="item {{if history["pos_all_money"][i]["all_self_money"]>0}}ship{{/if}}">{{if history["pos_all_money"][i]["all_self_money"]>0}}{{history["pos_all_money"][i]["all_self_money"]}}{{else if history["pos_all_money"][i]["other_all_money"]>0}}{{history["pos_all_money"][i]["other_all_money"]}}{{/if}}</div>'
                                                            +'<span class="foot">{{if history["pos_all_money"][i]["all_self_money"]>0}}{{history["pos_all_money"][i]["other_all_money"]}}{{/if}}</span>'
                                                            +'<span class="last">{{history["pos_all_money"][i]["all_js_money"]}}</span>'
                                                        +'</div>'
                                                        +'<div class="cards">'
                                                        +'{{if history["pos_card"] && history["pos_card"][i].length>0}}'
                                                            +'<img src="./css/kc/images/cards/b-{{history["pos_card"][i][0]}}.png" alt="">'
                                                            +'<img src="./css/kc/images/cards/b-{{history["pos_card"][i][1]}}.png" alt="">'
                                                            +'<img src="./css/kc/images/cards/b-{{history["pos_card"][i][2]}}.png" alt="">'
                                                            +'<div class="point">{{history["pos_card"][i][3]}}点</div>'
                                                        +'{{/if}}'
                                                        +'</div>'
                                                    +'</div>'
                                                    +'<ul class="list">'
                                                        +'{{each result as pos i}}'
                                                        +'<li {{if pos["u_name"]==history["u_name"] && pos["net_no"]==history["net_no"]}} class="cover" {{/if}}>'
                                                            +'<span class="ship">{{pos["bet_money"]}}</span>'
                                                            +'<span class="money">{{pos["js_money"]}}</span>'
                                                            +'<span class="nick">{{pos["u_name_nick"]}}</span>'
                                                        +'</li>'
                                                        +'{{/each}}'
                                                    +'</ul>'
                                                +'</div>'
                                            +'{{/each}}'
                                        +'</div>'
                                        +'</td>'
                                    +'</tr>'
                                    +'{{else}}'
                                    +'<tr><td>你没有下注该局, 不能查看该局派彩结果.</td></tr>'
                                    +'{{/if}}'
                                +'</tbody>'
                            +'{{/if}}'
                        +'</table>'
                    +'</div>'
                +'</div>'
            +'</div>',



        'noticeBox':''
            +'<div class="layout">'
                +'<div class="alert">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                            // +'<li class="back"> ‹ 返回</li>'
                            // +'<li class="active">本周</li>'
                            // +'<li>上周</li>'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<table >'
                            +'<thead>'
                                +'<th colspan=2 >公告信息</th>'
                            +'</thead>'
                            +'<tbody>'
                                +'{{each gg as notice i}}'
                                +'<tr>'
                                    +'<td width="20%">{{if notice["is_top"]==1}}特别公告{{else}}{{notice["game_time"]}}{{/if}}</td>'
                                    +'<td class="text-left">{{notice["gg_gb"]}}</td>'
                                +'</tr>'
                                +'{{/each}}'
                            +'</tbody>'
                        +'</table>'
                    +'</div>'
                +'</div>'
            +'</div>',


        'reportBox':''
            +'<div class="layout">'
                +'<div class="alert">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                            +'{{if isBack}}<li class="back" isBack=1 > ‹ 返回</li>{{/if}}'
                            +'<li data-week=0 class="getWeek{{if weekNum==0}} active{{/if}}">本周</li>'
                            +'<li data-week=-1 class="getWeek{{if weekNum==-1}} active{{/if}}">上周</li>'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<table >'
                            +'{{if target==0}}'
                                
                                +'<thead>'
                                +'<th >日期</th>'
                                +'<th >注单数</th>'
                                +'<th >投注金额</th>'
                                +'<th >有效金额</th>'
                                +'<th >盈利金额</th>'
                                +'</thead>'
                                +'<tbody>'
                                    +'{{each data as row i}}'
                                        +'<tr data-date={{i}} >'
                                            +'<td width="20%">{{i}}</td>'
                                            +'<td>{{row["bc"]["bet_id"]}}</td>'
                                            +'<td>{{row["bc"]["bet_money"]}}</td>'
                                            +'<td>{{row["bc"]["js_money_1"]}}</td>'
                                            +'<td>{{row["bc"]["js_money"]}}</td>'
                                        +'</tr>'
                                    +'{{/each}}'
                                    +'<tr>'
                                        +'<td>合计</td>'
                                        +'<td>{{sum["bc"]["bet_id"]}}</td>'
                                        +'<td>{{sum["bc"]["bet_money"]}}</td>'
                                        +'<td>{{sum["bc"]["js_money_1"]}}</td>'
                                        +'<td>{{sum["bc"]["js_money"]}}</td>'
                                    +'</tr>'
                                +'</tbody>'
                            +'{{else}}'
                                +'<thead>'
                                +'<tr>'
                                    +'<th>编号<br>时间</th>'
                                    +'<th>期数<br>结果</th>'
                                    +'<th>信息</th>'
                                    +'<th>有效金额</th>'
                                    +'<th>结果</th>'
                                +'</tr>'
                                +'</thead>'
                                +'<tbody>'
                                +'{{each data as row i}}'
                                    +'<tr {{if row["betTime"]}} gameTime={{gameTime}} deskId={{row["desk_id"]}} periods={{row["desk_periods"]}} {{/if}}><td>{{row["betId"]}}<br><span class="gray">{{row["betTime"]}}</span></td>'
                                        +'<td>{{if row["cp_periods"]}}<span class="gray">快乐八<br>[{{row["cp_periods"]}} - {{row["desk_periods"]}}]</span>{{if row["totalnumber"]}}<br><span class="gray">{{each row["totalnumber"] as pic p}} <img src="./css/kc/images/cards/{{pic}}.jpg"> {{/each}}</span>{{/if}}{{/if}}</td>'
                                        +'<td>{{if row["desk_id"]}}[第{{row["desk_periods"]}}期]<br><span class="gray">{{row["desk_id"]}}号桌<br>{{row["desk_show_pos"]}}号位</span>{{/if}}</td>'
                                        +'<td><span class="betMoneyObj">{{row["js_money_1"]}}</span><br><span class="gray">{{row["bet_money"]}}</span></td>'
                                        +'<td>{{row["js_money"]}}<br/><span class="gray">{{row["tsvalue"]}}</span></td>'
                                    +'</tr>'
                                +'{{/each}}'
                                +'</tbody>'
                            +'{{/if}}'
                        +'</table>'
                    +'</div>'
                +'</div>'
            +'</div>',

        /*个人信息*/
        'accountBox':''
            +'<div class="layout">'
                +'<div class="alert account">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                            +'<li data-rel="account" class="active">账户</li>'
                            +'<li data-rel="deposit" >存款</li>'
                            +'<li data-rel="withdrawal" >取款</li>'
                            +'<li data-rel="details" >交易明细</li>'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content"  data-rel="account">'
                        +'<table class="responsive">'
                            +'<tbody>'
                                +'<tr>'
                                    +'<td>用户名:</td>'
                                    +'<td>{{user["u_name"]}}</td>'
                                +'</tr>'
                                +'<tr>'
                                    +'<td>账户昵称:</td>'
                                    +'<td class="manage_nick" style="cursor:pointer;">{{user["u_name_nick"]}}</td>'
                                +'</tr>'
                                +'<tr>'
                                    +'<td>账户余额:</td>'
                                    +'<td >{{user["u_money"]}}</td>'
                                +'</tr>'
                                +'<tr>'
                                    +'<td>手机号码:</td>'
                                    +'<td >{{user_ex["u_tel"]}}</td>'
                                +'</tr>'
                            +'</tbody>'
                        +'</table>'
                        +'<div class="contents">'
                            +'<ul>'
                                +'<li>'
                                    //+'<p class="plus" rel="addmore" style="display: block;"><em>添加更多信息</em></p>'
                                    +'<p class="new_item">'
                                        +'<label><span>真实姓名<small>(不可修改)</small>：</span><input real="{{user_ex["u_xm"]}}" value="{{user_ex["u_xm"]}}" {{if user_ex && user_ex["u_xm"]}}disabled{{/if}} class="realname"></label>'
                                        +'<label><span>QQ 号码：</span><input class="qq number" value="{{user_ex["u_qq_id"]}}"></label>'
                                        //+'<label><span>电话号码：</span><input class="tel number" value="{{user_ex["u_tel"]}}"></label>'
                                        +'<label><span>微信号：</span><input class="wx" value="{{user_ex["u_wx_id"]}}"></label>'
                                        +'<label><span>原密码(不修改请留空)：</span><input type="password" class="old_password"></label>'
                                        +'<label><span>新密码：</span><input type="password" class="new_password"></label>'
                                        +'<label><span>重复密码：</span><input type="password" class="confirm_password"></label>'
                                        +'<label class="ctrl"><button class="submit" rel="addmore">保存</button><!--<button class="cancel">取消</button>--></label>'
                                    +'</p>'
                                +'</li>'
                            +'</ul>'
                        +'</div>'
                    +'</div>'
                    +'<div class="content" style="display:none;" data-rel="deposit">'
                        +'存款'
                    +'</div>'
                    +'<div class="content" style="display:none;" data-rel="withdrawal">'
                        +'取款'
                    +'</div>'
                    +'<div class="content" style="display:none;" data-rel="details"></div>'
                +'</div>'
            +'</div>',
        
        /*存款*/
        'depositBox':''
            +'<div class="deposit">'
                +'{{if data}}'
                +'<ul class="options">'   
                    +'{{if data && data[4]}}<li class="weichat active" rel=4  min="{{data[4]["limit_min"]}}" max="{{data[4]["limit_max"]}}"><span><em>微信</em></span></li>{{/if}}'
                    +'{{if data && data[3]}}<li class="alipay" rel=3  min="{{data[3]["limit_min"]}}" max="{{data[3]["limit_max"]}}"><span><em>支付宝</em></span></li>{{/if}}'
                    +'{{if data && data[2]}}<li class="bank " rel=2 min="{{data[2]["limit_min"]}}" max="{{data[2]["limit_max"]}}"><span><em>银行卡</em></span></li>{{/if}}'
                 +'</ul>'
                +'<div class="contents">'
                    +'<ul class="tabs">'
                        +'{{if data && data[4]}}'
                        +'<li rel="weichat">'
                            +'<p>{{data[4]["account_company"]["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[4]["account_company"]["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[4]["account_company"]["bank_pers"]}}</p>'
                            +'<p class="text-center">生成唯一金额，并按同意并支付按钮后，扫描此二维码进行支付<br><img class="w40" src="/qrcode/weixin.png"></p> '
                        +'</li>'
                        +'{{/if}}'
                        +'{{if data && data[3]}}'
                        +'<li rel="alipay" style="display:none;">'
                            +'<p>{{data[3]["account_company"]["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[3]["account_company"]["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[3]["account_company"]["bank_pers"]}}</p>'
                            +'<p class="text-center">生成唯一金额，并按同意并支付按钮后，扫描此二维码进行支付<br><img class="w40" src="/qrcode/zhifubao.png"></p> '
                        +'</li>'
                        +'{{/if}}'
                        +'{{if data && data[2]}}'
                        +'<li rel="bank" style="display:none;">'
                            +'{{if data[2]["account_company"]}}<p>{{data[2]["account_company"]["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[2]["account_company"]["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{data[2]["account_company"]["bank_pers"]}}</p>{{else}}<p>暂无公司账户，请选用其他方式存款。</p>{{/if}}'
                        +'</li>'
                        +'{{/if}}'
                    +'</ul>'
                    +'<div class="inset">'
                        +'<label>存入金额(最低<span class="limit">{{if data && data[2]}}{{data[2]["limit_min"]}}{{else if data && data[3]}}{{data[3]["limit_min"]}}{{else}}{{data[4]["limit_min"]}}{{/if}}</span>元):<input min={{if data && data[2]}}{{data[2]["limit_min"]}}{{else if data && data[3]}}{{data[3]["limit_min"]}}{{else}}{{data[4]["limit_min"]}}{{/if}} max={{if data && data[2]}}{{data[2]["limit_max"]}}{{else if data && data[3]}}{{data[3]["limit_max"]}}{{else}}{{data[4]["limit_max"]}}{{/if}} type="text" class="money_input number"/></label>'
                        +'<button class="generate">生成唯一金额</button>'
                        +'<button rel="agree" class="sure disabled">同意并支付</button>'
                        +'<button rel="complete" class="sure disabled">我&nbsp;已&nbsp;完&nbsp;成&nbsp;转&nbsp;账</button>'
                        +'<p class="title">为了您的存款能更快到账，请转入上面生成的金额。</p>'
                    +'</div>'
                +'</div>'
                +'{{/if}}'
            +'</div>',

        /*取款*/
        'withdrawalBox':''
            +'<div class="withdrawal">'
                +'{{if data}}'
                +'<ul class="options">' 
                    +'<li class="weichat " style="display:none;" rel=4  min="{{limit_min}}" pre_money="{{pre_money}}" total_money="{{total_money}}" u_money={{u_money_bc}} ><span><em>微信</em></span></li>'
                    +'<li class="alipay active" rel=3  min="{{limit_min}}" pre_money="{{pre_money}}" total_money="{{total_money}}" u_money={{u_money_bc}} ><span><em>支付宝</em></span></li>'
                    +'<li class="bank" rel=2 min="{{limit_min}}" pre_money="{{pre_money}}" total_money="{{total_money}}" u_money={{u_money_bc}} ><span><em>银行卡</em></span></li>'
                +'</ul>'
                +'<div class="contents">'
                    +'<ul class="tabs">'
                        +'<li rel="weichat" style="display:none;">'
                            +'{{if data[4] && data[4]["account_user"]}}'
                            +'<p class="select"><select>'
                                +'{{each data[4]["account_user"] as account i}}'
                                    +'<option value="{{account["id"]}}">{{account["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_pers"]}}</option>'
                                +'{{/each}}'
                            +'</select></p>'
                            +'{{/if}}'
                            +'<p class="plus" rel="weichat"><em>添加</em></p>'
                            +'<p class="new_item" style="display:none;">'
                                +'<label><span>微信号：</span><input class="bank_no"></label>'
                                +'<label class="ctrl"><button class="submit" rel="weichat">保存</button><button class="cancel">取消</button></label>'
                            +'</p>'
                        +'</li>'
                        +'<li rel="alipay" >'
                            +'{{if data[3] && data[3]["account_user"]}}'
                            +'<p class="select"><select>'
                                +'{{each data[3]["account_user"] as account i}}'
                                    +'<option value="{{account["id"]}}">{{account["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_pers"]}}</option>'
                                +'{{/each}}'
                            +'</select></p>'
                            +'{{/if}}'
                            +'<p class="plus" rel="alipay"><em>添加</em></p>'
                            +'<p class="new_item" style="display:none;">'
                                +'<label><span>真实姓名：</span><span>{{u_xm}}</span></label>'
                                +'<label><span>支付宝账号：</span><input class="bank_no"></label>'
                                +'<label class="ctrl"><button class="submit" rel="alipay">保存</button><button class="cancel">取消</button></label>'
                            +'</p>'
                        +'</li>'
                        +'<li rel="bank"  style="display:none;">'
                            +'{{if data[2] && data[2]["account_user"]}}'
                            +'<p class="select"><select>'
                                +'{{each data[2]["account_user"] as account i}}'
                                    +'<option value="{{account["id"]}}">{{account["bank_name"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_no"]}}&nbsp;&nbsp;&nbsp;&nbsp;{{account["bank_pers"]}}</option>'
                                +'{{/each}}'
                            +'</select></p>'
                            +'{{/if}}'
                            +'<p class="plus" rel="bank"><em>添加</em></p>'
                            +'<p class="new_item" style="display:none;">'
                                +'<label><span>开户行：</span><select class="list_id">'
                                        +'{{each banks as bank j}}'
                                            +'<option value="{{j}}">{{bank}}</option>'
                                        +'{{/each}}'
                                    +'</select></label>'
                                +'<label><span>银行账号：</span><input class="bank_no number"></label>'
                                +'<label><span>支行名称：</span><input class="bank_addr"></label>'
                                +'<label><span>账户名：</span><span>{{u_xm}}</span></label>'
                                +'<label><span>省：</span><input class="province"></label>'
                                +'<label><span>市：</span><input class="city"></label>'
                                +'<label class="ctrl"><button class="submit" rel="bank">保存</button><button class="cancel">取消</button></label>'
                            +'</p>'
                        +'</li>'
                        
                    +'</ul>'

                    +'<div class="inset special">'
                        +'<label >'
                            +'<select class="change-account">'
                                +'<option value=0 >账户额度：{{u_money_bc}}</option>'
                                +'<option value=1 >佣金额度：{{u_money_yongjin}}</option>'
                            +'</select>'
                        +'</label>'
                        +'<label class="nbmoney" data-money={{u_nbmoney_bc || 0}} >未完成流水：{{u_nbmoney_bc}}</label>'
                        +'<label >提款额度({{limit_min}}~{{per_money}})：<input class="out number money_input" min={{limit_min}} max={{per_money}} ></label>'
                    
                        +'<button rel="submit" class="sure {{if u_nbmoney_bc>0 }}disabled{{/if}}">提交申请</button>'
                        //+'<button rel="complete" class="sure disabled">我&nbsp;已&nbsp;完&nbsp;成&nbsp;转&nbsp;账</button>'
                        +'<p class="title">{{if u_nbmoney_bc>0 }}请先完成未完成的款项。{{/if}}</p>'
                    +'</div>'
                +'</div>'
                +'{{/if}}'
            +'</div>',

        'tradingBox':''
            +'<table >'
                +'<thead>'
                    +'<tr>'
                        +'<th colspan=7 class="select">'
                            +'<select class="month">'
                                +'{{each months as month i}}'
                                    +'<option {{if month==curr}}selected{{/if}} value="{{month}}">{{month}}</option>'
                                +'{{/each}}'
                            +'</select>'
                        +'</th>'
                    +'</tr>'
                    +'<tr>'
                        +'<th width="180">流水号</th>'
                        +'<th>转账金额</th>'
                        +'<th>手续费</th>'
                        +'<th>入账金额</th>'
                        +'<th>申请时间</th>'
                        +'<th>入账时间</th>'
                        +'<th width="60">状态</th>'
                    +'</tr>'
                +'</thead>'
                +'<tbody>'
                    +'{{each trading_bill as bill i}}'
                    +'<tr>'
                        +'<td>{{bill["serial_number"]}}<br/>{{if bill["pay_type"]==1}}[{{if bill["pay_method"]==2}}银行账户{{else if bill["pay_method"]==3}}支付宝{{else if bill["pay_method"]==4}}微信{{/if}}存款]{{else if bill["pay_type"]==2}}[{{if bill["pay_method"]==2}}银行账户{{else if bill["pay_method"]==3}}支付宝{{else if bill["pay_method"]==4}}微信{{/if}}取款]{{else if bill["pay_type"]==5}}[佣金提现]{{else if bill["pay_type"]==6}}[佣金入账]{{/if}}</td>'
                        +'<td>{{bill["money"]}}</td>'
                        +'<td>{{bill["money_shouxu"]}}</td>'
                        +'<td>{{bill["in_money"]}}</td>'
                        +'<td>{{bill["time_1"]}}</td>'
                        +'<td>{{bill["time_2"]}}</td>'
                        +'<td>'
                            +'{{if bill["pay_status"]==-1}}[已取消]'
                            +'{{else if bill["pay_status"]==0}}<button rel="complete" id={{bill["id"]}} class="sure">申请</button>'
                            +'{{else if bill["pay_status"]==1}}[已申请]'
                            +'{{else if bill["pay_status"]==2}}'
                                +'{{if bill["pay_type"]==1}}存款'
                                +'{{else if bill["pay_type"]==2}}取款'
                                +'{{/if}}成功'
                            +'{{/if}}'
                        +'</td>'
                    +'</tr>'
                    +'{{/each}}'
                +'</tbody>'
            +'</table>',

        /*游戏规则*/
        'ruleBox':''
            +'<div class="layout">'
                +'<div class="alert">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<table >'
                            +'<thead>'
                                +'<th colspan=2 >游戏规则</th>'
                            +'</thead>'
                            +'<tbody>'
                                +'<tr>'
                                    +'<td class="text-left">'
                                        +'<h3>发牌</h3>'
                                        +'<p>1.每局事先公布的一副随机顺序的扑克牌（编号为1-80号）；</p>'
                                        +'<p>2.以北京快乐八中奖结果里的20个号码(1~80)作为此局的发牌凭据，每天179局，从早上9：00到晚上12:00结束，每5分钟1局。</p>'
                                        +'<p>3.以第一个开奖号码所对应的扑克牌作为起始位置，然后按顺序发牌。（第二个号码所对应的牌为起始位置的第一只牌）；</p>'
                                        +'<p>4.北京快乐八的1-52结果对应着牌局的1-52号位置，53-80结果则对应着牌局循环从头开始的1-28号位置；当结果号码对应的位置卡牌被使用后，则默认使用下一张位置卡牌，若下一张也被使用，则继续找下一张牌，直至找到没有被使用的牌。</p>'
                                        +'<h3>输赢规则(三公大吃小):</h3>'
                                        +'<p>1. 每局最多6个位置可以下注，每个位置可以供多个玩家下注，顺位按下注时间排序，最少2个位置上有玩家下注才为有效局，否则返回玩家本金。</p>'
                                        +'<p>2. 游戏每场一副扑克(大小鬼除外), 整副牌最大的牌是K、其次是Q、J、10 以此类推，最小是 A ，扑克A到9为数子牌，10、J、Q、K为0点, 每个玩家的3张牌相加的和取个位数为本场点数</p>'
                                        +'<p>3. 点数对比：</p>'
                                        +'<p>&nbsp;&nbsp;a). 三公(三张花牌)＞9点＞8点＞7点＞6点＞5点＞4点＞3点＞2点＞1点＞0点</p>'
                                        +'<p>&nbsp;&nbsp;b). 相同点数时先比花牌数: 两张花牌＞一张花牌＞没带花牌</p>'
                                        +'<p>&nbsp;&nbsp;c). 最大的牌相同时对比花色: 黑桃＞红桃＞梅花＞方块</p>'
                                        +'<p>4. 每场发三张牌相加点数后和其他玩家互相对比点数大小进行名次排名：</p>'
                                        +'<p>&nbsp;&nbsp;a). 先从点数最小的位置的第一顺位扣除佣金（佣金=输赢金额*2.5%），若不够则往下一顺位或上一个点数较小的位置扣除。</p>'
                                        +'<p>&nbsp;&nbsp;b). 从最后扣除水钱的玩家开始计算，先给点数最大的位置的第一顺位玩家赔付，以此顺序依次往下进行赔付，直至赔付完成。</p>'
                                        +'<p>&nbsp;&nbsp;c). 赔付完成后没有输赢的下注为无效投注，投注金额将返还账户。</p>'
                                    +'</td>'
                                +'</tr>'
                            +'</tbody>'
                        +'</table>'
                    +'</div>'
                +'</div>'
            +'</div>',

        /*客服*/
        'serviceBox':''
            +'<div class="layout">'
                +'<div class="alert chat">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                            +'<li data-rel="chat" class="active">客服</li>'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<div class="msgbox">'
                            +'{{each msg as m i}}'
                                +'<div class="msg {{if m["u_admin"]==null}}me{{/if}}">'
                                    +'<span class="nick">{{if m["u_admin"]==null}}{{m["u_name"]}}{{else}}{{m["u_admin"]}}{{/if}}</span>'
                                    +'<span class="date">{{m["insert_date"]}}</span>'
                                    +'<p>{{m["content"]}}</p>'
                                +'</div>'
                            +'{{/each}}'
                        +'</div>'
                        +'<div class="sendbox">'
                            +'<textarea class="message" name="" id="" cols="30" rows="10"></textarea>'
                            +'<button class="send">发送</button>'
                        +'</div>'
                    +'</div>'
                +'</div>'
            +'</div>',

        /*推广*/
        'promotionBox':''
            +'<div class="layout">'
                +'<div class="alert promotion">'
                    +'<div class="header">'
                        +'<ul class="tab">'
                            +'<li rel=0 {{if rel==0}}class="active"{{/if}}>推广</li>'
                            //+'<li rel=1 {{if rel==1}}class="active"{{/if}}>推广佣金</li>'
                            +'<li rel=1 {{if rel==1}}class="active"{{/if}}>推广图</li>'
                            +'<li rel=2 {{if rel==2}}class="active"{{/if}}>对战佣金</li>'
                            +'<li rel=3 {{if rel==3}}class="active"{{/if}}>我的下线</li>'
                        +'</ul>'
                        +'<span class="close">&times;</span>'
                    +'</div>'
                    +'<div class="content">'
                        +'<div rel=0 {{if rel==0}}style="margin-top:30px;"{{else}} style="display:none;"{{/if}}>'
                            +'{{if qr}}<img class="myqrcode JIATHIS_IMG_OK" src="{{qr["qrcode"]}}">'
                            +'<p class="special-text text-left">长按二维码，复制给你的好友，当好友注册后，就会成为你的下线，如此类推，最多能拥有6级下线，每当各级下 线玩游戏并生成有效金额时，你就会得到对应的佣金:<br>{{if qr}}我的地址: {{qr["url"]}}  '
                            +'<button class="pcduan copy" data-clipboard-text="嗨，我发现了一款超好玩的开船游戏，无需下载，点击即玩，你也赶紧去试试吧 → {{qr["url"]}}" data-url="{{qr["url"]}}">复制链接</button>'
                            +'<h4><a style="color:#333;font-size:16px;" class="yidongduan" href="{{qr["url"]}}" target="_blank">长按此处复制链接!</a></h4>{{/if}}</p>'
							+'<div class="social-share"  style="padding:20px 0;"></div>'
                            +'{{/if}}'
                            +'{{if rate}}'
                                +'<table class="responsive">'
                                    +'{{each rate as r i}}'
                                        +'<tr><td>{{i+1}}级</td><td>有效金额x{{r}}%</td></tr>'
                                    +'{{/each}}'
                                +'</table>'
                            +'{{/if}}'
                        +'</div>'
                        +'<div rel=1 {{if rel==1}}{{else}} style="display:none;"{{/if}}>'
                            +'<table class="responsive">'
                                +'<tbody rel=1 >'
                                    +'<tr>'
                                        +'<td><img src="style/images/promotion/1.jpg" data-url="show_jpg.php?jpg=1&user_id={{user_id}}" class="show_big_pic" /></td>'
                                        +'<td><img src="style/images/promotion/2.jpg" data-url="show_jpg.php?jpg=2&user_id={{user_id}}" class="show_big_pic" /></td>'
                                    +'</tr>'
                                    +'<tr>'
                                        +'<td><img src="style/images/promotion/3.jpg" data-url="show_jpg.php?jpg=3&user_id={{user_id}}" class="show_big_pic" /></td>'
                                        +'<td><img src="style/images/promotion/4.jpg" data-url="show_jpg.php?jpg=4&user_id={{user_id}}" class="show_big_pic" /></td>'
                                    +'</tr>'
                                +'</tbody>'
                            +'</table>'
                        +'</div>'
                        +'<div rel=2 {{if rel==2}}{{else}} style="display:none;"{{/if}}>'
                            +'<div class="fix-show">'
                                +'<p class="text-center">'
                                    +'<select name="" id="" rel=2 >'
                                        +'<option value="0">所有下线</option>'
                                        +'{{each levels as level i}}'
                                            +'<option value="{{i+1}}">{{level}}</option>'
                                        +'{{/each}}'
                                    +'</select>'
                                +'</p>'
                                +'<p class="total_yongjin">当前级佣金总额：{{total_yongjin}}<button max={{u_money_yongjin}} class="button yj2account {{if u_money_yongjin==0}}disabled{{/if}}">佣金入账(可入账金额:{{u_money_yongjin}})</button></p>'
                            +'</div>'
                            +'<div class="special">'
                                +'<table class="responsive">'
                                    +'<tbody rel=2 >'
                                    +'<tr>'
                                        +'<th>用户</th>'
                                        +'<th>有效金额</th>'
                                        +'<th>佣金</th>'
                                    +'</tr>'
                                    +'{{each lowers_yongjin as lower i}}'
                                        +'<tr>'
                                            +'<td>{{lower["parm_xx_name"]}}</td>'
                                            +'<td>{{lower["js_money"]}}</td>'
                                            +'<td>{{lower["yongjin"]}}</td>'
                                        +'</tr>'
                                    +'{{/each}}'
                                    +'<tbody>'
                                +'</table>'
                            +'</div>'
                        +'</div>'
                        +'<div rel=3 {{if rel==3}}{{else}} style="display:none;"{{/if}}>'
                            +'<table  class="responsive">'
                                +'<thead>'
                                    +'<tr>'
                                        +'<th colspan="3">'
                                            +'<select name="" id="" rel=3 >'
                                                +'<option value="0">所有下线</option>'
                                                +'{{each levels as level i}}'
                                                    +'<option value="{{i+1}}">{{level}}</option>'
                                                +'{{/each}}'
                                            +'</select>'
                                        +'</th>'
                                    +'</tr>'
                                +'</thead>'
                                +'<tbody rel=3 >'
                                    +'<tr>'
                                        +'<th>序号</th>'
                                        +'<th>用户名</th>'
                                    +'</tr>'
                                    +'{{each lowers as lower i}}'
                                        +'<tr>'
                                            +'<td>{{i+1}}</td>'
                                            +'<td>{{lower}}</td>'
                                        +'</tr>'
                                    +'{{/each}}'
                                +'</tbody>'
                            +'</table>'
                        +'</div>'
                    +'</div>'
                +'</div>'
            +'</div>',


    };
});