// JavaScript Document
define(function(require, exports, module){
    module.exports = {
    'pageHeader':''
        +'{{if backBtn == 1}}'
            +'<span id="back" step="-1"><input type="submit" data-inline="true" data-theme="a" data-icon="arrow-l" data-iconpos="left" value="返回"></span>'
            +'<span id="headerTitle">{{pageTitle}}</span>'
            +'<span id="shuaxin" step="0"><input type="submit" data-theme="a" data-icon="forward" data-iconpos="left" data-mini="true" value="刷新"></span>'
        +'{{else}}'
            +'<span id="headerTitle">{{pageTitle}}</span>'
        +'{{/if}}',
        
    'homeImgBtn':''
        +'{{if u_flag_dq==1}}<a href="sport.php" rel="external"><dd id="sportsIco"></dd><dt>体育</dt></a>{{/if}}'
        +'{{if u_flag_cp==1}}<a href="lottery.php" rel="external"><dd id="lotteryIco"></dd><dt>彩票</dt></a>{{/if}}'
        +'{{if u_flag_bc==1}}<a href="kc.php" rel="external"><dd id="kcIco"></dd><dt>对战游戏</dt></a>{{/if}}'
        +'<a href="account.php?as=Result" rel="external"><dd id="resultIco"></dd><dt>赛果/开奖</dt></a>'
        +'<a href="account.php?as=Order" rel="external"><dd id="reportIco"></dd><dt>注单报表</dt></a>'
        +'<a href="account.php?as=Account" rel="external"><dd id="accountIco"></dd><dt>会员账户</dt></a>'
        +'<a href="helf.html" rel="external"><dd id="helfIco"></dd><dt>常见问题</dt></a>',
    
    'pageFooter':''
        +'<div data-role="navbar" data-iconpos="top" role="navigation"><ul>'
        +'<li><a href="home.php" data-icon="home" rel="external" data-transition="flip" data-theme="f">首頁</a></li>'
        +'{{if u_flag_dq==1}}<li><a href="sport.php" data-icon="sports" rel="external" data-transition="flip" data-theme="f">体育</a></li>{{/if}}'
        +'{{if u_flag_cp==1}}<li><a href="lottery.php" data-icon="lottery" rel="external" data-transition="flip" data-theme="f">彩票</a></li>{{/if}}'
        +'{{if u_flag_bc==1}}<li><a href="kc.php" data-icon="kc" rel="external" data-transition="flip" data-theme="f">对战</a></li>{{/if}}'
        +'<li><a href="account.php?as=Account" data-icon="account" rel="external" data-transition="flip" data-theme="f">账户</a></li>'
        //+'<li><a href="index.php" data-icon="logout" rel="external" data-transition="flip" data-theme="f">登出</a></li>'
        +'</ul></div>',
    'dialog':''
        +'<div class="header"><span class="title">{{title}}</span>{{if closeBtn}}<span class="closeBtn">Х</span>{{/if}}</div>'
        +'<div class="content">{{#content}}</div>'
        +'<div class="footer">{{if sureBtn}}<button class="sureBtn">确定</button>{{/if}}{{if backBtn}}<button class="backBtn">返回</button>{{/if}}</div>',
    'resultBoxCP':''
        +'<div id="resultBox">'
        +'{{each pcResult as row i}}'
        +'<dl>'
        +'<dt>{{row["p"]}}</dt>'
        +'<dd>{{each row["n"] as noStr j}}<span>{{noStr}}</span>{{/each}}</dd>'
        +'</dl>'
        +'{{/each}}'
        +'</div>',
    'resultBoxDQ':''
        +'<div id="resultBox">'
        +'<table>'
        +'{{each resultDQ as row i}}'
            +'<tr><td>{{row["info"][1]}}</td><td>VS</td><td>{{row["info"][2]}}</td>'
            +'{{each row["bf"] as bfRow halfLx}}'
                +'<tr><td>{{bfRow[0]}}</td><td>{{halfName[halfLx]}}</td><td>{{bfRow[1]}}</td></tr>'
            +'{{/each}}'
        +'{{/each}}'
        +'</table>'
        +'</div>',
    'orderListBox':''
        +'<div id="orderListBox">'
        +'{{if data}}'
            +'{{each data as row i}}'
            +'<dl>'
            +'<dt>CS{{row.betId}}</dt>'
            +'{{if row.subOrders}}'
                    +'{{each row.subOrders as surRow j}}'
                    +'<dd>{{surRow.orderTitle}}</dd>'
                    +'<dd>{{row.lx}}</dd>'
                    +'<dd>{{#surRow.eventName}}</dd>'
                    +'<dd><span class="betObj">{{surRow.betObjName}}</span> @ <span class="betPlObj">{{surRow.betPl}}</span></dd>'
                    +'{{/each}}'
                    +'<dd>{{row.subNum}} 串 1 ￥ <span class="betMoneyObj">{{row.betMoney}}</span></dd>'
            +'{{else}}'
                +'<dd>{{row.orderTitle}}</dd>'
                +'<dd>{{row.lx}}</dd>'
                +'<dd>{{#row.eventName}}</dd>'
                +'<dd><span class="betObj">{{row.betObjName}}</span> @ <span class="betPlObj">{{row.betPl}}</span> {{if row.panType}}<span class="panTypeObj">[{{row.panType}}]</span>{{/if}}</dd>'
                +'<dd>￥ <span class="betMoneyObj">{{row.betMoney}}</span></dd>'
                +'{{if row.bet_error }}<dd class="WxqStatus{{row.bet_error}}">{{row.betStatus}}</dd>{{/if}}'
            +'{{/if}}'
            +'<dd>{{row.betTime}}</dd>'
            +'</dl>'
            +'{{/each}}'
        +'{{else}}'
            +'<h3>无相关注单信息</h3>'
        +'{{/if}}'
        +'</div>',

        //系统维护
        'maintain':''
            +'<div class="maintain">'
                +'<ul data-role="listview" data-inset="true" >'
                    +'<li><div><h3 class="noData"><span class="Msg_Box_Info"></span><span class="info">{{ up[0] }}</span></h3></div>'
                    +'<div>{{each link as row i}}<a data-role="button" data-inline="true" rel="external" data-theme="c" href="{{row[0]}}.php">{{row[1]}}</a>{{/each}}</div></li>'
                +'</ul>'
            +'</div>',
        
    }
});